Virtual Zoo: test/air_habitat_test.cpp File Reference
air_habitat_test.cpp File Reference
#include "../src/include.h"
#include <gtest/gtest.h>
Data Structures
class AirHabitatTest
Functions
TEST (AirHabitatTest, AirHabitatConstructor)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 19 of file air_habitat_test.cpp.
{
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
TEST (AirHabitatTest , AirHabitatConstructor)
Definition at line 9 of file air_habitat_test.cpp.
References Cell::GetAbsis(), Cell::GetAnimal(), Cell::GetCage(), Cell::GetOrdinat(), and Cell::GetType().
{
     AirHabitat c(10,15);
     EXPECT_EQ('o', c.GetType());
     EXPECT_EQ(10, c.GetAbsis());
     EXPECT_EQ(15, c.GetOrdinat());
     EXPECT_EQ(NULL, c.GetCage());
     EXPECT_EQ(NULL, c.GetAnimal());
 }