Virtual Zoo: test/animal_test.cpp File Reference
animal_test.cpp File Reference
#include "../src/include.h"
#include <gtest/gtest.h>
Data Structures
class AnimalTest
Functions
TEST (AnimalTest, IsJinakFunction)
TEST (AnimalTest, GetInisialFunction)
TEST (AnimalTest, GetIDFunction)
TEST (AnimalTest, GetMassaFunction)
TEST (AnimalTest, GetPosisiXFunction)
TEST (AnimalTest, GetPosisiYFunction)
TEST (AnimalTest, SetMassaFunction)
TEST (AnimalTest, SetXFunction)
TEST (AnimalTest, SetYFunction)
TEST (AnimalTest, AddGetHabitatFunction)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 83 of file animal_test.cpp.
{
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
TEST (AnimalTest , IsJinakFunction)
Definition at line 9 of file animal_test.cpp.
References Animal::IsJinak().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   EXPECT_EQ(true, a->IsJinak());
 }
TEST (AnimalTest , GetInisialFunction)
Definition at line 16 of file animal_test.cpp.
References Animal::GetInisial().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   EXPECT_EQ('U', a->GetInisial());
 }
TEST (AnimalTest , GetIDFunction)
Definition at line 23 of file animal_test.cpp.
References Animal::GetID().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
    EXPECT_EQ(1, a->GetID());
 }
TEST (AnimalTest , GetMassaFunction)
Definition at line 30 of file animal_test.cpp.
References Animal::GetMassa().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   EXPECT_EQ(100, a->GetMassa());
 }
TEST (AnimalTest , GetPosisiXFunction)
Definition at line 37 of file animal_test.cpp.
References Animal::GetPosisiX().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   EXPECT_EQ(10, a->GetPosisiX());
 }
TEST (AnimalTest , GetPosisiYFunction)
Definition at line 44 of file animal_test.cpp.
References Animal::GetPosisiY().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   EXPECT_EQ(1, a->GetPosisiY());
 }
TEST (AnimalTest , SetMassaFunction)
Definition at line 51 of file animal_test.cpp.
References Animal::GetMassa(), and Animal::SetMassa().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   a->SetMassa(50);
   EXPECT_EQ(50, a->GetMassa());
 }
TEST (AnimalTest , SetXFunction)
Definition at line 59 of file animal_test.cpp.
References Animal::GetPosisiX(), and Animal::SetX().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   a->SetX(5);
   EXPECT_EQ(5, a->GetPosisiX());
 }
TEST (AnimalTest , SetYFunction)
Definition at line 67 of file animal_test.cpp.
References Animal::GetPosisiY(), and Animal::SetY().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   a->SetY(5);
   EXPECT_EQ(5, a->GetPosisiY());
 }
TEST (AnimalTest , AddGetHabitatFunction)
Definition at line 75 of file animal_test.cpp.
References Animal::AddHabitat(), and Animal::GetHabitat().
{
   Animal* a;
   a= new OrangUtan(1, 10, 1, 100, true);
   a->AddHabitat('x');
   EXPECT_EQ('x', a->GetHabitat()[0]);
 }