Virtual Zoo: test/carnivore_test.cpp File Reference
carnivore_test.cpp File Reference
#include "../src/include.h"
#include <gtest/gtest.h>
Data Structures
class CarnivoreTest
Functions
TEST (CarnivoreTest, CarnivoreConstructor)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 21 of file carnivore_test.cpp.
{
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
TEST (CarnivoreTest , CarnivoreConstructor)
Definition at line 9 of file carnivore_test.cpp.
References Animal::GetID(), Animal::GetInisial(), HarimauSumatra::GetJmlMakanan(), Animal::GetPosisiX(), Animal::GetPosisiY(), and Animal::IsJinak().
{
   HarimauSumatra o(1, 10, 1, 120, true);
   EXPECT_EQ(10, o.GetJmlMakanan());
   EXPECT_EQ(1, o.GetID());
   EXPECT_EQ(true, o.IsJinak());
   EXPECT_EQ(10, o.GetPosisiX());
   EXPECT_EQ(1, o.GetPosisiY());
   EXPECT_EQ('H', o.GetInisial());
 }