Virtual Zoo: nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > Class Template Reference
nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > Class Template Reference
a class to store JSON values
#include <json.hpp>
Data Structures
struct internal_iterator
an iterator value
class iter_impl
a template for a random access iterator for the basic_json class
class iteration_proxy
proxy class for the iterator_wrapper functions
class json_pointer
JSON Pointer.
class json_reverse_iterator
a template for a reverse iterator class
union json_value
a JSON value
class lexer
lexical analysis
class parser
syntax analysis
class primitive_iterator_t
an iterator for primitive JSON types
Public Types
enum parse_event_t : uint8_t {
parse_event_t::object_start, parse_event_t::object_end, parse_event_t::array_start, parse_event_t::array_end,
parse_event_t::key, parse_event_t::value
}
JSON callback events.
using value_t = detail::value_t
template<typename T , typename SFINAE >
using json_serializer = JSONSerializer< T, SFINAE >
using parser_callback_t = std::function< bool(int depth, parse_event_t event, basic_json &parsed)>
per-element parser callback type
Public Member Functions
std::string type_name () const
return the type as string
Static Public Member Functions
static allocator_type get_allocator ()
returns the allocator associated with the container
static basic_json meta ()
returns version information on the library
Private Types
using basic_json_t = basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >
workaround type for MSVC
Private Member Functions
void assert_invariant () const
checks the class invariants
boolean_t get_impl (boolean_t *) const
get a boolean (explicit)
object_t * get_impl_ptr (object_t *) noexcept
get a pointer to the value (object)
constexpr const object_t * get_impl_ptr (const object_t *) const noexcept
get a pointer to the value (object)
array_t * get_impl_ptr (array_t *) noexcept
get a pointer to the value (array)
constexpr const array_t * get_impl_ptr (const array_t *) const noexcept
get a pointer to the value (array)
string_t * get_impl_ptr (string_t *) noexcept
get a pointer to the value (string)
constexpr const string_t * get_impl_ptr (const string_t *) const noexcept
get a pointer to the value (string)
boolean_t * get_impl_ptr (boolean_t *) noexcept
get a pointer to the value (boolean)
constexpr const boolean_t * get_impl_ptr (const boolean_t *) const noexcept
get a pointer to the value (boolean)
number_integer_t * get_impl_ptr (number_integer_t *) noexcept
get a pointer to the value (integer number)
constexpr const number_integer_t * get_impl_ptr (const number_integer_t *) const noexcept
get a pointer to the value (integer number)
number_unsigned_t * get_impl_ptr (number_unsigned_t *) noexcept
get a pointer to the value (unsigned number)
constexpr const number_unsigned_t * get_impl_ptr (const number_unsigned_t *) const noexcept
get a pointer to the value (unsigned number)
number_float_t * get_impl_ptr (number_float_t *) noexcept
get a pointer to the value (floating-point number)
constexpr const number_float_t * get_impl_ptr (const number_float_t *) const noexcept
get a pointer to the value (floating-point number)
void dump (std::ostream &o, const bool pretty_print, const unsigned int indent_step, const unsigned int current_indent=0) const
internal implementation of the serialization function
Static Private Member Functions
template<typename T , typename... Args>
static T * create (Args &&...args)
helper for exception-safe object creation
template<typename ReferenceType , typename ThisType >
static ReferenceType get_ref_impl (ThisType &obj)
helper function to implement get_ref()
static std::size_t extra_space (const string_t &s) noexcept
calculates the extra space to escape a JSON string
static string_t escape_string (const string_t &s)
escape a string
Private Attributes
value_t m_type = value_t::null
the type of the current element
json_value m_value = {}
the value of the current element
Friends
template<detail::value_t >
struct detail::external_constructor
container types
The canonic container types to use basic_json like any other STL container.
using value_type = basic_json
the type of elements in a basic_json container
using reference = value_type &
the type of an element reference
using const_reference = const value_type &
the type of an element const reference
using difference_type = std::ptrdiff_t
a type to represent differences between iterators
using size_type = std::size_t
a type to represent container sizes
using allocator_type = AllocatorType< basic_json >
the allocator type
using pointer = typename std::allocator_traits< allocator_type >::pointer
the type of an element pointer
using const_pointer = typename std::allocator_traits< allocator_type >::const_pointer
the type of an element const pointer
using iterator = iter_impl< basic_json >
an iterator for a basic_json container
using const_iterator = iter_impl< const basic_json >
a const iterator for a basic_json container
using reverse_iterator = json_reverse_iterator< typename basic_json::iterator >
a reverse iterator for a basic_json container
using const_reverse_iterator = json_reverse_iterator< typename basic_json::const_iterator >
a const reverse iterator for a basic_json container
JSON value data types
The data types to store a JSON value. These types are derived from the template arguments passed to class basic_json.
using object_t = ObjectType< StringType, basic_json, std::less< StringType >, AllocatorType< std::pair< const StringType, basic_json >>>
a type for an object
using array_t = ArrayType< basic_json, AllocatorType< basic_json >>
a type for an array
using string_t = StringType
a type for a string
using boolean_t = BooleanType
a type for a boolean
using number_integer_t = NumberIntegerType
a type for a number (integer)
using number_unsigned_t = NumberUnsignedType
a type for a number (unsigned)
using number_float_t = NumberFloatType
a type for a number (floating-point)
constructors and destructors
Constructors of class basic_json, copy/move constructor, copy assignment, static functions creating objects, and the destructor.
static basic_json array (std::initializer_list< basic_json > init=std::initializer_list< basic_json >())
explicitly create an array from an initializer list
static basic_json object (std::initializer_list< basic_json > init=std::initializer_list< basic_json >())
explicitly create an object from an initializer list
basic_json (const value_t value_type)
create an empty value with a given type
basic_json (std::nullptr_t=nullptr) noexcept
create a null object
template<typename CompatibleType , typename U = detail::uncvref_t<CompatibleType>, detail::enable_if_t< not std::is_base_of< std::istream, U >::value andnot std::is_same< U, basic_json_t >::value andnot detail::is_basic_json_nested_type< basic_json_t, U >::value anddetail::has_to_json< basic_json, U >::value, int > = 0>
basic_json (CompatibleType &&val) noexcept(noexcept(JSONSerializer< U >::to_json(std::declval< basic_json_t & >(), std::forward< CompatibleType >(val))))
create a JSON value
basic_json (std::initializer_list< basic_json > init, bool type_deduction=true, value_t manual_type=value_t::array)
create a container (array or object) from an initializer list
basic_json (size_type cnt, const basic_json &val)
construct an array with count copies of given value
template<class InputIT , typename std::enable_if< std::is_same< InputIT, typename basic_json_t::iterator >::value orstd::is_same< InputIT, typename basic_json_t::const_iterator >::value, int >::type = 0>
basic_json (InputIT first, InputIT last)
construct a JSON container given an iterator range
basic_json (std::istream &i, const parser_callback_t cb=nullptr)
construct a JSON value given an input stream
basic_json (const basic_json &other)
copy constructor
basic_json (basic_json &&other) noexcept
move constructor
reference & operator= (basic_json other) noexcept(std::is_nothrow_move_constructible< value_t >::value andstd::is_nothrow_move_assignable< value_t >::value andstd::is_nothrow_move_constructible< json_value >::value andstd::is_nothrow_move_assignable< json_value >::value)
copy assignment
~basic_json ()
destructor
object inspection
Functions to inspect the type of a JSON value.
string_t dump (const int indent=-1) const
serialization
constexpr value_t type () const noexcept
return the type of the JSON value (explicit)
constexpr bool is_primitive () const noexcept
return whether type is primitive
constexpr bool is_structured () const noexcept
return whether type is structured
constexpr bool is_null () const noexcept
return whether value is null
constexpr bool is_boolean () const noexcept
return whether value is a boolean
constexpr bool is_number () const noexcept
return whether value is a number
constexpr bool is_number_integer () const noexcept
return whether value is an integer number
constexpr bool is_number_unsigned () const noexcept
return whether value is an unsigned integer number
constexpr bool is_number_float () const noexcept
return whether value is a floating-point number
constexpr bool is_object () const noexcept
return whether value is an object
constexpr bool is_array () const noexcept
return whether value is an array
constexpr bool is_string () const noexcept
return whether value is a string
constexpr bool is_discarded () const noexcept
return whether value is discarded
constexpr operator value_t () const noexcept
return the type of the JSON value (implicit)
value access
Direct access to the stored value of a JSON value.
template<typename BasicJsonType , detail::enable_if_t< std::is_same< typename std::remove_const< BasicJsonType >::type, basic_json_t >::value, int > = 0>
basic_json get () const
get special-case overload
template<typename ValueTypeCV , typename ValueType = detail::uncvref_t<ValueTypeCV>, detail::enable_if_t< not std::is_same< basic_json_t, ValueType >::value anddetail::has_from_json< basic_json_t, ValueType >::value andnot detail::has_non_default_from_json< basic_json_t, ValueType >::value, int > = 0>
ValueType get () const noexcept(noexcept(JSONSerializer< ValueType >::from_json(std::declval< const basic_json_t & >(), std::declval< ValueType & >())))
get a value (explicit)
template<typename ValueTypeCV , typename ValueType = detail::uncvref_t<ValueTypeCV>, detail::enable_if_t< not std::is_same< basic_json_t, ValueType >::value anddetail::has_non_default_from_json< basic_json_t, ValueType >::value, int > = 0>
ValueType get () const noexcept(noexcept(JSONSerializer< ValueTypeCV >::from_json(std::declval< const basic_json_t & >())))
get a value (explicit); special case
template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0>
PointerType get () noexcept
get a pointer value (explicit)
template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0>
constexpr const PointerType get () const noexcept
get a pointer value (explicit)
template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0>
PointerType get_ptr () noexcept
get a pointer value (implicit)
template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value andstd::is_const< typename std::remove_pointer< PointerType >::type >::value, int >::type = 0>
constexpr const PointerType get_ptr () const noexcept
get a pointer value (implicit)
template<typename ReferenceType , typename std::enable_if< std::is_reference< ReferenceType >::value, int >::type = 0>
ReferenceType get_ref ()
get a reference value (implicit)
template<typename ReferenceType , typename std::enable_if< std::is_reference< ReferenceType >::value andstd::is_const< typename std::remove_reference< ReferenceType >::type >::value, int >::type = 0>
ReferenceType get_ref () const
get a reference value (implicit)
template<typename ValueType , typename std::enable_if< not std::is_pointer< ValueType >::value andnot std::is_same< ValueType, typename string_t::value_type >::valueand not std::is_same< ValueType, std::initializer_list< typename string_t::value_type >>::value, int >::type = 0>
operator ValueType () const
get a value (implicit)
element access
Access to the JSON value.
reference at (size_type idx)
access specified array element with bounds checking
const_reference at (size_type idx) const
access specified array element with bounds checking
reference at (const typename object_t::key_type &key)
access specified object element with bounds checking
const_reference at (const typename object_t::key_type &key) const
access specified object element with bounds checking
reference operator[] (size_type idx)
access specified array element
const_reference operator[] (size_type idx) const
access specified array element
reference operator[] (const typename object_t::key_type &key)
access specified object element
const_reference operator[] (const typename object_t::key_type &key) const
read-only access specified object element
template<typename T , std::size_t n>
reference operator[] (T *(&key)[n])
access specified object element
template<typename T , std::size_t n>
const_reference operator[] (T *(&key)[n]) const
read-only access specified object element
template<typename T >
reference operator[] (T *key)
access specified object element
template<typename T >
const_reference operator[] (T *key) const
read-only access specified object element
template<class ValueType , typename std::enable_if< std::is_convertible< basic_json_t, ValueType >::value, int >::type = 0>
ValueType value (const typename object_t::key_type &key, ValueType default_value) const
access specified object element with default value
string_t value (const typename object_t::key_type &key, const char *default_value) const
overload for a default value of type const char*
template<class ValueType , typename std::enable_if< std::is_convertible< basic_json_t, ValueType >::value, int >::type = 0>
ValueType value (const json_pointer &ptr, ValueType default_value) const
access specified object element via JSON Pointer with default value
string_t value (const json_pointer &ptr, const char *default_value) const
overload for a default value of type const char*
reference front ()
access the first element
const_reference front () const
access the first element
reference back ()
access the last element
const_reference back () const
access the last element
template<class IteratorType , typename std::enable_if< std::is_same< IteratorType, typename basic_json_t::iterator >::value orstd::is_same< IteratorType, typename basic_json_t::const_iterator >::value, int >::type = 0>
IteratorType erase (IteratorType pos)
remove element given an iterator
template<class IteratorType , typename std::enable_if< std::is_same< IteratorType, typename basic_json_t::iterator >::value orstd::is_same< IteratorType, typename basic_json_t::const_iterator >::value, int >::type = 0>
IteratorType erase (IteratorType first, IteratorType last)
remove elements given an iterator range
size_type erase (const typename object_t::key_type &key)
remove element from a JSON object given a key
void erase (const size_type idx)
remove element from a JSON array given an index
lookup
iterator find (typename object_t::key_type key)
find an element in a JSON object
const_iterator find (typename object_t::key_type key) const
find an element in a JSON object
size_type count (typename object_t::key_type key) const
returns the number of occurrences of a key in a JSON object
iterators
static iteration_proxy< iterator > iterator_wrapper (reference cont)
wrapper to access iterator member functions in range-based for
static iteration_proxy< const_iterator > iterator_wrapper (const_reference cont)
wrapper to access iterator member functions in range-based for
iterator begin () noexcept
returns an iterator to the first element
const_iterator begin () const noexcept
returns a const iterator to the first element
const_iterator cbegin () const noexcept
returns a const iterator to the first element
iterator end () noexcept
returns an iterator to one past the last element
const_iterator end () const noexcept
returns a const iterator to one past the last element
const_iterator cend () const noexcept
returns a const iterator to one past the last element
reverse_iterator rbegin () noexcept
returns an iterator to the reverse-beginning
const_reverse_iterator rbegin () const noexcept
returns a const reverse iterator to the last element
reverse_iterator rend () noexcept
returns an iterator to the reverse-end
const_reverse_iterator rend () const noexcept
returns a const reverse iterator to one before the first
const_reverse_iterator crbegin () const noexcept
returns a const reverse iterator to the last element
const_reverse_iterator crend () const noexcept
returns a const reverse iterator to one before the first
capacity
bool empty () const noexcept
checks whether the container is empty
size_type size () const noexcept
returns the number of elements
size_type max_size () const noexcept
returns the maximum possible number of elements
modifiers
void clear () noexcept
clears the contents
void push_back (basic_json &&val)
add an object to an array
reference operator+= (basic_json &&val)
add an object to an array
void push_back (const basic_json &val)
add an object to an array
reference operator+= (const basic_json &val)
add an object to an array
void push_back (const typename object_t::value_type &val)
add an object to an object
reference operator+= (const typename object_t::value_type &val)
add an object to an object
void push_back (std::initializer_list< basic_json > init)
add an object to an object
reference operator+= (std::initializer_list< basic_json > init)
add an object to an object
template<class... Args>
void emplace_back (Args &&...args)
add an object to an array
template<class... Args>
std::pair< iterator, bool > emplace (Args &&...args)
add an object to an object if key does not exist
iterator insert (const_iterator pos, const basic_json &val)
inserts element
iterator insert (const_iterator pos, basic_json &&val)
inserts element
iterator insert (const_iterator pos, size_type cnt, const basic_json &val)
inserts elements
iterator insert (const_iterator pos, const_iterator first, const_iterator last)
inserts elements
iterator insert (const_iterator pos, std::initializer_list< basic_json > ilist)
inserts elements
void swap (reference other) noexcept(std::is_nothrow_move_constructible< value_t >::value andstd::is_nothrow_move_assignable< value_t >::value andstd::is_nothrow_move_constructible< json_value >::value andstd::is_nothrow_move_assignable< json_value >::value)
exchanges the values
void swap (array_t &other)
exchanges the values
void swap (object_t &other)
exchanges the values
void swap (string_t &other)
exchanges the values
lexicographical comparison operators
bool operator== (const_reference lhs, const_reference rhs) noexcept
comparison: equal
bool operator== (const_reference v, std::nullptr_t) noexcept
comparison: equal
bool operator== (std::nullptr_t, const_reference v) noexcept
comparison: equal
bool operator!= (const_reference lhs, const_reference rhs) noexcept
comparison: not equal
bool operator!= (const_reference v, std::nullptr_t) noexcept
comparison: not equal
bool operator!= (std::nullptr_t, const_reference v) noexcept
comparison: not equal
bool operator< (const_reference lhs, const_reference rhs) noexcept
comparison: less than
bool operator<= (const_reference lhs, const_reference rhs) noexcept
comparison: less than or equal
bool operator> (const_reference lhs, const_reference rhs) noexcept
comparison: greater than
bool operator>= (const_reference lhs, const_reference rhs) noexcept
comparison: greater than or equal
serialization
std::ostream & operator<< (std::ostream &o, const basic_json &j)
serialize to stream
std::ostream & operator>> (const basic_json &j, std::ostream &o)
serialize to stream
deserialization
std::istream & operator<< (basic_json &j, std::istream &i)
deserialize from stream
std::istream & operator>> (std::istream &i, basic_json &j)
deserialize from stream
template<class T , std::size_t N>
static basic_json parse (T(&array)[N], const parser_callback_t cb=nullptr)
deserialize from an array
template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0>
static basic_json parse (const CharT s, const parser_callback_t cb=nullptr)
deserialize from string literal
static basic_json parse (std::istream &i, const parser_callback_t cb=nullptr)
deserialize from stream
static basic_json parse (std::istream &&i, const parser_callback_t cb=nullptr)
deserialize from stream
template<class IteratorType , typename std::enable_if< std::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< IteratorType >::iterator_category >::value, int >::type = 0>
static basic_json parse (IteratorType first, IteratorType last, const parser_callback_t cb=nullptr)
deserialize from an iterator range with contiguous storage
template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value andstd::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value, int >::type = 0>
static basic_json parse (const ContiguousContainer &c, const parser_callback_t cb=nullptr)
deserialize from a container with contiguous storage
binary serialization/deserialization support
static std::vector< uint8_t > to_msgpack (const basic_json &j)
create a MessagePack serialization of a given JSON value
static basic_json from_msgpack (const std::vector< uint8_t > &v)
create a JSON value from a byte vector in MessagePack format
static std::vector< uint8_t > to_cbor (const basic_json &j)
create a MessagePack serialization of a given JSON value
static basic_json from_cbor (const std::vector< uint8_t > &v)
create a JSON value from a byte vector in CBOR format
template<typename T >
static void add_to_vector (std::vector< uint8_t > &vec, size_t bytes, const T number)
template<typename T >
static T get_from_vector (const std::vector< uint8_t > &vec, const size_t current_index)
take sufficient bytes from a vector to fill an integer variable
static void to_msgpack_internal (const basic_json &j, std::vector< uint8_t > &v)
create a MessagePack serialization of a given JSON value
static void to_cbor_internal (const basic_json &j, std::vector< uint8_t > &v)
create a CBOR serialization of a given JSON value
static void check_length (const size_t size, const size_t len, const size_t offset)
static basic_json from_msgpack_internal (const std::vector< uint8_t > &v, size_t &idx)
create a JSON value from a given MessagePack vector
static basic_json from_cbor_internal (const std::vector< uint8_t > &v, size_t &idx)
create a JSON value from a given CBOR vector
JSON Pointer functions
reference operator[] (const json_pointer &ptr)
access specified element via JSON Pointer
const_reference operator[] (const json_pointer &ptr) const
access specified element via JSON Pointer
reference at (const json_pointer &ptr)
access specified element via JSON Pointer
const_reference at (const json_pointer &ptr) const
access specified element via JSON Pointer
basic_json flatten () const
return flattened JSON value
basic_json unflatten () const
unflatten a previously flattened JSON value
JSON Patch functions
static basic_json diff (const basic_json &source, const basic_json &target, const std::string &path="")
creates a diff as a JSON patch
basic_json patch (const basic_json &json_patch) const
applies a JSON patch
Detailed Description
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer>
class nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >
a class to store JSON values
Template Parameters
ObjectType type for JSON objects (std::map by default; will be used in object_t)
ArrayType type for JSON arrays (std::vector by default; will be used in array_t)
StringType type for JSON strings and object keys (std::string by default; will be used in string_t)
BooleanType type for JSON booleans (bool by default; will be used in boolean_t)
NumberIntegerType type for JSON integer numbers (int64_t by default; will be used in number_integer_t)
NumberUnsignedType type for JSON unsigned integer numbers (uint64_t by default; will be used in number_unsigned_t)
NumberFloatType type for JSON floating-point numbers (double by default; will be used in number_float_t)
AllocatorType type of the allocator to use (std::allocator by default)
JSONSerializer the serializer to resolve internal calls to to_json() and from_json() (adl_serializer by default)
The class satisfies the following concept requirements:
Basic
DefaultConstructible: JSON values can be default constructed. The result will be a JSON null value.
MoveConstructible: A JSON value can be constructed from an rvalue argument.
CopyConstructible: A JSON value can be copy-constructed from an lvalue expression.
MoveAssignable: A JSON value van be assigned from an rvalue argument.
CopyAssignable: A JSON value can be copy-assigned from an lvalue expression.
Destructible: JSON values can be destructed.
Layout
StandardLayoutType: JSON values have standard layout: All non-static data members are private and standard layout types, the class has no virtual functions or (virtual) base classes.
Library-wide
EqualityComparable: JSON values can be compared with ==, see operator==(const_reference,const_reference).
LessThanComparable: JSON values can be compared with <, see operator<(const_reference,const_reference).
Swappable: Any JSON lvalue or rvalue of can be swapped with any lvalue or rvalue of other compatible types, using unqualified function call swap().
NullablePointer: JSON values can be compared against std::nullptr_t objects which are used to model the null value.
Container
Container: JSON values can be used like STL containers and provide iterator access.
ReversibleContainer; JSON values can be used like STL containers and provide reverse iterator access.
Invariant
The member variables m_value and m_type have the following relationship:
If m_type == value_t::object, then m_value.object != nullptr.
If m_type == value_t::array, then m_value.array != nullptr.
If m_type == value_t::string, then m_value.string != nullptr. The invariants are checked by member function assert_invariant().
See also
RFC 7159: The JavaScript Object Notation (JSON) Data Interchange Format
Since
version 1.0.0
Definition at line 1038 of file json.hpp.
Member Typedef Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::allocator_type = AllocatorType<basic_json>
the allocator type
Definition at line 1079 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::array_t = ArrayType<basic_json, AllocatorType<basic_json>>
a type for an array
RFC 7159 describes JSON arrays as follows:
An array is an ordered sequence of zero or more values.
To store objects in C++, a type is defined by the template parameters explained below.
Template Parameters
ArrayType container type to store arrays (e.g., std::vector or std::list)
AllocatorType allocator to use for arrays (e.g., std::allocator)
Default type
With the default values for ArrayType (std::vector) and AllocatorType (std::allocator), the default value for array_t is:
std::vector<
  basic_json, // value_type
  std::allocator<basic_json> // allocator_type
>
Limits
RFC 7159 specifies:
An implementation may set limits on the maximum depth of nesting.
In this class, the array's limit of nesting is not constraint explicitly. However, a maximum depth of nesting may be introduced by the compiler or runtime environment. A theoretical limit can be queried by calling the max_size function of a JSON array.
Storage
Arrays are stored as pointers in a basic_json type. That is, for any access to array values, a pointer of type array_t* must be dereferenced.
See also
object_t – type for an object value
Since
version 1.0.0
Definition at line 1327 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json_t = basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer> private
workaround type for MSVC
Definition at line 1045 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::boolean_t = BooleanType
a type for a boolean
RFC 7159 implicitly describes a boolean as a type which differentiates the two literals true and false.
To store objects in C++, a type is defined by the template parameter BooleanType which chooses the type to use.
Default type
With the default values for BooleanType (bool), the default value for boolean_t is:
bool
Storage
Boolean values are stored directly inside a basic_json type.
Since
version 1.0.0
Definition at line 1406 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::const_iterator = iter_impl<const basic_json>
a const iterator for a basic_json container
Definition at line 1089 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::const_pointer = typename std::allocator_traits<allocator_type>::const_pointer
the type of an element const pointer
Definition at line 1084 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::const_reference = const value_type&
the type of an element const reference
Definition at line 1071 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::const_reverse_iterator = json_reverse_iterator<typename basic_json::const_iterator>
a const reverse iterator for a basic_json container
Definition at line 1093 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::difference_type = std::ptrdiff_t
a type to represent differences between iterators
Definition at line 1074 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iterator = iter_impl<basic_json>
an iterator for a basic_json container
Definition at line 1087 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T , typename SFINAE > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_serializer = JSONSerializer<T, SFINAE>
Definition at line 1054 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::number_float_t = NumberFloatType
a type for a number (floating-point)
RFC 7159 describes numbers as follows:
The representation of numbers is similar to that used in most programming languages. A number is represented in base 10 using decimal digits. It contains an integer component that may be prefixed with an optional minus sign, which may be followed by a fraction part and/or an exponent part. Leading zeros are not allowed. (...) Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.
This description includes both integer and floating-point numbers. However, C++ allows more precise storage if it is known whether the number is a signed integer, an unsigned integer or a floating-point number. Therefore, three different types, number_integer_t, number_unsigned_t and number_float_t are used.
To store floating-point numbers in C++, a type is defined by the template parameter NumberFloatType which chooses the type to use.
Default type
With the default values for NumberFloatType (double), the default value for number_float_t is:
double
Default behavior
The restrictions about leading zeros is not enforced in C++. Instead, leading zeros in floating-point literals will be ignored. Internally, the value will be stored as decimal number. For instance, the C++ floating-point literal 01.2 will be serialized to 1.2. During deserialization, leading zeros yield an error.
Not-a-number (NaN) values will be serialized to null.
Limits
RFC 7159 states:
This specification allows implementations to set limits on the range and precision of numbers accepted. Since software that implements IEEE 754-2008 binary64 (double precision) numbers is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision.
This implementation does exactly follow this approach, as it uses double precision floating-point numbers. Note values smaller than -1.79769313486232e+308 and values greater than 1.79769313486232e+308 will be stored as NaN internally and be serialized to null.
Storage
Floating-point number values are stored directly inside a basic_json type.
See also
number_integer_t – type for number values (integer)
number_unsigned_t – type for number values (unsigned integer)
Since
version 1.0.0
Definition at line 1617 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::number_integer_t = NumberIntegerType
a type for a number (integer)
RFC 7159 describes numbers as follows:
The representation of numbers is similar to that used in most programming languages. A number is represented in base 10 using decimal digits. It contains an integer component that may be prefixed with an optional minus sign, which may be followed by a fraction part and/or an exponent part. Leading zeros are not allowed. (...) Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.
This description includes both integer and floating-point numbers. However, C++ allows more precise storage if it is known whether the number is a signed integer, an unsigned integer or a floating-point number. Therefore, three different types, number_integer_t, number_unsigned_t and number_float_t are used.
To store integer numbers in C++, a type is defined by the template parameter NumberIntegerType which chooses the type to use.
Default type
With the default values for NumberIntegerType (int64_t), the default value for number_integer_t is:
int64_t
Default behavior
The restrictions about leading zeros is not enforced in C++. Instead, leading zeros in integer literals lead to an interpretation as octal number. Internally, the value will be stored as decimal number. For instance, the C++ integer literal 010 will be serialized to 8. During deserialization, leading zeros yield an error.
Not-a-number (NaN) values will be serialized to null.
Limits
RFC 7159 specifies:
An implementation may set limits on the range and precision of numbers.
When the default type is used, the maximal integer number that can be stored is 9223372036854775807 (INT64_MAX) and the minimal integer number that can be stored is -9223372036854775808 (INT64_MIN). Integer numbers that are out of range will yield over/underflow when used in a constructor. During deserialization, too large or small integer numbers will be automatically be stored as number_unsigned_t or number_float_t.
RFC 7159 further states:
Note that when such software is used, numbers that are integers and are in the range are interoperable in the sense that implementations will agree exactly on their numeric values.
As this range is a subrange of the exactly supported range [INT64_MIN, INT64_MAX], this class's integer type is interoperable.
Storage
Integer number values are stored directly inside a basic_json type.
See also
number_float_t – type for number values (floating-point)
number_unsigned_t – type for number values (unsigned integer)
Since
version 1.0.0
Definition at line 1478 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::number_unsigned_t = NumberUnsignedType
a type for a number (unsigned)
RFC 7159 describes numbers as follows:
The representation of numbers is similar to that used in most programming languages. A number is represented in base 10 using decimal digits. It contains an integer component that may be prefixed with an optional minus sign, which may be followed by a fraction part and/or an exponent part. Leading zeros are not allowed. (...) Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.
This description includes both integer and floating-point numbers. However, C++ allows more precise storage if it is known whether the number is a signed integer, an unsigned integer or a floating-point number. Therefore, three different types, number_integer_t, number_unsigned_t and number_float_t are used.
To store unsigned integer numbers in C++, a type is defined by the template parameter NumberUnsignedType which chooses the type to use.
Default type
With the default values for NumberUnsignedType (uint64_t), the default value for number_unsigned_t is:
uint64_t
Default behavior
The restrictions about leading zeros is not enforced in C++. Instead, leading zeros in integer literals lead to an interpretation as octal number. Internally, the value will be stored as decimal number. For instance, the C++ integer literal 010 will be serialized to 8. During deserialization, leading zeros yield an error.
Not-a-number (NaN) values will be serialized to null.
Limits
RFC 7159 specifies:
An implementation may set limits on the range and precision of numbers.
When the default type is used, the maximal integer number that can be stored is 18446744073709551615 (UINT64_MAX) and the minimal integer number that can be stored is 0. Integer numbers that are out of range will yield over/underflow when used in a constructor. During deserialization, too large or small integer numbers will be automatically be stored as number_integer_t or number_float_t.
RFC 7159 further states:
Note that when such software is used, numbers that are integers and are in the range are interoperable in the sense that implementations will agree exactly on their numeric values.
As this range is a subrange (when considered in conjunction with the number_integer_t type) of the exactly supported range [0, UINT64_MAX], this class's integer type is interoperable.
Storage
Integer number values are stored directly inside a basic_json type.
See also
number_float_t – type for number values (floating-point)
number_integer_t – type for number values (integer)
Since
version 2.0.0
Definition at line 1549 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object_t = ObjectType<StringType, basic_json, std::less<StringType>, AllocatorType<std::pair<const StringType, basic_json>>>
a type for an object
RFC 7159 describes JSON objects as follows:
An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.
To store objects in C++, a type is defined by the template parameters described below.
Template Parameters
ObjectType the container to store objects (e.g., std::map or std::unordered_map)
StringType the type of the keys or names (e.g., std::string). The comparison function std::less<StringType> is used to order elements inside the container.
AllocatorType the allocator to use for objects (e.g., std::allocator)
Default type
With the default values for ObjectType (std::map), StringType (std::string), and AllocatorType (std::allocator), the default value for object_t is:
std::map<
  std::string, // key_type
  basic_json, // value_type
  std::less<std::string>, // key_compare
  std::allocator<std::pair<const std::string, basic_json>> // allocator_type
>
Behavior
The choice of object_t influences the behavior of the JSON class. With the default type, objects have the following behavior:
When all names are unique, objects will be interoperable in the sense that all software implementations receiving that object will agree on the name-value mappings.
When the names within an object are not unique, later stored name/value pairs overwrite previously stored name/value pairs, leaving the used names unique. For instance, {"key": 1} and {"key": 2, "key": 1} will be treated as equal and both stored as {"key": 1}.
Internally, name/value pairs are stored in lexicographical order of the names. Objects will also be serialized (see dump) in this order. For instance, {"b": 1, "a": 2} and {"a": 2, "b": 1} will be stored and serialized as {"a": 2, "b": 1}.
When comparing objects, the order of the name/value pairs is irrelevant. This makes objects interoperable in the sense that they will not be affected by these differences. For instance, {"b": 1, "a": 2} and {"a": 2, "b": 1} will be treated as equal.
Limits
RFC 7159 specifies:
An implementation may set limits on the maximum depth of nesting.
In this class, the object's limit of nesting is not constraint explicitly. However, a maximum depth of nesting may be introduced by the compiler or runtime environment. A theoretical limit can be queried by calling the max_size function of a JSON object.
Storage
Objects are stored as pointers in a basic_json type. That is, for any access to object values, a pointer of type object_t* must be dereferenced.
See also
array_t – type for an array value
Since
version 1.0.0
Note
The order name/value pairs are added to the object is not preserved by the library. Therefore, iterating an object may return name/value pairs in a different order than they were originally stored. In fact, keys will be traversed in alphabetical order as std::map with std::less is used by default. Please note this behavior conforms to RFC 7159, because any order implements the specified "unordered" nature of JSON objects.
Definition at line 1281 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser_callback_t = std::function<bool(int depth, parse_event_t event, basic_json& parsed)>
per-element parser callback type
With a parser callback function, the result of parsing a JSON text can be influenced. When passed to parse(std::istream&, const parser_callback_t) or parse(const CharT, const parser_callback_t), it is called on certain events (passed as parse_event_t via parameter event) with a set recursion depth depth and context JSON value parsed. The return value of the callback function is a boolean indicating whether the element that emitted the callback shall be kept or not.
We distinguish six scenarios (determined by the event type) in which the callback function can be called. The following table describes the values of the parameters depth, event, and parsed.
parameter event description parameter depth parameter parsed
parse_event_t::object_start the parser read { and started to process a JSON object depth of the parent of the JSON object a JSON value with type discarded
parse_event_t::key the parser read a key of a value in an object depth of the currently parsed JSON object a JSON string containing the key
parse_event_t::object_end the parser read } and finished processing a JSON object depth of the parent of the JSON object the parsed JSON object
parse_event_t::array_start the parser read [ and started to process a JSON array depth of the parent of the JSON array a JSON value with type discarded
parse_event_t::array_end the parser read ] and finished processing a JSON array depth of the parent of the JSON array the parsed JSON array
parse_event_t::value the parser finished reading a JSON value depth of the value the parsed JSON value
Example when certain parse events are triggered
Discarding a value (i.e., returning false) has different effects depending on the context in which function was called:
Discarded values in structured types are skipped. That is, the parser will behave as if the discarded value was never read.
In case a value outside a structured type is skipped, it is replaced with null. This case happens if the top-level element is skipped.
Parameters
[in] depth the depth of the recursion during parsing
[in] event an event of type parse_event_t indicating the context in the callback function has been called
[in,out] parsed the current intermediate parse result; note that writing to this value has no effect for parse_event_t::key events
Returns
Whether the JSON value which called the function during parsing should be kept (true) or not (false). In the latter case, it is either skipped completely or replaced by an empty discarded object.
See also
parse(std::istream&, parser_callback_t) or parse(const CharT, const parser_callback_t) for examples
Since
version 1.0.0
Definition at line 1876 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::pointer = typename std::allocator_traits<allocator_type>::pointer
the type of an element pointer
Definition at line 1082 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::reference = value_type&
the type of an element reference
Definition at line 1069 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::reverse_iterator = json_reverse_iterator<typename basic_json::iterator>
a reverse iterator for a basic_json container
Definition at line 1091 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::size_type = std::size_t
a type to represent container sizes
Definition at line 1076 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::string_t = StringType
a type for a string
RFC 7159 describes JSON strings as follows:
A string is a sequence of zero or more Unicode characters.
To store objects in C++, a type is defined by the template parameter described below. Unicode values are split by the JSON class into byte-sized characters during deserialization.
Template Parameters
StringType the container to store strings (e.g., std::string). Note this container is used for keys/names in objects, see object_t.
Default type
With the default values for StringType (std::string), the default value for string_t is:
std::string
Encoding
Strings are stored in UTF-8 encoding. Therefore, functions like std::string::size() or std::string::length() return the number of bytes in the string rather than the number of characters or glyphs.
String comparison
RFC 7159 states:
Software implementations are typically required to test names of object members for equality. Implementations that transform the textual representation into sequences of Unicode code units and then perform the comparison numerically, code unit by code unit, are interoperable in the sense that implementations will agree in all cases on equality or inequality of two strings. For example, implementations that compare strings with escaped characters unconverted may incorrectly find that "a\\\\b" and "a\\u005Cb" are not equal.
This implementation is interoperable as it does compare strings code unit by code unit.
Storage
String values are stored as pointers in a basic_json type. That is, for any access to string values, a pointer of type string_t* must be dereferenced.
Since
version 1.0.0
Definition at line 1380 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value_t = detail::value_t
Definition at line 1048 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value_type = basic_json
the type of elements in a basic_json container
Definition at line 1066 of file json.hpp.
Member Enumeration Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> enum nlohmann::basic_json::parse_event_t : uint8_t strong
JSON callback events.
This enumeration lists the parser events that can trigger calling a callback function of type parser_callback_t during parsing.
Example when certain parse events are triggered
Since
version 1.0.0
Enumerator
object_start
the parser read { and started to process a JSON object
object_end
the parser read } and finished processing a JSON object
array_start
the parser read [ and started to process a JSON array
array_end
the parser read ] and finished processing a JSON array
key
the parser read a key of a value in an object
value
the parser finished reading a JSON value
Definition at line 1806 of file json.hpp.
                              : uint8_t
     {
         object_start,
         object_end,
         array_start,
         array_end,
         key,
         value
     };
Constructor & Destructor Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (const value_t value_type) inline
create an empty value with a given type
Create an empty JSON value with a given type. The value will be default initialized with an empty value which depends on the type:
Value type initial value
null null
boolean false
string ""
number 0
object {}
array []
Parameters
[in] value_type the type of the value to create
Constant.
Exceptions
std::bad_alloc if allocation for object, array, or string value fails
{The following code shows the constructor for different value_t values,basic_json__value_t}
Since
version 1.0.0
Definition at line 1915 of file json.hpp.
         : m_type(value_type), m_value(value_type)
     {
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (std::nullptr_t = nullptr) inline noexcept
create a null object
Create a null JSON value. It either takes a null pointer as parameter (explicitly creating null) or no parameter (implicitly creating null). The passed null pointer itself is not read – it is only used to choose the right constructor.
Constant.
No-throw guarantee: this constructor never throws exceptions.
{The following code shows the constructor with and without a null pointer parameter.,basic_json__nullptr_t}
Since
version 1.0.0
Definition at line 1939 of file json.hpp.
         : basic_json(value_t::null)
     {
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename CompatibleType , typename U = detail::uncvref_t<CompatibleType>, detail::enable_if_t< not std::is_base_of< std::istream, U >::value andnot std::is_same< U, basic_json_t >::value andnot detail::is_basic_json_nested_type< basic_json_t, U >::value anddetail::has_to_json< basic_json, U >::value, int > = 0> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (CompatibleType && val) inline noexcept
create a JSON value
This is a "catch all" constructor for all compatible JSON types; that is, types for which a to_json() method exsits. The constructor forwards the parameter val to that method (to json_serializer<U>::to_json method with U = uncvref_t<CompatibleType>, to be exact).
Template type CompatibleType includes, but is not limited to, the following types:
arrays: array_t and all kinds of compatible containers such as std::vector, std::deque, std::list, std::forward_list, std::array, std::set, std::unordered_set, std::multiset, and unordered_multiset with a value_type from which a basic_json value can be constructed.
objects: object_t and all kinds of compatible associative containers such as std::map, std::unordered_map, std::multimap, and std::unordered_multimap with a key_type compatible to string_t and a value_type from which a basic_json value can be constructed.
strings: string_t, string literals, and all compatible string containers can be used.
numbers: number_integer_t, number_unsigned_t, number_float_t, and all convertible number types such as int, size_t, int64_t, float or double can be used.
boolean: boolean_t / bool can be used.
See the examples below.
Template Parameters
CompatibleType a type such that:
CompatibleType is not derived from std::istream,
CompatibleType is not basic_json (to avoid hijacking copy/move constructors),
CompatibleType is not a basic_json nested type (e.g., json_pointer, iterator, etc ...)
json_serializer<U> has a to_json(basic_json_t&, CompatibleType&&) method
U = uncvref_t<CompatibleType>
Parameters
[in] val the value to be forwarded
Usually linear in the size of the passed val, also depending on the implementation of the called to_json() method.
Exceptions
what json_serializer<U>to_json() throws
{The following code shows the constructor with several compatible types.,basic_json__CompatibleType}
Since
version 2.1.0
Definition at line 2005 of file json.hpp.
References nlohmann::detail::to_json().
     {
         JSONSerializer<U>::to_json(*this, std::forward<CompatibleType>(val));
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > init, bool type_deduction = true, value_t manual_type = value_t::array) inline
create a container (array or object) from an initializer list
Creates a JSON value of type array or object from the passed initializer list init. In case type_deduction is true (default), the type of the JSON value to be created is deducted from the initializer list init according to the following rules:
If the list is empty, an empty JSON object value {} is created.
If the list consists of pairs whose first element is a string, a JSON object value is created where the first elements of the pairs are treated as keys and the second elements are as values.
In all other cases, an array is created.
The rules aim to create the best fit between a C++ initializer list and JSON values. The rationale is as follows:
The empty initializer list is written as {} which is exactly an empty JSON object.
C++ has now way of describing mapped types other than to list a list of pairs. As JSON requires that keys must be of type string, rule 2 is the weakest constraint one can pose on initializer lists to interpret them as an object.
In all other cases, the initializer list could not be interpreted as JSON object type, so interpreting it as JSON array type is safe.
With the rules described above, the following JSON values cannot be expressed by an initializer list:
the empty array ([]): use array(std::initializer_list<basic_json>) with an empty initializer list in this case
arrays whose elements satisfy rule 2: use array(std::initializer_list<basic_json>) with the same initializer list in this case
Note
When used without parentheses around an empty initializer list, basic_json() is called instead of this function, yielding the JSON null value.
Parameters
[in] init initializer list with JSON values
[in] type_deduction internal parameter; when set to true, the type of the JSON value is deducted from the initializer list init; when set to false, the type provided via manual_type is forced. This mode is used by the functions array(std::initializer_list<basic_json>) and object(std::initializer_list<basic_json>).
[in] manual_type internal parameter; when type_deduction is set to false, the created JSON value will use the provided type (only value_t::array and value_t::object are valid); when type_deduction is set to true, this parameter has no effect
Exceptions
std::domain_error if type_deduction is false, manual_type is value_t::object, but init contains an element which is not a pair whose first element is a string; example: "cannot create object from initializer list"
Linear in the size of the initializer list init.
{The example below shows how JSON values are created from initializer lists.,basic_json__list_init_t}
See also
array(std::initializer_list<basic_json>) – create a JSON array value from an initializer list
object(std::initializer_list<basic_json>) – create a JSON object value from an initializer list
Since
version 1.0.0
Definition at line 2081 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
     {
         // check if each element is an array with two elements whose first
         // element is a string
         bool is_an_object = std::all_of(init.begin(), init.end(),
                                         [](const basic_json & element)
         {
             return element.is_array() and element.size() == 2 and element[0].is_string();
         });
         // adjust type if type deduction is not wanted
         if (not type_deduction)
         {
             // if array is wanted, do not create an object though possible
             if (manual_type == value_t::array)
             {
                 is_an_object = false;
             }
             // if object is wanted but impossible, throw an exception
             if (manual_type == value_t::object and not is_an_object)
             {
                 JSON_THROW(std::domain_error("cannot create object from initializer list"));
             }
         }
         if (is_an_object)
         {
             // the initializer list is a list of pairs -> create object
             m_type = value_t::object;
             m_value = value_t::object;
             std::for_each(init.begin(), init.end(), [this](const basic_json & element)
             {
                 m_value.object->emplace(*(element[0].m_value.string), element[1]);
             });
         }
         else
         {
             // the initializer list describes an array -> create array
             m_type = value_t::array;
             m_value.array = create<array_t>(init);
         }
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (size_type cnt, const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & val) inline
construct an array with count copies of given value
Constructs a JSON array value by creating cnt copies of a passed value. In case cnt is 0, an empty array is created. As postcondition, std::distance(begin(),end()) == cnt holds.
Parameters
[in] cnt the number of JSON copies of val to create
[in] val the JSON value to copy
Linear in cnt.
{The following code shows examples for the basic_json(size_type\, const basic_json&) constructor.,basic_json__size_type_basic_json}
Since
version 1.0.0
Definition at line 2228 of file json.hpp.
         : m_type(value_t::array)
     {
         m_value.array = create<array_t>(cnt, val);
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class InputIT , typename std::enable_if< std::is_same< InputIT, typename basic_json_t::iterator >::value orstd::is_same< InputIT, typename basic_json_t::const_iterator >::value, int >::type = 0> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (InputIT first, InputIT last) inline
construct a JSON container given an iterator range
Constructs the JSON value with the contents of the range [first, last). The semantics depends on the different types a JSON value can have:
In case of primitive types (number, boolean, or string), first must be begin() and last must be end(). In this case, the value is copied. Otherwise, std::out_of_range is thrown.
In case of structured types (array, object), the constructor behaves as similar versions for std::vector.
In case of a null type, std::domain_error is thrown.
Template Parameters
InputIT an input iterator type (iterator or const_iterator)
Parameters
[in] first begin of the range to copy from (included)
[in] last end of the range to copy from (excluded)
Precondition
Iterators first and last must be initialized. This precondition is enforced with an assertion.
Exceptions
std::domain_error if iterators are not compatible; that is, do not belong to the same JSON value; example: "iterators are not compatible"
std::out_of_range if iterators are for a primitive type (number, boolean, or string) where an out of range error can be detected easily; example: "iterators out of range"
std::bad_alloc if allocation for object, array, or string fails
std::domain_error if called with a null value; example: "cannot use construct with iterators from null"
Linear in distance between first and last.
{The example below shows several ways to create JSON values by specifying a subrange with iterators.,basic_json__InputIt_InputIt}
Since
version 1.0.0
Definition at line 2275 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, JSON_DEPRECATED, JSON_THROW, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
     {
         assert(first.m_object != nullptr);
         assert(last.m_object != nullptr);
         // make sure iterator fits the current value
         if (first.m_object != last.m_object)
         {
             JSON_THROW(std::domain_error("iterators are not compatible"));
         }
         // copy type from first iterator
         m_type = first.m_object->m_type;
         // check if iterator range is complete for primitive values
         switch (m_type)
         {
             case value_t::boolean:
             case value_t::number_float:
             case value_t::number_integer:
             case value_t::number_unsigned:
             case value_t::string:
             {
                 if (not first.m_it.primitive_iterator.is_begin() or not last.m_it.primitive_iterator.is_end())
                 {
                     JSON_THROW(std::out_of_range("iterators out of range"));
                 }
                 break;
             }
             default:
             {
                 break;
             }
         }
         switch (m_type)
         {
             case value_t::number_integer:
             {
                 m_value.number_integer = first.m_object->m_value.number_integer;
                 break;
             }
             case value_t::number_unsigned:
             {
                 m_value.number_unsigned = first.m_object->m_value.number_unsigned;
                 break;
             }
             case value_t::number_float:
             {
                 m_value.number_float = first.m_object->m_value.number_float;
                 break;
             }
             case value_t::boolean:
             {
                 m_value.boolean = first.m_object->m_value.boolean;
                 break;
             }
             case value_t::string:
             {
                 m_value = *first.m_object->m_value.string;
                 break;
             }
             case value_t::object:
             {
                 m_value.object = create<object_t>(first.m_it.object_iterator,
                                                   last.m_it.object_iterator);
                 break;
             }
             case value_t::array:
             {
                 m_value.array = create<array_t>(first.m_it.array_iterator,
                                                 last.m_it.array_iterator);
                 break;
             }
             default:
             {
                 JSON_THROW(std::domain_error("cannot use construct with iterators from " + first.m_object->type_name()));
             }
         }
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (std::istream & i, const parser_callback_t cb = nullptr) inline explicit
construct a JSON value given an input stream
Parameters
[in,out] i stream to read a serialized JSON value from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
Deprecated:
This constructor is deprecated and will be removed in version 3.0.0 to unify the interface of the library. Deserialization will be done by stream operators or by calling one of the parse functions, e.g. parse(std::istream&, const parser_callback_t). That is, calls like json j(i); for an input stream i need to be replaced by json j = json::parse(i);. See the example below.
{The example below demonstrates constructing a JSON value from a std::stringstream with and without callback function.,basic_json__istream}
Since
version 2.0.0, deprecated in version 2.0.3, to be removed in version 3.0.0
Definition at line 2395 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         *this = parser(i, cb).parse();
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & other) inline
copy constructor
Creates a copy of a given JSON value.
Parameters
[in] other the JSON value to copy
Linear in the size of other.
This function helps basic_json satisfying the Container requirements:
The complexity is linear.
As postcondition, it holds: other == basic_json(other).
Exceptions
std::bad_alloc if allocation for object, array, or string fails.
{The following code shows an example for the copy constructor.,basic_json__basic_json}
Since
version 1.0.0
Definition at line 2427 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::assert_invariant(), nlohmann::detail::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, nlohmann::detail::number_float, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_float, nlohmann::detail::number_integer, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_integer, nlohmann::detail::number_unsigned, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_unsigned, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object, nlohmann::detail::string, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::string.
         : m_type(other.m_type)
     {
         // check of passed value is valid
         other.assert_invariant();
         switch (m_type)
         {
             case value_t::object:
             {
                 m_value = *other.m_value.object;
                 break;
             }
             case value_t::array:
             {
                 m_value = *other.m_value.array;
                 break;
             }
             case value_t::string:
             {
                 m_value = *other.m_value.string;
                 break;
             }
             case value_t::boolean:
             {
                 m_value = other.m_value.boolean;
                 break;
             }
             case value_t::number_integer:
             {
                 m_value = other.m_value.number_integer;
                 break;
             }
             case value_t::number_unsigned:
             {
                 m_value = other.m_value.number_unsigned;
                 break;
             }
             case value_t::number_float:
             {
                 m_value = other.m_value.number_float;
                 break;
             }
             default:
             {
                 break;
             }
         }
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json (basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > && other) inline noexcept
move constructor
Move constructor. Constructs a JSON value with the contents of the given value other using move semantics. It "steals" the resources from other and leaves it as JSON null value.
Parameters
[in,out] other value to move to this object
Postcondition
other is a JSON null value
Constant.
{The code below shows the move constructor explicitly called via std::move.,basic_json__moveconstructor}
Since
version 1.0.0
Definition at line 2504 of file json.hpp.
References nlohmann::detail::null.
         : m_type(std::move(other.m_type)),
           m_value(std::move(other.m_value))
     {
         // check that passed value is valid
         other.assert_invariant();
         // invalidate payload
         other.m_type = value_t::null;
         other.m_value = {};
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::~basic_json () inline
destructor
Destroys the JSON value and frees all allocated memory.
Linear.
This function helps basic_json satisfying the Container requirements:
The complexity is linear.
All stored elements are destroyed and all memory is freed.
Since
version 1.0.0
Definition at line 2574 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::object, and nlohmann::detail::string.
     {
         assert_invariant();
         switch (m_type)
         {
             case value_t::object:
             {
                 AllocatorType<object_t> alloc;
                 alloc.destroy(m_value.object);
                 alloc.deallocate(m_value.object, 1);
                 break;
             }
             case value_t::array:
             {
                 AllocatorType<array_t> alloc;
                 alloc.destroy(m_value.array);
                 alloc.deallocate(m_value.array, 1);
                 break;
             }
             case value_t::string:
             {
                 AllocatorType<string_t> alloc;
                 alloc.destroy(m_value.string);
                 alloc.deallocate(m_value.string, 1);
                 break;
             }
             default:
             {
                 // all other types need no specific destructor
                 break;
             }
         }
     }
Member Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T > static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::add_to_vector (std::vector< uint8_t > & vec, size_t bytes, const T number) inline static private
Definition at line 6585 of file json.hpp.
     {
         assert(bytes == 1 or bytes == 2 or bytes == 4 or bytes == 8);
         switch (bytes)
         {
             case 8:
             {
                 vec.push_back(static_cast<uint8_t>((number >> 070) & 0xff));
                 vec.push_back(static_cast<uint8_t>((number >> 060) & 0xff));
                 vec.push_back(static_cast<uint8_t>((number >> 050) & 0xff));
                 vec.push_back(static_cast<uint8_t>((number >> 040) & 0xff));
                 // intentional fall-through
             }
             case 4:
             {
                 vec.push_back(static_cast<uint8_t>((number >> 030) & 0xff));
                 vec.push_back(static_cast<uint8_t>((number >> 020) & 0xff));
                 // intentional fall-through
             }
             case 2:
             {
                 vec.push_back(static_cast<uint8_t>((number >> 010) & 0xff));
                 // intentional fall-through
             }
             case 1:
             {
                 vec.push_back(static_cast<uint8_t>(number & 0xff));
                 break;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::array (std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > init = std::initializer_list<basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >>()) inline static
explicitly create an array from an initializer list
Creates a JSON array value from a given initializer list. That is, given a list of values a, b, c, creates the JSON value [a, b, c]. If the initializer list is empty, the empty array [] is created.
Note
This function is only needed to express two edge cases that cannot be realized with the initializer list constructor (basic_json(std::initializer_list<basic_json>, bool, value_t)). These cases are:
creating an array whose elements are all pairs whose first element is a string – in this case, the initializer list constructor would create an object, taking the first elements as keys
creating an empty array – passing the empty initializer list to the initializer list constructor yields an empty object
Parameters
[in] init initializer list with JSON values to create an array from (optional)
Returns
JSON array value
Linear in the size of init.
{The following code shows an example for the array function.,array}
See also
basic_json(std::initializer_list<basic_json>, bool, value_t) – create a JSON value from an initializer list
object(std::initializer_list<basic_json>) – create a JSON object value from an initializer list
Since
version 1.0.0
Definition at line 2164 of file json.hpp.
References nlohmann::detail::array.
Referenced by main(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[]().
     {
         return basic_json(init, false, value_t::array);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::assert_invariant () const inline private
checks the class invariants
This function asserts the class invariants. It needs to be called at the end of every constructor to make sure that created objects respect the invariant. Furthermore, it has to be called each time the type of a JSON value is changed, because the invariant expresses a relationship between m_type and m_value.
Definition at line 1784 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator=(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         assert(m_type != value_t::object or m_value.object != nullptr);
         assert(m_type != value_t::array or m_value.array != nullptr);
         assert(m_type != value_t::string or m_value.string != nullptr);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (size_type idx) inline
access specified array element with bounds checking
Returns a reference to the element at specified location idx, with bounds checking.
Parameters
[in] idx index of the element to access
Returns
reference to the element at index idx
Exceptions
std::domain_error if the JSON value is not an array; example: "cannot use at() with string"
std::out_of_range if the index idx is out of range of the array; that is, idx >= size(); example: "array index 7 is out of range"
Constant.
{The example below shows how array elements can be read and written using at().,at__size_type}
Since
version 1.0.0
Definition at line 3538 of file json.hpp.
References JSON_CATCH, JSON_THROW, and JSON_TRY.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         // at only works for arrays
         if (is_array())
         {
             JSON_TRY
             {
                 return m_value.array->at(idx);
             }
             JSON_CATCH (std::out_of_range&)
             {
                 // create better exception explanation
                 JSON_THROW(std::out_of_range("array index " + std::to_string(idx) + " is out of range"));
             }
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use at() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (size_type idx) const inline
access specified array element with bounds checking
Returns a const reference to the element at specified location idx, with bounds checking.
Parameters
[in] idx index of the element to access
Returns
const reference to the element at index idx
Exceptions
std::domain_error if the JSON value is not an array; example: "cannot use at() with string"
std::out_of_range if the index idx is out of range of the array; that is, idx >= size(); example: "array index 7 is out of range"
Constant.
{The example below shows how array elements can be read using at().,at__size_type_const}
Since
version 1.0.0
Definition at line 3581 of file json.hpp.
References JSON_CATCH, JSON_THROW, and JSON_TRY.
     {
         // at only works for arrays
         if (is_array())
         {
             JSON_TRY
             {
                 return m_value.array->at(idx);
             }
             JSON_CATCH (std::out_of_range&)
             {
                 // create better exception explanation
                 JSON_THROW(std::out_of_range("array index " + std::to_string(idx) + " is out of range"));
             }
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use at() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (const typename object_t::key_type & key) inline
access specified object element with bounds checking
Returns a reference to the element at with specified key key, with bounds checking.
Parameters
[in] key key of the element to access
Returns
reference to the element at key key
Exceptions
std::domain_error if the JSON value is not an object; example: "cannot use at() with boolean"
std::out_of_range if the key key is is not stored in the object; that is, find(key) == end(); example: "key "the fast" not found"
Logarithmic in the size of the container.
{The example below shows how object elements can be read and written using at().,at__object_t_key_type}
See also
operator[](const typename object_t::key_type&) for unchecked access by reference
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3628 of file json.hpp.
References JSON_CATCH, JSON_THROW, and JSON_TRY.
     {
         // at only works for objects
         if (is_object())
         {
             JSON_TRY
             {
                 return m_value.object->at(key);
             }
             JSON_CATCH (std::out_of_range&)
             {
                 // create better exception explanation
                 JSON_THROW(std::out_of_range("key '" + key + "' not found"));
             }
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use at() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (const typename object_t::key_type & key) const inline
access specified object element with bounds checking
Returns a const reference to the element at with specified key key, with bounds checking.
Parameters
[in] key key of the element to access
Returns
const reference to the element at key key
Exceptions
std::domain_error if the JSON value is not an object; example: "cannot use at() with boolean"
std::out_of_range if the key key is is not stored in the object; that is, find(key) == end(); example: "key "the fast" not found"
Logarithmic in the size of the container.
{The example below shows how object elements can be read using at().,at__object_t_key_type_const}
See also
operator[](const typename object_t::key_type&) for unchecked access by reference
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3675 of file json.hpp.
References JSON_CATCH, JSON_THROW, and JSON_TRY.
     {
         // at only works for objects
         if (is_object())
         {
             JSON_TRY
             {
                 return m_value.object->at(key);
             }
             JSON_CATCH (std::out_of_range&)
             {
                 // create better exception explanation
                 JSON_THROW(std::out_of_range("key '" + key + "' not found"));
             }
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use at() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (const json_pointer & ptr) inline
access specified element via JSON Pointer
Returns a reference to the element at with specified JSON pointer ptr, with bounds checking.
Parameters
[in] ptr JSON pointer to the desired element
Returns
reference to the element pointed to by ptr
Constant.
Exceptions
std::out_of_range if the JSON pointer can not be resolved
std::domain_error if an array index begins with '0'
std::invalid_argument if an array index was not a number
{The behavior is shown in the example.,at_json_pointer}
Since
version 2.0.0
Definition at line 12030 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_checked().
     {
         return ptr.get_checked(this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at (const json_pointer & ptr) const inline
access specified element via JSON Pointer
Returns a const reference to the element at with specified JSON pointer ptr, with bounds checking.
Parameters
[in] ptr JSON pointer to the desired element
Returns
reference to the element pointed to by ptr
Constant.
Exceptions
std::out_of_range if the JSON pointer can not be resolved
std::domain_error if an array index begins with '0'
std::invalid_argument if an array index was not a number
{The behavior is shown in the example.,at_json_pointer_const}
Since
version 2.0.0
Definition at line 12055 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_checked().
     {
         return ptr.get_checked(this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::back () inline
access the last element
Returns a reference to the last element in the container. For a JSON container c, the expression c.back() is equivalent to
auto tmp = c.end();
--tmp;
return *tmp;
Returns
In case of a structured type (array or object), a reference to the last element is returned. In case of number, string, or boolean values, a reference to the value is returned.
Constant.
Precondition
The JSON value must not be null (would throw std::out_of_range) or an empty array or object (undefined behavior, guarded by assertions).
Postcondition
The JSON value remains unchanged.
Exceptions
std::out_of_range when called on null value.
{The following code shows an example for back().,back}
See also
front() – access the first element
Since
version 1.0.0
Definition at line 4242 of file json.hpp.
     {
         auto tmp = end();
         --tmp;
         return *tmp;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::back () const inline
access the last element
Returns a reference to the last element in the container. For a JSON container c, the expression c.back() is equivalent to
auto tmp = c.end();
--tmp;
return *tmp;
Returns
In case of a structured type (array or object), a reference to the last element is returned. In case of number, string, or boolean values, a reference to the value is returned.
Constant.
Precondition
The JSON value must not be null (would throw std::out_of_range) or an empty array or object (undefined behavior, guarded by assertions).
Postcondition
The JSON value remains unchanged.
Exceptions
std::out_of_range when called on null value.
{The following code shows an example for back().,back}
See also
front() – access the first element
Since
version 1.0.0
Definition at line 4252 of file json.hpp.
     {
         auto tmp = cend();
         --tmp;
         return *tmp;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin () inline noexcept
returns an iterator to the first element
Returns an iterator to the first element.
Illustration from cppreference.com
Returns
iterator to the first element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
{The following code shows an example for begin().,begin}
See also
cbegin() – returns a const iterator to the beginning
end() – returns an iterator to the end
cend() – returns a const iterator to the end
Since
version 1.0.0
Definition at line 4677 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_begin().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         iterator result(this);
         result.set_begin();
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin () const inline noexcept
returns a const iterator to the first element
Returns a const iterator to the first element.
Illustration from cppreference.com
Returns
const iterator to the first element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).begin().
{The following code shows an example for cbegin().,cbegin}
See also
begin() – returns an iterator to the beginning
end() – returns an iterator to the end
cend() – returns a const iterator to the end
Since
version 1.0.0
Definition at line 4687 of file json.hpp.
     {
         return cbegin();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cbegin () const inline noexcept
returns a const iterator to the first element
Returns a const iterator to the first element.
Illustration from cppreference.com
Returns
const iterator to the first element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).begin().
{The following code shows an example for cbegin().,cbegin}
See also
begin() – returns an iterator to the beginning
end() – returns an iterator to the end
cend() – returns a const iterator to the end
Since
version 1.0.0
Definition at line 4717 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_begin().
     {
         const_iterator result(this);
         result.set_begin();
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cend () const inline noexcept
returns a const iterator to one past the last element
Returns a const iterator to one past the last element.
Illustration from cppreference.com
Returns
const iterator one past the last element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).end().
{The following code shows an example for cend().,cend}
See also
end() – returns an iterator to the end
begin() – returns an iterator to the beginning
cbegin() – returns a const iterator to the beginning
Since
version 1.0.0
Definition at line 4788 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_end().
     {
         const_iterator result(this);
         result.set_end();
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::check_length (const size_t size, const size_t len, const size_t offset) inline static private
Definition at line 7207 of file json.hpp.
References JSON_THROW.
     {
         // simple case: requested length is greater than the vector's length
         if (len > size or offset > size)
         {
             JSON_THROW(std::out_of_range("len out of range"));
         }
         // second case: adding offset would result in overflow
         if ((size > (std::numeric_limits<size_t>::max() - offset)))
         {
             JSON_THROW(std::out_of_range("len+offset out of range"));
         }
         // last case: reading past the end of the vector
         if (len + offset > size)
         {
             JSON_THROW(std::out_of_range("len+offset out of range"));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::clear () inline noexcept
clears the contents
Clears the content of a JSON value and resets it to the default value as if basic_json(value_t) would have been called:
Value type initial value
null null
boolean false
string ""
number 0
object {}
array []
Linear in the size of the JSON value.
{The example below shows the effect of clear() to different JSON types.,clear}
Since
version 1.0.0
Definition at line 5192 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
     {
         switch (m_type)
         {
             case value_t::number_integer:
             {
                 m_value.number_integer = 0;
                 break;
             }
             case value_t::number_unsigned:
             {
                 m_value.number_unsigned = 0;
                 break;
             }
             case value_t::number_float:
             {
                 m_value.number_float = 0.0;
                 break;
             }
             case value_t::boolean:
             {
                 m_value.boolean = false;
                 break;
             }
             case value_t::string:
             {
                 m_value.string->clear();
                 break;
             }
             case value_t::array:
             {
                 m_value.array->clear();
                 break;
             }
             case value_t::object:
             {
                 m_value.object->clear();
                 break;
             }
             default:
             {
                 break;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> size_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::count (typename object_t::key_type key) const inline
returns the number of occurrences of a key in a JSON object
Returns the number of elements with key key. If ObjectType is the default std::map type, the return value will always be 0 (key was not found) or 1 (key was found).
Note
This method always returns 0 when executed on a JSON type that is not an object.
Parameters
[in] key key value of the element to count
Returns
Number of elements with key key. If the JSON value is not an object, the return value will be 0.
Logarithmic in the size of the JSON object.
{The example shows how count() is used.,count}
Since
version 1.0.0
Definition at line 4637 of file json.hpp.
     {
         // return 0 for all nonobject types
         return is_object() ? m_value.object->count(key) : 0;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::crbegin () const inline noexcept
returns a const reverse iterator to the last element
Returns a const iterator to the reverse-beginning; that is, the last element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).rbegin().
{The following code shows an example for crbegin().,crbegin}
See also
rbegin() – returns a reverse iterator to the beginning
rend() – returns a reverse iterator to the end
crend() – returns a const reverse iterator to the end
Since
version 1.0.0
Definition at line 4892 of file json.hpp.
     {
         return const_reverse_iterator(cend());
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T , typename... Args> static T* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::create (Args &&... args) inline static private
helper for exception-safe object creation
Definition at line 1625 of file json.hpp.
References nlohmann::detail::object.
     {
         AllocatorType<T> alloc;
         auto deleter = [&](T * object)
         {
             alloc.deallocate(object, 1);
         };
         std::unique_ptr<T, decltype(deleter)> object(alloc.allocate(1), deleter);
         alloc.construct(object.get(), std::forward<Args>(args)...);
         assert(object != nullptr);
         return object.release();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::crend () const inline noexcept
returns a const reverse iterator to one before the first
Returns a const reverse iterator to the reverse-end; that is, one before the first element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).rend().
{The following code shows an example for crend().,crend}
See also
rend() – returns a reverse iterator to the end
rbegin() – returns a reverse iterator to the beginning
crbegin() – returns a const reverse iterator to the beginning
Since
version 1.0.0
Definition at line 4921 of file json.hpp.
     {
         return const_reverse_iterator(cbegin());
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & source, const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & target, const std::string & path = "") inline static
creates a diff as a JSON patch
Creates a JSON Patch so that value source can be changed into the value target by calling patch function.
Invariant
For two JSON values source and target, the following code yields always true:
source.patch(diff(source, target)) == target;
Note
Currently, only remove, add, and replace operations are generated.
Parameters
[in] source JSON value to compare from
[in] target JSON value to compare against
[in] path helper value to create JSON pointers
Returns
a JSON patch to convert the source to target
Linear in the lengths of source and target.
{The following code shows how a JSON patch is created as a diff for two JSON values.,diff}
See also
patch – apply a JSON patch
RFC 6902 (JSON Patch)
Since
version 2.0.0
Definition at line 12459 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::size(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::type().
     {
         // the patch
         basic_json result(value_t::array);
         // if the values are the same, return empty patch
         if (source == target)
         {
             return result;
         }
         if (source.type() != target.type())
         {
             // different types: replace value
             result.push_back(
             {
                 {"op", "replace"},
                 {"path", path},
                 {"value", target}
             });
         }
         else
         {
             switch (source.type())
             {
                 case value_t::array:
                 {
                     // first pass: traverse common elements
                     size_t i = 0;
                     while (i < source.size() and i < target.size())
                     {
                         // recursive call to compare array values at index i
                         auto temp_diff = diff(source[i], target[i], path + "/" + std::to_string(i));
                         result.insert(result.end(), temp_diff.begin(), temp_diff.end());
                         ++i;
                     }
                     // i now reached the end of at least one array
                     // in a second pass, traverse the remaining elements
                     // remove my remaining elements
                     const auto end_index = static_cast<difference_type>(result.size());
                     while (i < source.size())
                     {
                         // add operations in reverse order to avoid invalid
                         // indices
                         result.insert(result.begin() + end_index, object(
{
                             {"op", "remove"},
                             {"path", path + "/" + std::to_string(i)}
                         }));
                         ++i;
                     }
                     // add other remaining elements
                     while (i < target.size())
                     {
                         result.push_back(
{
                             {"op", "add"},
                             {"path", path + "/" + std::to_string(i)},
                             {"value", target[i]}
                         });
                         ++i;
                     }
                     break;
                 }
                 case value_t::object:
                 {
                     // first pass: traverse this object's elements
                     for (auto it = source.begin(); it != source.end(); ++it)
                     {
                         // escape the key name to be used in a JSON patch
                         const auto key = json_pointer::escape(it.key());
                         if (target.find(it.key()) != target.end())
{
                             // recursive call to compare object values at key it
                             auto temp_diff = diff(it.value(), target[it.key()], path + "/" + key);
                             result.insert(result.end(), temp_diff.begin(), temp_diff.end());
                         }
                         else
{
                             // found a key that is not in o -> remove it
                             result.push_back(object(
{
                                 {"op", "remove"},
                                 {"path", path + "/" + key}
                             }));
                         }
                     }
                     // second pass: traverse other object's elements
                     for (auto it = target.begin(); it != target.end(); ++it)
                     {
                         if (source.find(it.key()) == source.end())
{
                             // found a key that is not in this -> add it
                             const auto key = json_pointer::escape(it.key());
                             result.push_back(
{
                                 {"op", "add"},
                                 {"path", path + "/" + key},
                                 {"value", it.value()}
                             });
                         }
                     }
                     break;
                 }
                 default:
                 {
                     // both primitive type: replace value
                     result.push_back(
                     {
                         {"op", "replace"},
                         {"path", path},
                         {"value", target}
                     });
                     break;
                 }
             }
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> string_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump (const int indent = -1) const inline
serialization
Serialization function for JSON values. The function tries to mimic Python's json.dumps() function, and currently supports its indent parameter.
Parameters
[in] indent If indent is nonnegative, then array elements and object members will be pretty-printed with that indent level. An indent level of 0 will only insert newlines. -1 (the default) selects the most compact representation.
Returns
string containing the serialization of the JSON value
Linear.
{The following example shows the effect of different indent parameters to the result of the serialization.,dump}
See also
https://docs.python.org/2/library/json.html#json.dump
Since
version 1.0.0
Definition at line 2646 of file json.hpp.
Referenced by std::hash< nlohmann::json >::operator()().
     {
         std::stringstream ss;
         // fix locale problems
         ss.imbue(std::locale::classic());
         // 6, 15 or 16 digits of precision allows round-trip IEEE 754
         // string->float->string, string->double->string or string->long
         // double->string; to be safe, we read this value from
         // std::numeric_limits<number_float_t>::digits10
         ss.precision(std::numeric_limits<double>::digits10);
         if (indent >= 0)
         {
             dump(ss, true, static_cast<unsigned int>(indent));
         }
         else
         {
             dump(ss, false, 0);
         }
         return ss.str();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::dump (std::ostream & o, const bool pretty_print, const unsigned int indent_step, const unsigned int current_indent = 0) const inline private
internal implementation of the serialization function
This function is called by the public member function dump and organizes the serialization internally. The indentation level is propagated as additional parameter. In case of arrays and objects, the function is called recursively. Note that
strings and object keys are escaped using escape_string()
integer numbers are converted implicitly via operator<<
floating-point numbers are converted to a string using "%g" format
Parameters
[out] o stream to write to
[in] pretty_print whether the output shall be pretty-printed
[in] indent_step the indent level
[in] current_indent the current indent level (only used internally)
Definition at line 8284 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
     {
         // variable to hold indentation for recursive calls
         unsigned int new_indent = current_indent;
         switch (m_type)
         {
             case value_t::object:
             {
                 if (m_value.object->empty())
                 {
                     o << "{}";
                     return;
                 }
                 o << "{";
                 // increase indentation
                 if (pretty_print)
                 {
                     new_indent += indent_step;
                     o << "\n";
                 }
                 for (auto i = m_value.object->cbegin(); i != m_value.object->cend(); ++i)
                 {
                     if (i != m_value.object->cbegin())
                     {
                         o << (pretty_print ? ",\n" : ",");
                     }
                     o << string_t(new_indent, ' ') << "\""
                       << escape_string(i->first) << "\":"
                       << (pretty_print ? " " : "");
                     i->second.dump(o, pretty_print, indent_step, new_indent);
                 }
                 // decrease indentation
                 if (pretty_print)
                 {
                     new_indent -= indent_step;
                     o << "\n";
                 }
                 o << string_t(new_indent, ' ') + "}";
                 return;
             }
             case value_t::array:
             {
                 if (m_value.array->empty())
                 {
                     o << "[]";
                     return;
                 }
                 o << "[";
                 // increase indentation
                 if (pretty_print)
                 {
                     new_indent += indent_step;
                     o << "\n";
                 }
                 for (auto i = m_value.array->cbegin(); i != m_value.array->cend(); ++i)
                 {
                     if (i != m_value.array->cbegin())
                     {
                         o << (pretty_print ? ",\n" : ",");
                     }
                     o << string_t(new_indent, ' ');
                     i->dump(o, pretty_print, indent_step, new_indent);
                 }
                 // decrease indentation
                 if (pretty_print)
                 {
                     new_indent -= indent_step;
                     o << "\n";
                 }
                 o << string_t(new_indent, ' ') << "]";
                 return;
             }
             case value_t::string:
             {
                 o << string_t("\"") << escape_string(*m_value.string) << "\"";
                 return;
             }
             case value_t::boolean:
             {
                 o << (m_value.boolean ? "true" : "false");
                 return;
             }
             case value_t::number_integer:
             {
                 o << m_value.number_integer;
                 return;
             }
             case value_t::number_unsigned:
             {
                 o << m_value.number_unsigned;
                 return;
             }
             case value_t::number_float:
             {
                 if (m_value.number_float == 0)
                 {
                     // special case for zero to get "0.0"/"-0.0"
                     o << (std::signbit(m_value.number_float) ? "-0.0" : "0.0");
                 }
                 else
                 {
                     o << m_value.number_float;
                 }
                 return;
             }
             case value_t::discarded:
             {
                 o << "<discarded>";
                 return;
             }
             case value_t::null:
             {
                 o << "null";
                 return;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class... Args> std::pair<iterator, bool> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::emplace (Args &&... args) inline
add an object to an object if key does not exist
Inserts a new element into a JSON object constructed in-place with the given args if there is no element with the key in the container. If the function is called on a JSON null value, an empty object is created before appending the value created from args.
Parameters
[in] args arguments to forward to a constructor of basic_json
Template Parameters
Args compatible types to create a basic_json object
Returns
a pair consisting of an iterator to the inserted element, or the already-existing element if no insertion happened, and a bool denoting whether the insertion took place.
Exceptions
std::domain_error when called on a type other than JSON object or null; example: "cannot use emplace() with number"
Logarithmic in the size of the container, O(log(size())).
{The example shows how emplace() can be used to add elements to a JSON object. Note how the null value was silently converted to a JSON object. Further note how no value is added if there was already one value stored with the same key.,emplace}
Since
version 2.0.8
Definition at line 5499 of file json.hpp.
References JSON_THROW, and nlohmann::detail::object.
     {
         // emplace only works for null objects or arrays
         if (not(is_null() or is_object()))
         {
             JSON_THROW(std::domain_error("cannot use emplace() with " + type_name()));
         }
         // transform null object into an object
         if (is_null())
         {
             m_type = value_t::object;
             m_value = value_t::object;
             assert_invariant();
         }
         // add element to array (perfect forwarding)
         auto res = m_value.object->emplace(std::forward<Args>(args)...);
         // create result iterator and set iterator to the result of emplace
         auto it = begin();
         it.m_it.object_iterator = res.first;
         // return pair of iterator and boolean
         return {it, res.second};
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class... Args> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::emplace_back (Args &&... args) inline
add an object to an array
Creates a JSON value from the passed parameters args to the end of the JSON value. If the function is called on a JSON null value, an empty array is created before appending the value created from args.
Parameters
[in] args arguments to forward to a constructor of basic_json
Template Parameters
Args compatible types to create a basic_json object
Exceptions
std::domain_error when called on a type other than JSON array or null; example: "cannot use emplace_back() with number"
Amortized constant.
{The example shows how push_back() can be used to add elements to a JSON array. Note how the null value was silently converted to a JSON array.,emplace_back}
Since
version 2.0.8
Definition at line 5451 of file json.hpp.
References nlohmann::detail::array, and JSON_THROW.
     {
         // emplace_back only works for null objects or arrays
         if (not(is_null() or is_array()))
         {
             JSON_THROW(std::domain_error("cannot use emplace_back() with " + type_name()));
         }
         // transform null object into an array
         if (is_null())
         {
             m_type = value_t::array;
             m_value = value_t::array;
             assert_invariant();
         }
         // add element to array (perfect forwarding)
         m_value.array->emplace_back(std::forward<Args>(args)...);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::empty () const inline noexcept
checks whether the container is empty
Checks if a JSON value has no elements.
Returns
The return value depends on the different types and is defined as follows:
Value type return value
null true
boolean false
string false
number false
object result of function object_t::empty()
array result of function array_t::empty()
Note
This function does not return whether a string stored as JSON value is empty - it returns whether the JSON container itself is empty which is false in the case of a string.
Constant, as long as array_t and object_t satisfy the Container concept; that is, their empty() functions have constant complexity.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of begin() == end().
{The following code uses empty() to check if a JSON object contains any elements.,empty}
See also
size() – returns the number of elements
Since
version 1.0.0
Definition at line 5002 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::null, and nlohmann::detail::object.
     {
         switch (m_type)
         {
             case value_t::null:
             {
                 // null values are empty
                 return true;
             }
             case value_t::array:
             {
                 // delegate call to array_t::empty()
                 return m_value.array->empty();
             }
             case value_t::object:
             {
                 // delegate call to object_t::empty()
                 return m_value.object->empty();
             }
             default:
             {
                 // all other types are nonempty
                 return false;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end () inline noexcept
returns an iterator to one past the last element
Returns an iterator to one past the last element.
Illustration from cppreference.com
Returns
iterator one past the last element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
{The following code shows an example for end().,end}
See also
cend() – returns a const iterator to the end
begin() – returns an iterator to the beginning
cbegin() – returns a const iterator to the beginning
Since
version 1.0.0
Definition at line 4748 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_end().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         iterator result(this);
         result.set_end();
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end () const inline noexcept
returns a const iterator to one past the last element
Returns a const iterator to one past the last element.
Illustration from cppreference.com
Returns
const iterator one past the last element
Constant.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).end().
{The following code shows an example for cend().,cend}
See also
end() – returns an iterator to the end
begin() – returns an iterator to the beginning
cbegin() – returns a const iterator to the beginning
Since
version 1.0.0
Definition at line 4758 of file json.hpp.
     {
         return cend();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class IteratorType , typename std::enable_if< std::is_same< IteratorType, typename basic_json_t::iterator >::value orstd::is_same< IteratorType, typename basic_json_t::const_iterator >::value, int >::type = 0> IteratorType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase (IteratorType pos) inline
remove element given an iterator
Removes the element specified by iterator pos. The iterator pos must be valid and dereferenceable. Thus the end() iterator (which is valid, but is not dereferenceable) cannot be used as a value for pos.
If called on a primitive type other than null, the resulting JSON value will be null.
Parameters
[in] pos iterator to the element to remove
Returns
Iterator following the last removed element. If the iterator pos refers to the last element, the end() iterator is returned.
Template Parameters
IteratorType an iterator or const_iterator
Postcondition
Invalidates iterators and references at or after the point of the erase, including the end() iterator.
Exceptions
std::domain_error if called on a null value; example: "cannot use erase() with null"
std::domain_error if called on an iterator which does not belong to the current JSON value; example: "iterator does not fit current value"
std::out_of_range if called on a primitive type with invalid iterator (i.e., any iterator which is not begin()); example: "iterator out of range"
The complexity depends on the type:
objects: amortized constant
arrays: linear in distance between pos and the end of the container
strings: linear in the length of the string
other types: constant
{The example shows the result of erase() for different JSON types.,erase__IteratorType}
See also
erase(IteratorType, IteratorType) – removes the elements in the given range
erase(const typename object_t::key_type&) – removes the element from an object at the given key
erase(const size_type) – removes the element from an array at the given index
Since
version 1.0.0
Definition at line 4308 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, JSON_THROW, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         // make sure iterator fits the current value
         if (this != pos.m_object)
         {
             JSON_THROW(std::domain_error("iterator does not fit current value"));
         }
         IteratorType result = end();
         switch (m_type)
         {
             case value_t::boolean:
             case value_t::number_float:
             case value_t::number_integer:
             case value_t::number_unsigned:
             case value_t::string:
             {
                 if (not pos.m_it.primitive_iterator.is_begin())
                 {
                     JSON_THROW(std::out_of_range("iterator out of range"));
                 }
                 if (is_string())
                 {
                     AllocatorType<string_t> alloc;
                     alloc.destroy(m_value.string);
                     alloc.deallocate(m_value.string, 1);
                     m_value.string = nullptr;
                 }
                 m_type = value_t::null;
                 assert_invariant();
                 break;
             }
             case value_t::object:
             {
                 result.m_it.object_iterator = m_value.object->erase(pos.m_it.object_iterator);
                 break;
             }
             case value_t::array:
             {
                 result.m_it.array_iterator = m_value.array->erase(pos.m_it.array_iterator);
                 break;
             }
             default:
             {
                 JSON_THROW(std::domain_error("cannot use erase() with " + type_name()));
             }
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class IteratorType , typename std::enable_if< std::is_same< IteratorType, typename basic_json_t::iterator >::value orstd::is_same< IteratorType, typename basic_json_t::const_iterator >::value, int >::type = 0> IteratorType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase (IteratorType first, IteratorType last) inline
remove elements given an iterator range
Removes the element specified by the range [first; last). The iterator first does not need to be dereferenceable if first == last: erasing an empty range is a no-op.
If called on a primitive type other than null, the resulting JSON value will be null.
Parameters
[in] first iterator to the beginning of the range to remove
[in] last iterator past the end of the range to remove
Returns
Iterator following the last removed element. If the iterator second refers to the last element, the end() iterator is returned.
Template Parameters
IteratorType an iterator or const_iterator
Postcondition
Invalidates iterators and references at or after the point of the erase, including the end() iterator.
Exceptions
std::domain_error if called on a null value; example: "cannot use erase() with null"
std::domain_error if called on iterators which does not belong to the current JSON value; example: "iterators do not fit current value"
std::out_of_range if called on a primitive type with invalid iterators (i.e., if first != begin() and last != end()); example: "iterators out of range"
The complexity depends on the type:
objects: log(size()) + std::distance(first, last)
arrays: linear in the distance between first and last, plus linear in the distance between last and end of the container
strings: linear in the length of the string
other types: constant
{The example shows the result of erase() for different JSON types.,erase__IteratorType_IteratorType}
See also
erase(IteratorType) – removes the element at a given position
erase(const typename object_t::key_type&) – removes the element from an object at the given key
erase(const size_type) – removes the element from an array at the given index
Since
version 1.0.0
Definition at line 4415 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, JSON_THROW, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
     {
         // make sure iterator fits the current value
         if (this != first.m_object or this != last.m_object)
         {
             JSON_THROW(std::domain_error("iterators do not fit current value"));
         }
         IteratorType result = end();
         switch (m_type)
         {
             case value_t::boolean:
             case value_t::number_float:
             case value_t::number_integer:
             case value_t::number_unsigned:
             case value_t::string:
             {
                 if (not first.m_it.primitive_iterator.is_begin() or not last.m_it.primitive_iterator.is_end())
                 {
                     JSON_THROW(std::out_of_range("iterators out of range"));
                 }
                 if (is_string())
                 {
                     AllocatorType<string_t> alloc;
                     alloc.destroy(m_value.string);
                     alloc.deallocate(m_value.string, 1);
                     m_value.string = nullptr;
                 }
                 m_type = value_t::null;
                 assert_invariant();
                 break;
             }
             case value_t::object:
             {
                 result.m_it.object_iterator = m_value.object->erase(first.m_it.object_iterator,
                                               last.m_it.object_iterator);
                 break;
             }
             case value_t::array:
             {
                 result.m_it.array_iterator = m_value.array->erase(first.m_it.array_iterator,
                                              last.m_it.array_iterator);
                 break;
             }
             default:
             {
                 JSON_THROW(std::domain_error("cannot use erase() with " + type_name()));
             }
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> size_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase (const typename object_t::key_type & key) inline
remove element from a JSON object given a key
Removes elements from a JSON object with the key value key.
Parameters
[in] key value of the elements to remove
Returns
Number of elements removed. If ObjectType is the default std::map type, the return value will always be 0 (key was not found) or 1 (key was found).
Postcondition
References and iterators to the erased elements are invalidated. Other references and iterators are not affected.
Exceptions
std::domain_error when called on a type other than JSON object; example: "cannot use erase() with null"
log(size()) + count(key)
{The example shows the effect of erase().,erase__key_type}
See also
erase(IteratorType) – removes the element at a given position
erase(IteratorType, IteratorType) – removes the elements in the given range
erase(const size_type) – removes the element from an array at the given index
Since
version 1.0.0
Definition at line 4503 of file json.hpp.
References JSON_THROW.
     {
         // this erase only works for objects
         if (is_object())
         {
             return m_value.object->erase(key);
         }
         JSON_THROW(std::domain_error("cannot use erase() with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase (const size_type idx) inline
remove element from a JSON array given an index
Removes element from a JSON array at the index idx.
Parameters
[in] idx index of the element to remove
Exceptions
std::domain_error when called on a type other than JSON array; example: "cannot use erase() with null"
std::out_of_range when idx >= size(); example: "array index 17 is out of range"
Linear in distance between idx and the end of the container.
{The example shows the effect of erase().,erase__size_type}
See also
erase(IteratorType) – removes the element at a given position
erase(IteratorType, IteratorType) – removes the elements in the given range
erase(const typename object_t::key_type&) – removes the element from an object at the given key
Since
version 1.0.0
Definition at line 4538 of file json.hpp.
References JSON_THROW.
     {
         // this erase only works for arrays
         if (is_array())
         {
             if (idx >= size())
             {
                 JSON_THROW(std::out_of_range("array index " + std::to_string(idx) + " is out of range"));
             }
             m_value.array->erase(m_value.array->begin() + static_cast<difference_type>(idx));
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use erase() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static string_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::escape_string (const string_t & s) inline static private
escape a string
Escape a string by replacing certain special characters by a sequence of an escape character (backslash) and another character and other control characters by a sequence of "\u" followed by a four-digit hex representation.
Parameters
[in] s the string to escape
Returns
the escaped string
Linear in the length of string s.
Definition at line 8160 of file json.hpp.
     {
         const auto space = extra_space(s);
         if (space == 0)
         {
             return s;
         }
         // create a result string of necessary size
         string_t result(s.size() + space, '\\');
         std::size_t pos = 0;
         for (const auto& c : s)
         {
             switch (c)
             {
                 // quotation mark (0x22)
                 case '"':
                 {
                     result[pos + 1] = '"';
                     pos += 2;
                     break;
                 }
                 // reverse solidus (0x5c)
                 case '\\':
                 {
                     // nothing to change
                     pos += 2;
                     break;
                 }
                 // backspace (0x08)
                 case '\b':
                 {
                     result[pos + 1] = 'b';
                     pos += 2;
                     break;
                 }
                 // formfeed (0x0c)
                 case '\f':
                 {
                     result[pos + 1] = 'f';
                     pos += 2;
                     break;
                 }
                 // newline (0x0a)
                 case '\n':
                 {
                     result[pos + 1] = 'n';
                     pos += 2;
                     break;
                 }
                 // carriage return (0x0d)
                 case '\r':
                 {
                     result[pos + 1] = 'r';
                     pos += 2;
                     break;
                 }
                 // horizontal tab (0x09)
                 case '\t':
                 {
                     result[pos + 1] = 't';
                     pos += 2;
                     break;
                 }
                 default:
                 {
                     if (c >= 0x00 and c <= 0x1f)
                     {
                         // convert a number 0..15 to its hex representation
                         // (0..f)
                         static const char hexify[16] =
{
                             '0', '1', '2', '3', '4', '5', '6', '7',
                             '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
                         };
                         // print character c as \uxxxx
                         for (const char m :
                     { 'u', '0', '0', hexify[c >> 4], hexify[c & 0x0f]
                         })
{
                             result[++pos] = m;
                         }
                         ++pos;
                     }
                     else
                     {
                         // all other characters are added as-is
                         result[pos++] = c;
                     }
                     break;
                 }
             }
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static std::size_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::extra_space (const string_t & s) inline static private noexcept
calculates the extra space to escape a JSON string
Parameters
[in] s the string to escape
Returns
the number of characters required to escape string s
Linear in the length of string s.
Definition at line 8114 of file json.hpp.
     {
         return std::accumulate(s.begin(), s.end(), size_t{},
                                [](size_t res, typename string_t::value_type c)
         {
             switch (c)
             {
                 case '"':
                 case '\\':
                 case '\b':
                 case '\f':
                 case '\n':
                 case '\r':
                 case '\t':
                 {
                     // from c (1 byte) to \x (2 bytes)
                     return res + 1;
                 }
                 default:
                 {
                     if (c >= 0x00 and c <= 0x1f)
                     {
                         // from c (1 byte) to \uxxxx (6 bytes)
                         return res + 5;
                     }
                     return res;
                 }
             }
         });
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find (typename object_t::key_type key) inline
find an element in a JSON object
Finds an element in a JSON object with key equivalent to key. If the element is not found or the JSON value is not an object, end() is returned.
Note
This method always returns end() when executed on a JSON type that is not an object.
Parameters
[in] key key value of the element to search for
Returns
Iterator to an element with key equivalent to key. If no such element is found or the JSON value is not an object, past-the-end (see end()) iterator is returned.
Logarithmic in the size of the JSON object.
{The example shows how find() is used.,find__key_type}
Since
version 1.0.0
Definition at line 4588 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[](), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         auto result = end();
         if (is_object())
         {
             result.m_it.object_iterator = m_value.object->find(key);
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find (typename object_t::key_type key) const inline
find an element in a JSON object
find an element in a JSON object Finds an element in a JSON object with key equivalent to key. If the element is not found or the JSON value is not an object, end() is returned.
Note
This method always returns end() when executed on a JSON type that is not an object.
Parameters
[in] key key value of the element to search for
Returns
Iterator to an element with key equivalent to key. If no such element is found or the JSON value is not an object, past-the-end (see end()) iterator is returned.
Logarithmic in the size of the JSON object.
{The example shows how find() is used.,find__key_type}
Since
version 1.0.0
Definition at line 4604 of file json.hpp.
     {
         auto result = cend();
         if (is_object())
         {
             result.m_it.object_iterator = m_value.object->find(key);
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::flatten () const inline
return flattened JSON value
The function creates a JSON object whose keys are JSON pointers (see RFC 6901) and whose values are all primitive. The original JSON value can be restored using the unflatten() function.
Returns
an object that maps JSON pointers to primitive values
Note
Empty objects and arrays are flattened to null and will not be reconstructed correctly by the unflatten() function.
Linear in the size the JSON value.
{The following code shows how a JSON object is flattened to an object whose keys consist of JSON pointers.,flatten}
See also
unflatten() for the reverse function
Since
version 2.0.0
Definition at line 12082 of file json.hpp.
References nlohmann::detail::object.
     {
         basic_json result(value_t::object);
         json_pointer::flatten("", *this, result);
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor (const std::vector< uint8_t > & v) inline static
create a JSON value from a byte vector in CBOR format
Deserializes a given byte vector v to a JSON value using the CBOR (Concise Binary Object Representation) serialization format.
Parameters
[in] v a byte vector in CBOR format
Returns
deserialized JSON value
Exceptions
std::invalid_argument if unsupported features from CBOR were used in the given vector v or if the input is not valid MessagePack
std::out_of_range if the given vector ends prematurely
Linear in the size of the byte vector v.
{The example shows the deserialization of a byte vector in CBOR format to a JSON value.,from_cbor}
See also
http://cbor.io
to_cbor(const basic_json&) for the analogous serialization
from_msgpack(const std::vector<uint8_t>&) for the related MessagePack format
Definition at line 8055 of file json.hpp.
     {
         size_t i = 0;
         return from_cbor_internal(v, i);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor_internal (const std::vector< uint8_t > & v, size_t & idx) inline static private
create a JSON value from a given CBOR vector
Parameters
[in] v CBOR serialization
[in] idx byte index to start reading from v
Returns
deserialized JSON value
Exceptions
std::invalid_argument if unsupported features from CBOR were used in the given vector v or if the input is not valid CBOR
std::out_of_range if the given vector ends prematurely
See also
https://tools.ietf.org/html/rfc7049
Definition at line 7480 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, nlohmann::detail::null, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back(), and nlohmann::detail::string.
     {
         // store and increment index
         const size_t current_idx = idx++;
         switch (v.at(current_idx))
         {
             // Integer 0x00..0x17 (0..23)
             case 0x00:
             case 0x01:
             case 0x02:
             case 0x03:
             case 0x04:
             case 0x05:
             case 0x06:
             case 0x07:
             case 0x08:
             case 0x09:
             case 0x0a:
             case 0x0b:
             case 0x0c:
             case 0x0d:
             case 0x0e:
             case 0x0f:
             case 0x10:
             case 0x11:
             case 0x12:
             case 0x13:
             case 0x14:
             case 0x15:
             case 0x16:
             case 0x17:
             {
                 return v[current_idx];
             }
             case 0x18: // Unsigned integer (one-byte uint8_t follows)
             {
                 idx += 1; // skip content byte
                 return get_from_vector<uint8_t>(v, current_idx);
             }
             case 0x19: // Unsigned integer (two-byte uint16_t follows)
             {
                 idx += 2; // skip 2 content bytes
                 return get_from_vector<uint16_t>(v, current_idx);
             }
             case 0x1a: // Unsigned integer (four-byte uint32_t follows)
             {
                 idx += 4; // skip 4 content bytes
                 return get_from_vector<uint32_t>(v, current_idx);
             }
             case 0x1b: // Unsigned integer (eight-byte uint64_t follows)
             {
                 idx += 8; // skip 8 content bytes
                 return get_from_vector<uint64_t>(v, current_idx);
             }
             // Negative integer -1-0x00..-1-0x17 (-1..-24)
             case 0x20:
             case 0x21:
             case 0x22:
             case 0x23:
             case 0x24:
             case 0x25:
             case 0x26:
             case 0x27:
             case 0x28:
             case 0x29:
             case 0x2a:
             case 0x2b:
             case 0x2c:
             case 0x2d:
             case 0x2e:
             case 0x2f:
             case 0x30:
             case 0x31:
             case 0x32:
             case 0x33:
             case 0x34:
             case 0x35:
             case 0x36:
             case 0x37:
             {
                 return static_cast<int8_t>(0x20 - 1 - v[current_idx]);
             }
             case 0x38: // Negative integer (one-byte uint8_t follows)
             {
                 idx += 1; // skip content byte
                 // must be uint8_t !
                 return static_cast<number_integer_t>(-1) - get_from_vector<uint8_t>(v, current_idx);
             }
             case 0x39: // Negative integer -1-n (two-byte uint16_t follows)
             {
                 idx += 2; // skip 2 content bytes
                 return static_cast<number_integer_t>(-1) - get_from_vector<uint16_t>(v, current_idx);
             }
             case 0x3a: // Negative integer -1-n (four-byte uint32_t follows)
             {
                 idx += 4; // skip 4 content bytes
                 return static_cast<number_integer_t>(-1) - get_from_vector<uint32_t>(v, current_idx);
             }
             case 0x3b: // Negative integer -1-n (eight-byte uint64_t follows)
             {
                 idx += 8; // skip 8 content bytes
                 return static_cast<number_integer_t>(-1) - static_cast<number_integer_t>(get_from_vector<uint64_t>(v, current_idx));
             }
             // UTF-8 string (0x00..0x17 bytes follow)
             case 0x60:
             case 0x61:
             case 0x62:
             case 0x63:
             case 0x64:
             case 0x65:
             case 0x66:
             case 0x67:
             case 0x68:
             case 0x69:
             case 0x6a:
             case 0x6b:
             case 0x6c:
             case 0x6d:
             case 0x6e:
             case 0x6f:
             case 0x70:
             case 0x71:
             case 0x72:
             case 0x73:
             case 0x74:
             case 0x75:
             case 0x76:
             case 0x77:
             {
                 const auto len = static_cast<size_t>(v[current_idx] - 0x60);
                 const size_t offset = current_idx + 1;
                 idx += len; // skip content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
             case 0x78: // UTF-8 string (one-byte uint8_t for n follows)
             {
                 const auto len = static_cast<size_t>(get_from_vector<uint8_t>(v, current_idx));
                 const size_t offset = current_idx + 2;
                 idx += len + 1; // skip size byte + content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
             case 0x79: // UTF-8 string (two-byte uint16_t for n follow)
             {
                 const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                 const size_t offset = current_idx + 3;
                 idx += len + 2; // skip 2 size bytes + content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
             case 0x7a: // UTF-8 string (four-byte uint32_t for n follow)
             {
                 const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                 const size_t offset = current_idx + 5;
                 idx += len + 4; // skip 4 size bytes + content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
             case 0x7b: // UTF-8 string (eight-byte uint64_t for n follow)
             {
                 const auto len = static_cast<size_t>(get_from_vector<uint64_t>(v, current_idx));
                 const size_t offset = current_idx + 9;
                 idx += len + 8; // skip 8 size bytes + content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
             case 0x7f: // UTF-8 string (indefinite length)
             {
                 std::string result;
                 while (v.at(idx) != 0xff)
                 {
                     string_t s = from_cbor_internal(v, idx);
                     result += s;
                 }
                 // skip break byte (0xFF)
                 idx += 1;
                 return result;
             }
             // array (0x00..0x17 data items follow)
             case 0x80:
             case 0x81:
             case 0x82:
             case 0x83:
             case 0x84:
             case 0x85:
             case 0x86:
             case 0x87:
             case 0x88:
             case 0x89:
             case 0x8a:
             case 0x8b:
             case 0x8c:
             case 0x8d:
             case 0x8e:
             case 0x8f:
             case 0x90:
             case 0x91:
             case 0x92:
             case 0x93:
             case 0x94:
             case 0x95:
             case 0x96:
             case 0x97:
             {
                 basic_json result = value_t::array;
                 const auto len = static_cast<size_t>(v[current_idx] - 0x80);
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 return result;
             }
             case 0x98: // array (one-byte uint8_t for n follows)
             {
                 basic_json result = value_t::array;
                 const auto len = static_cast<size_t>(get_from_vector<uint8_t>(v, current_idx));
                 idx += 1; // skip 1 size byte
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 return result;
             }
             case 0x99: // array (two-byte uint16_t for n follow)
             {
                 basic_json result = value_t::array;
                 const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                 idx += 2; // skip 4 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 return result;
             }
             case 0x9a: // array (four-byte uint32_t for n follow)
             {
                 basic_json result = value_t::array;
                 const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                 idx += 4; // skip 4 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 return result;
             }
             case 0x9b: // array (eight-byte uint64_t for n follow)
             {
                 basic_json result = value_t::array;
                 const auto len = static_cast<size_t>(get_from_vector<uint64_t>(v, current_idx));
                 idx += 8; // skip 8 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 return result;
             }
             case 0x9f: // array (indefinite length)
             {
                 basic_json result = value_t::array;
                 while (v.at(idx) != 0xff)
                 {
                     result.push_back(from_cbor_internal(v, idx));
                 }
                 // skip break byte (0xFF)
                 idx += 1;
                 return result;
             }
             // map (0x00..0x17 pairs of data items follow)
             case 0xa0:
             case 0xa1:
             case 0xa2:
             case 0xa3:
             case 0xa4:
             case 0xa5:
             case 0xa6:
             case 0xa7:
             case 0xa8:
             case 0xa9:
             case 0xaa:
             case 0xab:
             case 0xac:
             case 0xad:
             case 0xae:
             case 0xaf:
             case 0xb0:
             case 0xb1:
             case 0xb2:
             case 0xb3:
             case 0xb4:
             case 0xb5:
             case 0xb6:
             case 0xb7:
             {
                 basic_json result = value_t::object;
                 const auto len = static_cast<size_t>(v[current_idx] - 0xa0);
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 return result;
             }
             case 0xb8: // map (one-byte uint8_t for n follows)
             {
                 basic_json result = value_t::object;
                 const auto len = static_cast<size_t>(get_from_vector<uint8_t>(v, current_idx));
                 idx += 1; // skip 1 size byte
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 return result;
             }
             case 0xb9: // map (two-byte uint16_t for n follow)
             {
                 basic_json result = value_t::object;
                 const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                 idx += 2; // skip 2 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 return result;
             }
             case 0xba: // map (four-byte uint32_t for n follow)
             {
                 basic_json result = value_t::object;
                 const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                 idx += 4; // skip 4 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 return result;
             }
             case 0xbb: // map (eight-byte uint64_t for n follow)
             {
                 basic_json result = value_t::object;
                 const auto len = static_cast<size_t>(get_from_vector<uint64_t>(v, current_idx));
                 idx += 8; // skip 8 size bytes
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 return result;
             }
             case 0xbf: // map (indefinite length)
             {
                 basic_json result = value_t::object;
                 while (v.at(idx) != 0xff)
                 {
                     std::string key = from_cbor_internal(v, idx);
                     result[key] = from_cbor_internal(v, idx);
                 }
                 // skip break byte (0xFF)
                 idx += 1;
                 return result;
             }
             case 0xf4: // false
             {
                 return false;
             }
             case 0xf5: // true
             {
                 return true;
             }
             case 0xf6: // null
             {
                 return value_t::null;
             }
             case 0xf9: // Half-Precision Float (two-byte IEEE 754)
             {
                 idx += 2; // skip two content bytes
                 // code from RFC 7049, Appendix D, Figure 3:
                 // As half-precision floating-point numbers were only added to
                 // IEEE 754 in 2008, today's programming platforms often still
                 // only have limited support for them. It is very easy to
                 // include at least decoding support for them even without such
                 // support. An example of a small decoder for half-precision
                 // floating-point numbers in the C language is shown in Fig. 3.
                 const int half = (v.at(current_idx + 1) << 8) + v.at(current_idx + 2);
                 const int exp = (half >> 10) & 0x1f;
                 const int mant = half & 0x3ff;
                 double val;
                 if (exp == 0)
                 {
                     val = std::ldexp(mant, -24);
                 }
                 else if (exp != 31)
                 {
                     val = std::ldexp(mant + 1024, exp - 25);
                 }
                 else
                 {
                     val = mant == 0 ? INFINITY : NAN;
                 }
                 return (half & 0x8000) != 0 ? -val : val;
             }
             case 0xfa: // Single-Precision Float (four-byte IEEE 754)
             {
                 // copy bytes in reverse order into the float variable
                 float res;
                 for (size_t byte = 0; byte < sizeof(float); ++byte)
                 {
                     reinterpret_cast<uint8_t*>(&res)[sizeof(float) - byte - 1] = v.at(current_idx + 1 + byte);
                 }
                 idx += sizeof(float); // skip content bytes
                 return res;
             }
             case 0xfb: // Double-Precision Float (eight-byte IEEE 754)
             {
                 // copy bytes in reverse order into the double variable
                 double res;
                 for (size_t byte = 0; byte < sizeof(double); ++byte)
                 {
                     reinterpret_cast<uint8_t*>(&res)[sizeof(double) - byte - 1] = v.at(current_idx + 1 + byte);
                 }
                 idx += sizeof(double); // skip content bytes
                 return res;
             }
             default: // anything else (0xFF is handled inside the other types)
             {
                 JSON_THROW(std::invalid_argument("error parsing a CBOR @ " + std::to_string(current_idx) + ": " + std::to_string(static_cast<int>(v[current_idx]))));
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack (const std::vector< uint8_t > & v) inline static
create a JSON value from a byte vector in MessagePack format
Deserializes a given byte vector v to a JSON value using the MessagePack serialization format.
Parameters
[in] v a byte vector in MessagePack format
Returns
deserialized JSON value
Exceptions
std::invalid_argument if unsupported features from MessagePack were used in the given vector v or if the input is not valid MessagePack
std::out_of_range if the given vector ends prematurely
Linear in the size of the byte vector v.
{The example shows the deserialization of a byte vector in MessagePack format to a JSON value.,from_msgpack}
See also
http://msgpack.org
to_msgpack(const basic_json&) for the analogous serialization
from_cbor(const std::vector<uint8_t>&) for the related CBOR format
Definition at line 7998 of file json.hpp.
     {
         size_t i = 0;
         return from_msgpack_internal(v, i);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack_internal (const std::vector< uint8_t > & v, size_t & idx) inline static private
create a JSON value from a given MessagePack vector
Parameters
[in] v MessagePack serialization
[in] idx byte index to start reading from v
Returns
deserialized JSON value
Exceptions
std::invalid_argument if unsupported features from MessagePack were used in the given vector v or if the input is not valid MessagePack
std::out_of_range if the given vector ends prematurely
See also
https://github.com/msgpack/msgpack/blob/master/spec.md
Definition at line 7242 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, nlohmann::detail::null, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back(), and nlohmann::detail::string.
     {
         // make sure reading 1 byte is safe
         check_length(v.size(), 1, idx);
         // store and increment index
         const size_t current_idx = idx++;
         if (v[current_idx] <= 0xbf)
         {
             if (v[current_idx] <= 0x7f) // positive fixint
             {
                 return v[current_idx];
             }
             if (v[current_idx] <= 0x8f) // fixmap
             {
                 basic_json result = value_t::object;
                 const size_t len = v[current_idx] & 0x0f;
                 for (size_t i = 0; i < len; ++i)
                 {
                     std::string key = from_msgpack_internal(v, idx);
                     result[key] = from_msgpack_internal(v, idx);
                 }
                 return result;
             }
             else if (v[current_idx] <= 0x9f) // fixarray
             {
                 basic_json result = value_t::array;
                 const size_t len = v[current_idx] & 0x0f;
                 for (size_t i = 0; i < len; ++i)
                 {
                     result.push_back(from_msgpack_internal(v, idx));
                 }
                 return result;
             }
             else // fixstr
             {
                 const size_t len = v[current_idx] & 0x1f;
                 const size_t offset = current_idx + 1;
                 idx += len; // skip content bytes
                 check_length(v.size(), len, offset);
                 return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
             }
         }
         else if (v[current_idx] >= 0xe0) // negative fixint
         {
             return static_cast<int8_t>(v[current_idx]);
         }
         else
         {
             switch (v[current_idx])
             {
                 case 0xc0: // nil
                 {
                     return value_t::null;
                 }
                 case 0xc2: // false
                 {
                     return false;
                 }
                 case 0xc3: // true
                 {
                     return true;
                 }
                 case 0xca: // float 32
                 {
                     // copy bytes in reverse order into the double variable
                     float res;
                     for (size_t byte = 0; byte < sizeof(float); ++byte)
                     {
                         reinterpret_cast<uint8_t*>(&res)[sizeof(float) - byte - 1] = v.at(current_idx + 1 + byte);
                     }
                     idx += sizeof(float); // skip content bytes
                     return res;
                 }
                 case 0xcb: // float 64
                 {
                     // copy bytes in reverse order into the double variable
                     double res;
                     for (size_t byte = 0; byte < sizeof(double); ++byte)
                     {
                         reinterpret_cast<uint8_t*>(&res)[sizeof(double) - byte - 1] = v.at(current_idx + 1 + byte);
                     }
                     idx += sizeof(double); // skip content bytes
                     return res;
                 }
                 case 0xcc: // uint 8
                 {
                     idx += 1; // skip content byte
                     return get_from_vector<uint8_t>(v, current_idx);
                 }
                 case 0xcd: // uint 16
                 {
                     idx += 2; // skip 2 content bytes
                     return get_from_vector<uint16_t>(v, current_idx);
                 }
                 case 0xce: // uint 32
                 {
                     idx += 4; // skip 4 content bytes
                     return get_from_vector<uint32_t>(v, current_idx);
                 }
                 case 0xcf: // uint 64
                 {
                     idx += 8; // skip 8 content bytes
                     return get_from_vector<uint64_t>(v, current_idx);
                 }
                 case 0xd0: // int 8
                 {
                     idx += 1; // skip content byte
                     return get_from_vector<int8_t>(v, current_idx);
                 }
                 case 0xd1: // int 16
                 {
                     idx += 2; // skip 2 content bytes
                     return get_from_vector<int16_t>(v, current_idx);
                 }
                 case 0xd2: // int 32
                 {
                     idx += 4; // skip 4 content bytes
                     return get_from_vector<int32_t>(v, current_idx);
                 }
                 case 0xd3: // int 64
                 {
                     idx += 8; // skip 8 content bytes
                     return get_from_vector<int64_t>(v, current_idx);
                 }
                 case 0xd9: // str 8
                 {
                     const auto len = static_cast<size_t>(get_from_vector<uint8_t>(v, current_idx));
                     const size_t offset = current_idx + 2;
                     idx += len + 1; // skip size byte + content bytes
                     check_length(v.size(), len, offset);
                     return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
                 }
                 case 0xda: // str 16
                 {
                     const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                     const size_t offset = current_idx + 3;
                     idx += len + 2; // skip 2 size bytes + content bytes
                     check_length(v.size(), len, offset);
                     return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
                 }
                 case 0xdb: // str 32
                 {
                     const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                     const size_t offset = current_idx + 5;
                     idx += len + 4; // skip 4 size bytes + content bytes
                     check_length(v.size(), len, offset);
                     return std::string(reinterpret_cast<const char*>(v.data()) + offset, len);
                 }
                 case 0xdc: // array 16
                 {
                     basic_json result = value_t::array;
                     const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                     idx += 2; // skip 2 size bytes
                     for (size_t i = 0; i < len; ++i)
                     {
                         result.push_back(from_msgpack_internal(v, idx));
                     }
                     return result;
                 }
                 case 0xdd: // array 32
                 {
                     basic_json result = value_t::array;
                     const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                     idx += 4; // skip 4 size bytes
                     for (size_t i = 0; i < len; ++i)
                     {
                         result.push_back(from_msgpack_internal(v, idx));
                     }
                     return result;
                 }
                 case 0xde: // map 16
                 {
                     basic_json result = value_t::object;
                     const auto len = static_cast<size_t>(get_from_vector<uint16_t>(v, current_idx));
                     idx += 2; // skip 2 size bytes
                     for (size_t i = 0; i < len; ++i)
                     {
                         std::string key = from_msgpack_internal(v, idx);
                         result[key] = from_msgpack_internal(v, idx);
                     }
                     return result;
                 }
                 case 0xdf: // map 32
                 {
                     basic_json result = value_t::object;
                     const auto len = static_cast<size_t>(get_from_vector<uint32_t>(v, current_idx));
                     idx += 4; // skip 4 size bytes
                     for (size_t i = 0; i < len; ++i)
                     {
                         std::string key = from_msgpack_internal(v, idx);
                         result[key] = from_msgpack_internal(v, idx);
                     }
                     return result;
                 }
                 default:
                 {
                     JSON_THROW(std::invalid_argument("error parsing a msgpack @ " + std::to_string(current_idx) + ": " + std::to_string(static_cast<int>(v[current_idx]))));
                 }
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::front () inline
access the first element
Returns a reference to the first element in the container. For a JSON container c, the expression c.front() is equivalent to *c.begin().
Returns
In case of a structured type (array or object), a reference to the first element is returned. In case of number, string, or boolean values, a reference to the value is returned.
Constant.
Precondition
The JSON value must not be null (would throw std::out_of_range) or an empty array or object (undefined behavior, guarded by assertions).
Postcondition
The JSON value remains unchanged.
Exceptions
std::out_of_range when called on null value
{The following code shows an example for front().,front}
See also
back() – access the last element
Since
version 1.0.0
Definition at line 4199 of file json.hpp.
     {
         return *begin();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::front () const inline
access the first element
Returns a reference to the first element in the container. For a JSON container c, the expression c.front() is equivalent to *c.begin().
Returns
In case of a structured type (array or object), a reference to the first element is returned. In case of number, string, or boolean values, a reference to the value is returned.
Constant.
Precondition
The JSON value must not be null (would throw std::out_of_range) or an empty array or object (undefined behavior, guarded by assertions).
Postcondition
The JSON value remains unchanged.
Exceptions
std::out_of_range when called on null value
{The following code shows an example for front().,front}
See also
back() – access the last element
Since
version 1.0.0
Definition at line 4207 of file json.hpp.
     {
         return *cbegin();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename BasicJsonType , detail::enable_if_t< std::is_same< typename std::remove_const< BasicJsonType >::type, basic_json_t >::value, int > = 0> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get () const inline
get special-case overload
This overloads avoids a lot of template boilerplate, it can be seen as the identity method
Template Parameters
BasicJsonType == basic_json
Returns
a copy of *this
Constant.
Since
version 2.1.0
Definition at line 3180 of file json.hpp.
Referenced by Driver::Driver(), Driver::InitAnimal(), and Driver::InitZoo().
     {
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ValueTypeCV , typename ValueType = detail::uncvref_t<ValueTypeCV>, detail::enable_if_t< not std::is_same< basic_json_t, ValueType >::value anddetail::has_from_json< basic_json_t, ValueType >::value andnot detail::has_non_default_from_json< basic_json_t, ValueType >::value, int > = 0> ValueType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get () const inline noexcept
get a value (explicit)
Explicit type conversion between the JSON value and a compatible value which is CopyConstructible and DefaultConstructible. The value is converted by calling the json_serializer<ValueType> from_json() method.
The function is equivalent to executing
ValueType ret;
JSONSerializer<ValueType>::from_json(*this, ret);
return ret;
This overloads is chosen if:
ValueType is not basic_json,
json_serializer<ValueType> has a from_json() method of the form void from_json(const @ref basic_json&, ValueType&), and
json_serializer<ValueType> does not have a from_json() method of the form ValueType from_json(const @ref basic_json&)
Template Parameters
ValueTypeCV the provided value type
ValueType the returned value type
Returns
copy of the JSON value, converted to ValueType
Exceptions
what json_serializer<ValueType> from_json() method throws
{The example below shows several conversions from JSON values to other types. There a few things to note: (1) Floating-point numbers can be converted to integers\, (2) A JSON array can be converted to a standard std::vector<short>\, (3) A JSON object can be converted to C++ associative containers such as std::unordered_map<std::string\, json>.,get__ValueType_const}
Since
version 2.1.0
Definition at line 3232 of file json.hpp.
References nlohmann::detail::from_json().
     {
         // we cannot static_assert on ValueTypeCV being non-const, because
         // there is support for get<const basic_json_t>(), which is why we
         // still need the uncvref
         static_assert(not std::is_reference<ValueTypeCV>::value,
                       "get() cannot be used with reference types, you might want to use get_ref()");
         static_assert(std::is_default_constructible<ValueType>::value,
                       "types must be DefaultConstructible when used with get()");
         ValueType ret;
         JSONSerializer<ValueType>::from_json(*this, ret);
         return ret;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ValueTypeCV , typename ValueType = detail::uncvref_t<ValueTypeCV>, detail::enable_if_t< not std::is_same< basic_json_t, ValueType >::value anddetail::has_non_default_from_json< basic_json_t, ValueType >::value, int > = 0> ValueType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get () const inline noexcept
get a value (explicit); special case
Explicit type conversion between the JSON value and a compatible value which is not CopyConstructible and not DefaultConstructible. The value is converted by calling the json_serializer<ValueType> from_json() method.
The function is equivalent to executing
return JSONSerializer<ValueTypeCV>::from_json(*this);
This overloads is chosen if:
ValueType is not basic_json and
json_serializer<ValueType> has a from_json() method of the form ValueType from_json(const @ref basic_json&)
Note
If json_serializer<ValueType> has both overloads of from_json(), this one is chosen.
Template Parameters
ValueTypeCV the provided value type
ValueType the returned value type
Returns
copy of the JSON value, converted to ValueType
Exceptions
what json_serializer<ValueType> from_json() method throws
Since
version 2.1.0
Definition at line 3285 of file json.hpp.
References nlohmann::detail::from_json().
     {
         static_assert(not std::is_reference<ValueTypeCV>::value,
                       "get() cannot be used with reference types, you might want to use get_ref()");
         return JSONSerializer<ValueTypeCV>::from_json(*this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0> PointerType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get () inline noexcept
get a pointer value (explicit)
Explicit pointer access to the internally stored JSON value. No copies are made.
Warning
The pointer becomes invalid if the underlying JSON object changes.
Template Parameters
PointerType pointer type; must be a pointer to array_t, object_t, string_t, boolean_t, number_integer_t, number_unsigned_t, or number_float_t.
Returns
pointer to the internally stored JSON value if the requested pointer type PointerType fits to the JSON value; nullptr otherwise
Constant.
{The example below shows how pointers to internal values of a JSON value can be requested. Note that no type conversions are made and a nullptr is returned if the value and the requested pointer type does not match.,get__PointerType}
See also
get_ptr() for explicit pointer-member access
Since
version 1.0.0
Definition at line 3322 of file json.hpp.
     {
         // delegate the call to get_ptr
         return get_ptr<PointerType>();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0> constexpr const PointerType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get () const inline noexcept
get a pointer value (explicit)
get a pointer value (explicit) Explicit pointer access to the internally stored JSON value. No copies are made.
Warning
The pointer becomes invalid if the underlying JSON object changes.
Template Parameters
PointerType pointer type; must be a pointer to array_t, object_t, string_t, boolean_t, number_integer_t, number_unsigned_t, or number_float_t.
Returns
pointer to the internally stored JSON value if the requested pointer type PointerType fits to the JSON value; nullptr otherwise
Constant.
{The example below shows how pointers to internal values of a JSON value can be requested. Note that no type conversions are made and a nullptr is returned if the value and the requested pointer type does not match.,get__PointerType}
See also
get_ptr() for explicit pointer-member access
Since
version 1.0.0
Definition at line 3334 of file json.hpp.
     {
         // delegate the call to get_ptr
         return get_ptr<PointerType>();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static allocator_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_allocator () inline static
returns the allocator associated with the container
Definition at line 1101 of file json.hpp.
     {
         return allocator_type();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T > static T nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_from_vector (const std::vector< uint8_t > & vec, const size_t current_index) inline static private
take sufficient bytes from a vector to fill an integer variable
In the context of binary serialization formats, we need to read several bytes from a byte vector and combine them to multi-byte integral data types.
Parameters
[in] vec byte vector to read from
[in] current_index the position in the vector after which to read
Returns
the next sizeof(T) bytes from vec, in reverse order as T
Template Parameters
T the integral return type
Exceptions
std::out_of_range if there are less than sizeof(T)+1 bytes in the vector vec to read
In the for loop, the bytes from the vector are copied in reverse order into the return value. In the figures below, let sizeof(T)=4 and i be the loop variable.
Precondition:
vec: | | | a | b | c | d | T: | | | | | ^ ^ ^ ^ current_index i ptr sizeof(T)
Postcondition:
vec: | | | a | b | c | d | T: | d | c | b | a | ^ ^ ^ | i ptr current_index
See also
Code adapted from http://stackoverflow.com/a/41031865/266378.
Definition at line 6658 of file json.hpp.
References JSON_THROW.
     {
         if (current_index + sizeof(T) + 1 > vec.size())
         {
             JSON_THROW(std::out_of_range("cannot read " + std::to_string(sizeof(T)) + " bytes from vector"));
         }
         T result;
         auto* ptr = reinterpret_cast<uint8_t*>(&result);
         for (size_t i = 0; i < sizeof(T); ++i)
         {
             *ptr++ = vec[current_index + sizeof(T) - i];
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> boolean_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl (boolean_t *) const inline private
get a boolean (explicit)
Definition at line 3033 of file json.hpp.
References JSON_THROW.
     {
         if (is_boolean())
         {
             return m_value.boolean;
         }
         JSON_THROW(std::domain_error("type must be boolean, but is " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> object_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (object_t *) inline private noexcept
get a pointer to the value (object)
Definition at line 3044 of file json.hpp.
     {
         return is_object() ? m_value.object : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const object_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const object_t *) const inline private noexcept
get a pointer to the value (object)
Definition at line 3050 of file json.hpp.
     {
         return is_object() ? m_value.object : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> array_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (array_t *) inline private noexcept
get a pointer to the value (array)
Definition at line 3056 of file json.hpp.
     {
         return is_array() ? m_value.array : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const array_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const array_t *) const inline private noexcept
get a pointer to the value (array)
Definition at line 3062 of file json.hpp.
     {
         return is_array() ? m_value.array : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> string_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (string_t *) inline private noexcept
get a pointer to the value (string)
Definition at line 3068 of file json.hpp.
     {
         return is_string() ? m_value.string : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const string_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const string_t *) const inline private noexcept
get a pointer to the value (string)
Definition at line 3074 of file json.hpp.
     {
         return is_string() ? m_value.string : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> boolean_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (boolean_t *) inline private noexcept
get a pointer to the value (boolean)
Definition at line 3080 of file json.hpp.
     {
         return is_boolean() ? &m_value.boolean : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const boolean_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const boolean_t *) const inline private noexcept
get a pointer to the value (boolean)
Definition at line 3086 of file json.hpp.
     {
         return is_boolean() ? &m_value.boolean : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> number_integer_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (number_integer_t *) inline private noexcept
get a pointer to the value (integer number)
Definition at line 3092 of file json.hpp.
     {
         return is_number_integer() ? &m_value.number_integer : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const number_integer_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const number_integer_t *) const inline private noexcept
get a pointer to the value (integer number)
Definition at line 3098 of file json.hpp.
     {
         return is_number_integer() ? &m_value.number_integer : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> number_unsigned_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (number_unsigned_t *) inline private noexcept
get a pointer to the value (unsigned number)
Definition at line 3104 of file json.hpp.
     {
         return is_number_unsigned() ? &m_value.number_unsigned : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const number_unsigned_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const number_unsigned_t *) const inline private noexcept
get a pointer to the value (unsigned number)
Definition at line 3110 of file json.hpp.
     {
         return is_number_unsigned() ? &m_value.number_unsigned : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> number_float_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (number_float_t *) inline private noexcept
get a pointer to the value (floating-point number)
Definition at line 3116 of file json.hpp.
     {
         return is_number_float() ? &m_value.number_float : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr const number_float_t* nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_impl_ptr (const number_float_t *) const inline private noexcept
get a pointer to the value (floating-point number)
Definition at line 3122 of file json.hpp.
     {
         return is_number_float() ? &m_value.number_float : nullptr;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value, int >::type = 0> PointerType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_ptr () inline noexcept
get a pointer value (implicit)
Implicit pointer access to the internally stored JSON value. No copies are made.
Warning
Writing data to the pointee of the result yields an undefined state.
Template Parameters
PointerType pointer type; must be a pointer to array_t, object_t, string_t, boolean_t, number_integer_t, number_unsigned_t, or number_float_t. Enforced by a static assertion.
Returns
pointer to the internally stored JSON value if the requested pointer type PointerType fits to the JSON value; nullptr otherwise
Constant.
{The example below shows how pointers to internal values of a JSON value can be requested. Note that no type conversions are made and a nullptr is returned if the value and the requested pointer type does not match.,get_ptr}
Since
version 1.0.0
Definition at line 3368 of file json.hpp.
     {
         // get the type of the PointerType (remove pointer and const)
         using pointee_t = typename std::remove_const<typename
                           std::remove_pointer<typename
                           std::remove_const<PointerType>::type>::type>::type;
         // make sure the type matches the allowed types
         static_assert(
             std::is_same<object_t, pointee_t>::value
             or std::is_same<array_t, pointee_t>::value
             or std::is_same<string_t, pointee_t>::value
             or std::is_same<boolean_t, pointee_t>::value
             or std::is_same<number_integer_t, pointee_t>::value
             or std::is_same<number_unsigned_t, pointee_t>::value
             or std::is_same<number_float_t, pointee_t>::value
             , "incompatible pointer type");
         // delegate the call to get_impl_ptr<>()
         return get_impl_ptr(static_cast<PointerType>(nullptr));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename PointerType , typename std::enable_if< std::is_pointer< PointerType >::value andstd::is_const< typename std::remove_pointer< PointerType >::type >::value, int >::type = 0> constexpr const PointerType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_ptr () const inline noexcept
get a pointer value (implicit)
get a pointer value (implicit) Implicit pointer access to the internally stored JSON value. No copies are made.
Warning
Writing data to the pointee of the result yields an undefined state.
Template Parameters
PointerType pointer type; must be a pointer to array_t, object_t, string_t, boolean_t, number_integer_t, number_unsigned_t, or number_float_t. Enforced by a static assertion.
Returns
pointer to the internally stored JSON value if the requested pointer type PointerType fits to the JSON value; nullptr otherwise
Constant.
{The example below shows how pointers to internal values of a JSON value can be requested. Note that no type conversions are made and a nullptr is returned if the value and the requested pointer type does not match.,get_ptr}
Since
version 1.0.0
Definition at line 3396 of file json.hpp.
     {
         // get the type of the PointerType (remove pointer and const)
         using pointee_t = typename std::remove_const<typename
                           std::remove_pointer<typename
                           std::remove_const<PointerType>::type>::type>::type;
         // make sure the type matches the allowed types
         static_assert(
             std::is_same<object_t, pointee_t>::value
             or std::is_same<array_t, pointee_t>::value
             or std::is_same<string_t, pointee_t>::value
             or std::is_same<boolean_t, pointee_t>::value
             or std::is_same<number_integer_t, pointee_t>::value
             or std::is_same<number_unsigned_t, pointee_t>::value
             or std::is_same<number_float_t, pointee_t>::value
             , "incompatible pointer type");
         // delegate the call to get_impl_ptr<>() const
         return get_impl_ptr(static_cast<const PointerType>(nullptr));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ReferenceType , typename std::enable_if< std::is_reference< ReferenceType >::value, int >::type = 0> ReferenceType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_ref () inline
get a reference value (implicit)
Implicit reference access to the internally stored JSON value. No copies are made.
Warning
Writing data to the referee of the result yields an undefined state.
Template Parameters
ReferenceType reference type; must be a reference to array_t, object_t, string_t, boolean_t, number_integer_t, or number_float_t. Enforced by static assertion.
Returns
reference to the internally stored JSON value if the requested reference type ReferenceType fits to the JSON value; throws std::domain_error otherwise
Exceptions
std::domain_error in case passed type ReferenceType is incompatible with the stored JSON value
Constant.
{The example shows several calls to get_ref().,get_ref}
Since
version 1.1.0
Definition at line 3445 of file json.hpp.
     {
         // delegate call to get_ref_impl
         return get_ref_impl<ReferenceType>(*this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ReferenceType , typename std::enable_if< std::is_reference< ReferenceType >::value andstd::is_const< typename std::remove_reference< ReferenceType >::type >::value, int >::type = 0> ReferenceType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_ref () const inline
get a reference value (implicit)
get a reference value (implicit) Implicit reference access to the internally stored JSON value. No copies are made.
Warning
Writing data to the referee of the result yields an undefined state.
Template Parameters
ReferenceType reference type; must be a reference to array_t, object_t, string_t, boolean_t, number_integer_t, or number_float_t. Enforced by static assertion.
Returns
reference to the internally stored JSON value if the requested reference type ReferenceType fits to the JSON value; throws std::domain_error otherwise
Exceptions
std::domain_error in case passed type ReferenceType is incompatible with the stored JSON value
Constant.
{The example shows several calls to get_ref().,get_ref}
Since
version 1.1.0
Definition at line 3458 of file json.hpp.
     {
         // delegate call to get_ref_impl
         return get_ref_impl<ReferenceType>(*this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ReferenceType , typename ThisType > static ReferenceType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::get_ref_impl (ThisType & obj) inline static private
helper function to implement get_ref()
This funcion helps to implement get_ref() without code duplication for const and non-const overloads
Template Parameters
ThisType will be deduced as basic_json or const basic_json
Exceptions
std::domain_error if ReferenceType does not match underlying value type of the current JSON
Definition at line 3139 of file json.hpp.
     {
         // helper type
         using PointerType = typename std::add_pointer<ReferenceType>::type;
         // delegate the call to get_ptr<>()
         auto ptr = obj.template get_ptr<PointerType>();
         if (ptr != nullptr)
         {
             return *ptr;
         }
         throw std::domain_error("incompatible ReferenceType for get_ref, actual type is " +
                                 obj.type_name());
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert (const_iterator pos, const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & val) inline
inserts element
Inserts element val before iterator pos.
Parameters
[in] pos iterator before which the content will be inserted; may be the end() iterator
[in] val element to insert
Returns
iterator pointing to the inserted val.
Exceptions
std::domain_error if called on JSON values other than arrays; example: "cannot use insert() with string"
std::domain_error if pos is not an iterator of *this; example: "iterator does not fit current value"
Constant plus linear in the distance between pos and end of the container.
{The example shows how insert() is used.,insert}
Since
version 1.0.0
Definition at line 5547 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         // insert only works for arrays
         if (is_array())
         {
             // check if iterator pos fits to this JSON value
             if (pos.m_object != this)
             {
                 JSON_THROW(std::domain_error("iterator does not fit current value"));
             }
             // insert to array and return iterator
             iterator result(this);
             result.m_it.array_iterator = m_value.array->insert(pos.m_it.array_iterator, val);
             return result;
         }
         JSON_THROW(std::domain_error("cannot use insert() with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert (const_iterator pos, basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > && val) inline
inserts element
inserts element Inserts element val before iterator pos.
Parameters
[in] pos iterator before which the content will be inserted; may be the end() iterator
[in] val element to insert
Returns
iterator pointing to the inserted val.
Exceptions
std::domain_error if called on JSON values other than arrays; example: "cannot use insert() with string"
std::domain_error if pos is not an iterator of *this; example: "iterator does not fit current value"
Constant plus linear in the distance between pos and end of the container.
{The example shows how insert() is used.,insert}
Since
version 1.0.0
Definition at line 5571 of file json.hpp.
     {
         return insert(pos, val);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert (const_iterator pos, size_type cnt, const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & val) inline
inserts elements
Inserts cnt copies of val before iterator pos.
Parameters
[in] pos iterator before which the content will be inserted; may be the end() iterator
[in] cnt number of copies of val to insert
[in] val element to insert
Returns
iterator pointing to the first element inserted, or pos if cnt==0
Exceptions
std::domain_error if called on JSON values other than arrays; example: "cannot use insert() with string"
std::domain_error if pos is not an iterator of *this; example: "iterator does not fit current value"
Linear in cnt plus linear in the distance between pos and end of the container.
{The example shows how insert() is used.,insert__count}
Since
version 1.0.0
Definition at line 5600 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object.
     {
         // insert only works for arrays
         if (is_array())
         {
             // check if iterator pos fits to this JSON value
             if (pos.m_object != this)
             {
                 JSON_THROW(std::domain_error("iterator does not fit current value"));
             }
             // insert to array and return iterator
             iterator result(this);
             result.m_it.array_iterator = m_value.array->insert(pos.m_it.array_iterator, cnt, val);
             return result;
         }
         JSON_THROW(std::domain_error("cannot use insert() with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert (const_iterator pos, const_iterator first, const_iterator last) inline
inserts elements
Inserts elements from range [first, last) before iterator pos.
Parameters
[in] pos iterator before which the content will be inserted; may be the end() iterator
[in] first begin of the range of elements to insert
[in] last end of the range of elements to insert
Exceptions
std::domain_error if called on JSON values other than arrays; example: "cannot use insert() with string"
std::domain_error if pos is not an iterator of *this; example: "iterator does not fit current value"
std::domain_error if first and last do not belong to the same JSON value; example: "iterators do not fit"
std::domain_error if first or last are iterators into container for which insert is called; example: "passed iterators may not belong to container"
Returns
iterator pointing to the first element inserted, or pos if first==last
Linear in std::distance(first, last) plus linear in the distance between pos and end of the container.
{The example shows how insert() is used.,insert__range}
Since
version 1.0.0
Definition at line 5650 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object.
     {
         // insert only works for arrays
         if (not is_array())
         {
             JSON_THROW(std::domain_error("cannot use insert() with " + type_name()));
         }
         // check if iterator pos fits to this JSON value
         if (pos.m_object != this)
         {
             JSON_THROW(std::domain_error("iterator does not fit current value"));
         }
         // check if range iterators belong to the same JSON object
         if (first.m_object != last.m_object)
         {
             JSON_THROW(std::domain_error("iterators do not fit"));
         }
         if (first.m_object == this or last.m_object == this)
         {
             JSON_THROW(std::domain_error("passed iterators may not belong to container"));
         }
         // insert to array and return iterator
         iterator result(this);
         result.m_it.array_iterator = m_value.array->insert(
                                          pos.m_it.array_iterator,
                                          first.m_it.array_iterator,
                                          last.m_it.array_iterator);
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert (const_iterator pos, std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > ilist) inline
inserts elements
Inserts elements from initializer list ilist before iterator pos.
Parameters
[in] pos iterator before which the content will be inserted; may be the end() iterator
[in] ilist initializer list to insert the values from
Exceptions
std::domain_error if called on JSON values other than arrays; example: "cannot use insert() with string"
std::domain_error if pos is not an iterator of *this; example: "iterator does not fit current value"
Returns
iterator pointing to the first element inserted, or pos if ilist is empty
Linear in ilist.size() plus linear in the distance between pos and end of the container.
{The example shows how insert() is used.,insert__ilist}
Since
version 1.0.0
Definition at line 5708 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object.
     {
         // insert only works for arrays
         if (not is_array())
         {
             JSON_THROW(std::domain_error("cannot use insert() with " + type_name()));
         }
         // check if iterator pos fits to this JSON value
         if (pos.m_object != this)
         {
             JSON_THROW(std::domain_error("iterator does not fit current value"));
         }
         // insert to array and return iterator
         iterator result(this);
         result.m_it.array_iterator = m_value.array->insert(pos.m_it.array_iterator, ilist);
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_array () const inline noexcept
return whether value is an array
This function returns true iff the JSON value is an array.
Returns
true if type is array, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_array() for all JSON types.,is_array}
Since
version 1.0.0
Definition at line 2948 of file json.hpp.
References nlohmann::detail::array.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         return m_type == value_t::array;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_boolean () const inline noexcept
return whether value is a boolean
This function returns true iff the JSON value is a boolean.
Returns
true if type is boolean, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_boolean() for all JSON types.,is_boolean}
Since
version 1.0.0
Definition at line 2789 of file json.hpp.
References nlohmann::detail::boolean.
     {
         return m_type == value_t::boolean;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_discarded () const inline noexcept
return whether value is discarded
This function returns true iff the JSON value was discarded during parsing with a callback function (see parser_callback_t).
Note
This function will always be false for JSON values after parsing. That is, discarded values can only occur during parsing, but will be removed when inside a structured value or replaced by null in other cases.
Returns
true if type is discarded, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_discarded() for all JSON types.,is_discarded}
Since
version 1.0.0
Definition at line 2997 of file json.hpp.
References nlohmann::detail::discarded.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         return m_type == value_t::discarded;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_null () const inline noexcept
return whether value is null
This function returns true iff the JSON value is null.
Returns
true if type is null, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_null() for all JSON types.,is_null}
Since
version 1.0.0
Definition at line 2767 of file json.hpp.
References nlohmann::detail::null.
     {
         return m_type == value_t::null;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_number () const inline noexcept
return whether value is a number
This function returns true iff the JSON value is a number. This includes both integer and floating-point values.
Returns
true if type is number (regardless whether integer, unsigned integer or floating-type), false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_number() for all JSON types.,is_number}
See also
is_number_integer() – check if value is an integer or unsigned integer number
is_number_unsigned() – check if value is an unsigned integer number
is_number_float() – check if value is a floating-point number
Since
version 1.0.0
Definition at line 2819 of file json.hpp.
     {
         return is_number_integer() or is_number_float();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_number_float () const inline noexcept
return whether value is a floating-point number
This function returns true iff the JSON value is a floating-point number. This excludes integer and unsigned integer values.
Returns
true if type is a floating-point number, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_number_float() for all JSON types.,is_number_float}
See also
is_number() – check if value is number
is_number_integer() – check if value is an integer number
is_number_unsigned() – check if value is an unsigned integer number
Since
version 1.0.0
Definition at line 2904 of file json.hpp.
References nlohmann::detail::number_float.
     {
         return m_type == value_t::number_float;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_number_integer () const inline noexcept
return whether value is an integer number
This function returns true iff the JSON value is an integer or unsigned integer number. This excludes floating-point values.
Returns
true if type is an integer or unsigned integer number, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_number_integer() for all JSON types.,is_number_integer}
See also
is_number() – check if value is a number
is_number_unsigned() – check if value is an unsigned integer number
is_number_float() – check if value is a floating-point number
Since
version 1.0.0
Definition at line 2848 of file json.hpp.
References nlohmann::detail::number_integer, and nlohmann::detail::number_unsigned.
     {
         return m_type == value_t::number_integer or m_type == value_t::number_unsigned;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_number_unsigned () const inline noexcept
return whether value is an unsigned integer number
This function returns true iff the JSON value is an unsigned integer number. This excludes floating-point and (signed) integer values.
Returns
true if type is an unsigned integer number, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_number_unsigned() for all JSON types.,is_number_unsigned}
See also
is_number() – check if value is a number
is_number_integer() – check if value is an integer or unsigned integer number
is_number_float() – check if value is a floating-point number
Since
version 2.0.0
Definition at line 2876 of file json.hpp.
References nlohmann::detail::number_unsigned.
     {
         return m_type == value_t::number_unsigned;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_object () const inline noexcept
return whether value is an object
This function returns true iff the JSON value is an object.
Returns
true if type is object, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_object() for all JSON types.,is_object}
Since
version 1.0.0
Definition at line 2926 of file json.hpp.
References nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::unflatten().
     {
         return m_type == value_t::object;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_primitive () const inline noexcept
return whether type is primitive
This function returns true iff the JSON type is primitive (string, number, boolean, or null).
Returns
true if type is primitive (string, number, boolean, or null), false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_primitive() for all JSON types.,is_primitive}
See also
is_structured() – returns whether JSON value is structured
is_null() – returns whether JSON value is null
is_string() – returns whether JSON value is a string
is_boolean() – returns whether JSON value is a boolean
is_number() – returns whether JSON value is a number
Since
version 1.0.0
Definition at line 2718 of file json.hpp.
     {
         return is_null() or is_string() or is_boolean() or is_number();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_string () const inline noexcept
return whether value is a string
This function returns true iff the JSON value is a string.
Returns
true if type is string, false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_string() for all JSON types.,is_string}
Since
version 1.0.0
Definition at line 2970 of file json.hpp.
References nlohmann::detail::string.
     {
         return m_type == value_t::string;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_structured () const inline noexcept
return whether type is structured
This function returns true iff the JSON type is structured (array or object).
Returns
true if type is structured (array or object), false otherwise.
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies is_structured() for all JSON types.,is_structured}
See also
is_primitive() – returns whether value is primitive
is_array() – returns whether value is an array
is_object() – returns whether value is an object
Since
version 1.0.0
Definition at line 2745 of file json.hpp.
     {
         return is_array() or is_object();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static iteration_proxy<iterator> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iterator_wrapper (reference cont) inline static
wrapper to access iterator member functions in range-based for
This function allows to access iterator::key() and iterator::value() during range-based for loops. In these loops, a reference to the JSON values is returned, so there is no access to the underlying iterator.
Note
The name of this function is not yet final and may change in the future.
Definition at line 4942 of file json.hpp.
     {
         return iteration_proxy<iterator>(cont);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static iteration_proxy<const_iterator> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iterator_wrapper (const_reference cont) inline static
wrapper to access iterator member functions in range-based for
This function allows to access iterator::key() and iterator::value() during range-based for loops. In these loops, a reference to the JSON values is returned, so there is no access to the underlying iterator.
Note
The name of this function is not yet final and may change in the future.
Definition at line 4950 of file json.hpp.
     {
         return iteration_proxy<const_iterator>(cont);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> size_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::max_size () const inline noexcept
returns the maximum possible number of elements
Returns the maximum number of elements a JSON value is able to hold due to system or library implementation limitations, i.e. std::distance(begin(), end()) for the JSON value.
Returns
The return value depends on the different types and is defined as follows:
Value type return value
null 0 (same as size())
boolean 1 (same as size())
string 1 (same as size())
number 1 (same as size())
object result of function object_t::max_size()
array result of function array_t::max_size()
Constant, as long as array_t and object_t satisfy the Container concept; that is, their max_size() functions have constant complexity.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of returning b.size() where b is the largest possible JSON value.
{The following code calls max_size() on the different value types. Note the output is implementation specific.,max_size}
See also
size() – returns the number of elements
Since
version 1.0.0
Definition at line 5136 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
     {
         switch (m_type)
         {
             case value_t::array:
             {
                 // delegate call to array_t::max_size()
                 return m_value.array->max_size();
             }
             case value_t::object:
             {
                 // delegate call to object_t::max_size()
                 return m_value.object->max_size();
             }
             default:
             {
                 // all other types have max_size() == size()
                 return size();
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::meta () inline static
returns version information on the library
This function returns a JSON object with information about the library, including the version number and information on the platform and compiler.
Returns
JSON object holding version information
key description
compiler Information on the used compiler. It is an object with the following keys: c++ (the used C++ standard), family (the compiler family; possible values are clang, icc, gcc, ilecpp, msvc, pgcpp, sunpro, and unknown), and version (the compiler version).
copyright The copyright line for the library as string.
name The name of the library as string.
platform The used platform as string. Possible values are win32, linux, apple, unix, and unknown.
url The URL of the project as string.
version The version of the library. It is an object with the following keys: major, minor, and patch as defined by Semantic Versioning, and string (the version string).
{The following code shows an example output of the meta() function.,meta}
Constant.
Since
2.1.0
Definition at line 1129 of file json.hpp.
     {
         basic_json result;
         result["copyright"] = "(C) 2013-2017 Niels Lohmann";
         result["name"] = "JSON for Modern C++";
         result["url"] = "https://github.com/nlohmann/json";
         result["version"] =
         {
             {"string", "2.1.0"},
             {"major", 2},
             {"minor", 1},
             {"patch", 0},
         };
 #ifdef _WIN32
         result["platform"] = "win32";
 #elif defined __linux__
         result["platform"] = "linux";
 #elif defined __APPLE__
         result["platform"] = "apple";
 #elif defined __unix__
         result["platform"] = "unix";
 #else
         result["platform"] = "unknown";
 #endif
 #if defined(__clang__)
         result["compiler"] = {{"family", "clang"}, {"version", __clang_version__}};
 #elif defined(__ICC) || defined(__INTEL_COMPILER)
         result["compiler"] = {{"family", "icc"}, {"version", __INTEL_COMPILER}};
 #elif defined(__GNUC__) || defined(__GNUG__)
         result["compiler"] = {{"family", "gcc"}, {"version", std::to_string(__GNUC__) + "." + std::to_string(__GNUC_MINOR__) + "." + std::to_string(__GNUC_PATCHLEVEL__)}};
 #elif defined(__HP_cc) || defined(__HP_aCC)
         result["compiler"] = "hp"
 #elif defined(__IBMCPP__)
         result["compiler"] = {{"family", "ilecpp"}, {"version", __IBMCPP__}};
 #elif defined(_MSC_VER)
         result["compiler"] = {{"family", "msvc"}, {"version", _MSC_VER}};
 #elif defined(__PGI)
         result["compiler"] = {{"family", "pgcpp"}, {"version", __PGI}};
 #elif defined(__SUNPRO_CC)
         result["compiler"] = {{"family", "sunpro"}, {"version", __SUNPRO_CC}};
 #else
         result["compiler"] = {{"family", "unknown"}, {"version", "unknown"}};
 #endif
 #ifdef __cplusplus
         result["compiler"]["c++"] = std::to_string(__cplusplus);
 #else
         result["compiler"]["c++"] = "unknown";
 #endif
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object (std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > init = std::initializer_list<basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >>()) inline static
explicitly create an object from an initializer list
Creates a JSON object value from a given initializer list. The initializer lists elements must be pairs, and their first elements must be strings. If the initializer list is empty, the empty object {} is created.
Note
This function is only added for symmetry reasons. In contrast to the related function array(std::initializer_list<basic_json>), there are no cases which can only be expressed by this function. That is, any initializer list init can also be passed to the initializer list constructor basic_json(std::initializer_list<basic_json>, bool, value_t).
Parameters
[in] init initializer list to create an object from (optional)
Returns
JSON object value
Exceptions
std::domain_error if init is not a pair whose first elements are strings; thrown by basic_json(std::initializer_list<basic_json>, bool, value_t)
Linear in the size of init.
{The following code shows an example for the object function.,object}
See also
basic_json(std::initializer_list<basic_json>, bool, value_t) – create a JSON value from an initializer list
array(std::initializer_list<basic_json>) – create a JSON array value from an initializer list
Since
version 1.0.0
Definition at line 2204 of file json.hpp.
References nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[]().
     {
         return basic_json(init, false, value_t::object);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator value_t () const inline noexcept
return the type of the JSON value (implicit)
Implicitly return the type of the JSON value as a value from the value_t enumeration.
Returns
the type of the JSON value
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies the value_t operator for all JSON types.,operator__value_t}
Since
version 1.0.0
Definition at line 3020 of file json.hpp.
     {
         return m_type;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename ValueType , typename std::enable_if< not std::is_pointer< ValueType >::value andnot std::is_same< ValueType, typename string_t::value_type >::valueand not std::is_same< ValueType, std::initializer_list< typename string_t::value_type >>::value, int >::type = 0> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator ValueType () const inline
get a value (implicit)
Implicit type conversion between the JSON value and a compatible value. The call is realized by calling get() const.
Template Parameters
ValueType non-pointer type compatible to the JSON value, for instance int for JSON integer numbers, bool for JSON booleans, or std::vector types for JSON arrays. The character type of string_t as well as an initializer list of this type is excluded to avoid ambiguities as these types implicitly convert to std::string.
Returns
copy of the JSON value, converted to type ValueType
Exceptions
std::domain_error in case passed type ValueType is incompatible to JSON, thrown by get() const
Linear in the size of the JSON value.
{The example below shows several conversions from JSON values to other types. There a few things to note: (1) Floating-point numbers can be converted to integers\, (2) A JSON array can be converted to a standard std::vector<short>\, (3) A JSON object can be converted to C++ associative containers such as std::unordered_map<std::string\, json>.,operator__ValueType}
Since
version 1.0.0
Definition at line 3499 of file json.hpp.
     {
         // delegate the call to get<>() const
         return get<ValueType>();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator+= (basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > && val) inline
add an object to an array
add an object to an array Appends the given element val to the end of the JSON value. If the function is called on a JSON null value, an empty array is created before appending val.
Parameters
[in] val the value to add to the JSON array
Exceptions
std::domain_error when called on a type other than JSON array or null; example: "cannot use push_back() with number"
Amortized constant.
{The example shows how push_back() and += can be used to add elements to a JSON array. Note how the null value was silently converted to a JSON array.,push_back}
Since
version 1.0.0
Definition at line 5291 of file json.hpp.
     {
         push_back(std::move(val));
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator+= (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & val) inline
add an object to an array
add an object to an array Appends the given element val to the end of the JSON value. If the function is called on a JSON null value, an empty array is created before appending val.
Parameters
[in] val the value to add to the JSON array
Exceptions
std::domain_error when called on a type other than JSON array or null; example: "cannot use push_back() with number"
Amortized constant.
{The example shows how push_back() and += can be used to add elements to a JSON array. Note how the null value was silently converted to a JSON array.,push_back}
Since
version 1.0.0
Definition at line 5325 of file json.hpp.
     {
         push_back(val);
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator+= (const typename object_t::value_type & val) inline
add an object to an object
add an object to an object Inserts the given element val to the JSON object. If the function is called on a JSON null value, an empty object is created before inserting val.
Parameters
[in] val the value to add to the JSON object
Exceptions
std::domain_error when called on a type other than JSON object or null; example: "cannot use push_back() with number"
Logarithmic in the size of the container, O(log(size())).
{The example shows how push_back() and += can be used to add elements to a JSON object. Note how the null value was silently converted to a JSON object.,push_back__object_t__value}
Since
version 1.0.0
Definition at line 5375 of file json.hpp.
     {
         push_back(val);
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator+= (std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > init) inline
add an object to an object
add an object to an object This function allows to use push_back with an initializer list. In case
the current value is an object,
the initializer list init contains only two elements, and
the first element of init is a string,
init is converted into an object element and added using push_back(const typename object_t::value_type&). Otherwise, init is converted to a JSON value and added using push_back(basic_json&&).
Parameters
init an initializer list
Linear in the size of the initializer list init.
Note
This function is required to resolve an ambiguous overload error, because pairs like {"key", "value"} can be both interpreted as object_t::value_type or std::initializer_list<basic_json>, see https://github.com/nlohmann/json/issues/235 for more information.
{The example shows how initializer lists are treated as objects when possible.,push_back__initializer_list}
Definition at line 5423 of file json.hpp.
     {
         push_back(init);
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator= (basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > other) inline noexcept
copy assignment
Copy assignment operator. Copies a JSON value via the "copy and swap" strategy: It is expressed in terms of the copy constructor, destructor, and the swap() member function.
Parameters
[in] other value to copy from
Linear.
This function helps basic_json satisfying the Container requirements:
The complexity is linear.
{The code below shows and example for the copy assignment. It creates a copy of value a which is then swapped with b. Finally\, the copy of a (which is the null value after the swap) is destroyed.,basic_json__copyassignment}
Since
version 1.0.0
Definition at line 2541 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::assert_invariant().
     {
         // check that passed value is valid
         other.assert_invariant();
         using std::swap;
         swap(m_type, other.m_type);
         swap(m_value, other.m_value);
         assert_invariant();
         return *this;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (size_type idx) inline
access specified array element
Returns a reference to the element at specified location idx.
Note
If idx is beyond the range of the array (i.e., idx >= size()), then the array is silently filled up with null values to make idx a valid reference to the last stored element.
Parameters
[in] idx index of the element to access
Returns
reference to the element at index idx
Exceptions
std::domain_error if JSON is not an array or null; example: "cannot use operator[] with string"
Constant if idx is in the range of the array. Otherwise linear in idx - size().
{The example below shows how array elements can be read and written using [] operator. Note the addition of null values.,operatorarray__size_type}
Since
version 1.0.0
Definition at line 3721 of file json.hpp.
References nlohmann::detail::array, and JSON_THROW.
     {
         // implicitly convert null value to an empty array
         if (is_null())
         {
             m_type = value_t::array;
             m_value.array = create<array_t>();
             assert_invariant();
         }
         // operator[] only works for arrays
         if (is_array())
         {
             // fill up array with null values if given idx is outside range
             if (idx >= m_value.array->size())
             {
                 m_value.array->insert(m_value.array->end(),
                                       idx - m_value.array->size() + 1,
                                       basic_json());
             }
             return m_value.array->operator[](idx);
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (size_type idx) const inline
access specified array element
Returns a const reference to the element at specified location idx.
Parameters
[in] idx index of the element to access
Returns
const reference to the element at index idx
Exceptions
std::domain_error if JSON is not an array; example: "cannot use operator[] with null"
Constant.
{The example below shows how array elements can be read using the [] operator.,operatorarray__size_type_const}
Since
version 1.0.0
Definition at line 3767 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::array(), and JSON_THROW.
     {
         // const operator[] only works for arrays
         if (is_array())
         {
             return m_value.array->operator[](idx);
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (const typename object_t::key_type & key) inline
access specified object element
Returns a reference to the element at with specified key key.
Note
If key is not found in the object, then it is silently added to the object and filled with a null value to make key a valid reference. In case the value was null before, it is converted to an object.
Parameters
[in] key key of the element to access
Returns
reference to the element at key key
Exceptions
std::domain_error if JSON is not an object or null; example: "cannot use operator[] with string"
Logarithmic in the size of the container.
{The example below shows how object elements can be read and written using the [] operator.,operatorarray__key_type}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3805 of file json.hpp.
References JSON_THROW, and nlohmann::detail::object.
     {
         // implicitly convert null value to an empty object
         if (is_null())
         {
             m_type = value_t::object;
             m_value.object = create<object_t>();
             assert_invariant();
         }
         // operator[] only works for objects
         if (is_object())
         {
             return m_value.object->operator[](key);
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (const typename object_t::key_type & key) const inline
read-only access specified object element
Returns a const reference to the element at with specified key key. No bounds checking is performed.
Warning
If the element with key key does not exist, the behavior is undefined.
Parameters
[in] key key of the element to access
Returns
const reference to the element at key key
Precondition
The element with key key must exist. This precondition is enforced with an assertion.
Exceptions
std::domain_error if JSON is not an object; example: "cannot use operator[] with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be read using the [] operator.,operatorarray__key_type_const}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3854 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), JSON_THROW, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object().
     {
         // const operator[] only works for objects
         if (is_object())
         {
             assert(m_value.object->find(key) != m_value.object->end());
             return m_value.object->find(key)->second;
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T , std::size_t n> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (T *(&) key[n]) inline
access specified object element
Returns a reference to the element at with specified key key.
Note
If key is not found in the object, then it is silently added to the object and filled with a null value to make key a valid reference. In case the value was null before, it is converted to an object.
Parameters
[in] key key of the element to access
Returns
reference to the element at key key
Exceptions
std::domain_error if JSON is not an object or null; example: "cannot use operator[] with string"
Logarithmic in the size of the container.
{The example below shows how object elements can be read and written using the [] operator.,operatorarray__key_type}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3894 of file json.hpp.
     {
         return operator[](static_cast<const T>(key));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T , std::size_t n> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (T *(&) key[n]) const inline
read-only access specified object element
Returns a const reference to the element at with specified key key. No bounds checking is performed.
Warning
If the element with key key does not exist, the behavior is undefined.
Note
This function is required for compatibility reasons with Clang.
Parameters
[in] key key of the element to access
Returns
const reference to the element at key key
Exceptions
std::domain_error if JSON is not an object; example: "cannot use operator[] with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be read using the [] operator.,operatorarray__key_type_const}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.0.0
Definition at line 3929 of file json.hpp.
     {
         return operator[](static_cast<const T>(key));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T > reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (T * key) inline
access specified object element
Returns a reference to the element at with specified key key.
Note
If key is not found in the object, then it is silently added to the object and filled with a null value to make key a valid reference. In case the value was null before, it is converted to an object.
Parameters
[in] key key of the element to access
Returns
reference to the element at key key
Exceptions
std::domain_error if JSON is not an object or null; example: "cannot use operator[] with string"
Logarithmic in the size of the container.
{The example below shows how object elements can be read and written using the [] operator.,operatorarray__key_type}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.1.0
Definition at line 3962 of file json.hpp.
References JSON_THROW, and nlohmann::detail::object.
     {
         // implicitly convert null to object
         if (is_null())
         {
             m_type = value_t::object;
             m_value = value_t::object;
             assert_invariant();
         }
         // at only works for objects
         if (is_object())
         {
             return m_value.object->operator[](key);
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename T > const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (T * key) const inline
read-only access specified object element
Returns a const reference to the element at with specified key key. No bounds checking is performed.
Warning
If the element with key key does not exist, the behavior is undefined.
Parameters
[in] key key of the element to access
Returns
const reference to the element at key key
Precondition
The element with key key must exist. This precondition is enforced with an assertion.
Exceptions
std::domain_error if JSON is not an object; example: "cannot use operator[] with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be read using the [] operator.,operatorarray__key_type_const}
See also
at(const typename object_t::key_type&) for access by reference with range checking
value() for access by value with a default value
Since
version 1.1.0
Definition at line 4012 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), JSON_THROW, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::object().
     {
         // at only works for objects
         if (is_object())
         {
             assert(m_value.object->find(key) != m_value.object->end());
             return m_value.object->find(key)->second;
         }
         JSON_THROW(std::domain_error("cannot use operator[] with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (const json_pointer & ptr) inline
access specified element via JSON Pointer
Uses a JSON pointer to retrieve a reference to the respective JSON value. No bound checking is performed. Similar to operator[](const typename object_t::key_type&), null values are created in arrays and objects if necessary.
In particular:
If the JSON pointer points to an object key that does not exist, it is created an filled with a null value before a reference to it is returned.
If the JSON pointer points to an array index that does not exist, it is created an filled with a null value before a reference to it is returned. All indices between the current maximum and the given index are also filled with null.
The special value - is treated as a synonym for the index past the end.
Parameters
[in] ptr a JSON pointer
Returns
reference to the element pointed to by ptr
Constant.
Exceptions
std::out_of_range if the JSON pointer can not be resolved
std::domain_error if an array index begins with '0'
std::invalid_argument if an array index was not a number
{The behavior is shown in the example.,operatorjson_pointer}
Since
version 2.0.0
Definition at line 11978 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_unchecked().
     {
         return ptr.get_unchecked(this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[] (const json_pointer & ptr) const inline
access specified element via JSON Pointer
Uses a JSON pointer to retrieve a reference to the respective JSON value. No bound checking is performed. The function does not change the JSON value; no null values are created. In particular, the the special value - yields an exception.
Parameters
[in] ptr JSON pointer to the desired element
Returns
const reference to the element pointed to by ptr
Constant.
Exceptions
std::out_of_range if the JSON pointer can not be resolved
std::domain_error if an array index begins with '0'
std::invalid_argument if an array index was not a number
{The behavior is shown in the example.,operatorjson_pointer_const}
Since
version 2.0.0
Definition at line 12005 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_unchecked().
     {
         return ptr.get_unchecked(this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class T , std::size_t N> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (T(&) array[N], const parser_callback_t cb = nullptr) inline static
deserialize from an array
This function reads from an array of 1-byte values.
Precondition
Each element of the container has a size of 1 byte. Violating this precondition yields undefined behavior. This precondition is enforced with a static assertion.
Parameters
[in] array array to read from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
{The example below demonstrates the parse() function reading from an array.,parse__array__parser_callback_t}
Since
version 2.0.3
Definition at line 6328 of file json.hpp.
References nlohmann::detail::array.
Referenced by operator""_json().
     {
         // delegate the call to the iterator-range parse overload
         return parse(std::begin(array), std::end(array), cb);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename CharT , typename std::enable_if< std::is_pointer< CharT >::value andstd::is_integral< typename std::remove_pointer< CharT >::type >::value andsizeof(typename std::remove_pointer< CharT >::type)==1, int >::type = 0> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (const CharT s, const parser_callback_t cb = nullptr) inline static
deserialize from string literal
Template Parameters
CharT character/literal type with size of 1 byte
Parameters
[in] s string literal to read a serialized JSON value from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
String containers like std::string or string_t can be parsed with parse(const ContiguousContainer&, const parser_callback_t)
{The example below demonstrates the parse() function with and without callback function.,parse__string__parser_callback_t}
See also
parse(std::istream&, const parser_callback_t) for a version that reads from an input stream
Since
version 1.0.0 (originally for string_t)
Definition at line 6366 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         return parser(reinterpret_cast<const char*>(s), cb).parse();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (std::istream & i, const parser_callback_t cb = nullptr) inline static
deserialize from stream
Parameters
[in,out] i stream to read a serialized JSON value from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
{The example below demonstrates the parse() function with and without callback function.,parse__istream__parser_callback_t}
See also
parse(const CharT, const parser_callback_t) for a version that reads from a string
Since
version 1.0.0
Definition at line 6396 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         return parser(i, cb).parse();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (std::istream && i, const parser_callback_t cb = nullptr) inline static
deserialize from stream
Parameters
[in,out] i stream to read a serialized JSON value from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
{The example below demonstrates the parse() function with and without callback function.,parse__istream__parser_callback_t}
See also
parse(const CharT, const parser_callback_t) for a version that reads from a string
Since
version 1.0.0
Definition at line 6405 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         return parser(i, cb).parse();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class IteratorType , typename std::enable_if< std::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< IteratorType >::iterator_category >::value, int >::type = 0> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (IteratorType first, IteratorType last, const parser_callback_t cb = nullptr) inline static
deserialize from an iterator range with contiguous storage
This function reads from an iterator range of a container with contiguous storage of 1-byte values. Compatible container types include std::vector, std::string, std::array, std::valarray, and std::initializer_list. Furthermore, C-style arrays can be used with std::begin()/std::end(). User-defined containers can be used as long as they implement random-access iterators and a contiguous storage.
Precondition
The iterator range is contiguous. Violating this precondition yields undefined behavior. This precondition is enforced with an assertion.
Each element in the range has a size of 1 byte. Violating this precondition yields undefined behavior. This precondition is enforced with a static assertion.
Warning
There is no way to enforce all preconditions at compile-time. If the function is called with noncompliant iterators and with assertions switched off, the behavior is undefined and will most likely yield segmentation violation.
Template Parameters
IteratorType iterator of container with contiguous storage
Parameters
[in] first begin of the range to parse (included)
[in] last end of the range to parse (excluded)
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
{The example below demonstrates the parse() function reading from an iterator range.,parse__iteratortype__parser_callback_t}
Since
version 2.0.3
Definition at line 6456 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse().
     {
         // assertion to check that the iterator range is indeed contiguous,
         // see http://stackoverflow.com/a/35008842/266378 for more discussion
         assert(std::accumulate(first, last, std::pair<bool, int>(true, 0),
                                [&first](std::pair<bool, int> res, decltype(*first) val)
         {
             res.first &= (val == *(std::next(std::addressof(*first), res.second++)));
             return res;
         }).first);
         // assertion to check that each element is 1 byte long
         static_assert(sizeof(typename std::iterator_traits<IteratorType>::value_type) == 1,
                       "each element in the iterator range must have the size of 1 byte");
         // if iterator range is empty, create a parser with an empty string
         // to generate "unexpected EOF" error message
         if (std::distance(first, last) <= 0)
         {
             return parser("").parse();
         }
         return parser(first, last, cb).parse();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class ContiguousContainer , typename std::enable_if< not std::is_pointer< ContiguousContainer >::value andstd::is_base_of< std::random_access_iterator_tag, typename std::iterator_traits< decltype(std::begin(std::declval< ContiguousContainer const >()))>::iterator_category >::value, int >::type = 0> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse (const ContiguousContainer & c, const parser_callback_t cb = nullptr) inline static
deserialize from a container with contiguous storage
This function reads from a container with contiguous storage of 1-byte values. Compatible container types include std::vector, std::string, std::array, and std::initializer_list. User-defined containers can be used as long as they implement random-access iterators and a contiguous storage.
Precondition
The container storage is contiguous. Violating this precondition yields undefined behavior. This precondition is enforced with an assertion.
Each element of the container has a size of 1 byte. Violating this precondition yields undefined behavior. This precondition is enforced with a static assertion.
Warning
There is no way to enforce all preconditions at compile-time. If the function is called with a noncompliant container and with assertions switched off, the behavior is undefined and will most likely yield segmentation violation.
Template Parameters
ContiguousContainer container type with contiguous storage
Parameters
[in] c container to read from
[in] cb a parser callback function of type parser_callback_t which is used to control the deserialization by filtering unwanted values (optional)
Returns
result of the deserialization
Linear in the length of the input. The parser is a predictive LL(1) parser. The complexity can be higher if the parser callback function cb has a super-linear complexity.
Note
A UTF-8 byte order mark is silently ignored.
{The example below demonstrates the parse() function reading from a contiguous container.,parse__contiguouscontainer__parser_callback_t}
Since
version 2.0.3
Definition at line 6528 of file json.hpp.
     {
         // delegate the call to the iterator-range parse overload
         return parse(std::begin(c), std::end(c), cb);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & json_patch) const inline
applies a JSON patch
JSON Patch defines a JSON document structure for expressing a sequence of operations to apply to a JSON) document. With this function, a JSON Patch is applied to the current JSON value by executing all operations from the patch.
Parameters
[in] json_patch JSON patch document
Returns
patched document
Note
The application of a patch is atomic: Either all operations succeed and the patched document is returned or an exception is thrown. In any case, the original value is not changed: the patch is applied to a copy of the value.
Exceptions
std::out_of_range if a JSON pointer inside the patch could not be resolved successfully in the current JSON value; example: "key baz not found"
invalid_argument if the JSON patch is malformed (e.g., mandatory attributes are missing); example: "operation add must have member path"
Linear in the size of the JSON value and the length of the JSON patch. As usually only a fraction of the JSON value is affected by the patch, the complexity can usually be neglected.
{The following code shows how a JSON patch is applied to a value.,patch}
See also
diff – create a JSON patch by comparing two JSON values
RFC 6902 (JSON Patch)
RFC 6901 (JSON Pointer)
Since
version 2.0.0
Definition at line 12166 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::erase(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_array(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::is_root(), JSON_CATCH, JSON_THROW, JSON_TRY, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_type, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, nlohmann::detail::null, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::pop_back(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::size(), nlohmann::detail::string, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::top().
     {
         // make a working copy to apply the patch to
         basic_json result = *this;
         // the valid JSON Patch operations
         enum class patch_operations {add, remove, replace, move, copy, test, invalid};
         const auto get_op = [](const std::string op)
         {
             if (op == "add")
             {
                 return patch_operations::add;
             }
             if (op == "remove")
             {
                 return patch_operations::remove;
             }
             if (op == "replace")
             {
                 return patch_operations::replace;
             }
             if (op == "move")
             {
                 return patch_operations::move;
             }
             if (op == "copy")
             {
                 return patch_operations::copy;
             }
             if (op == "test")
             {
                 return patch_operations::test;
             }
             return patch_operations::invalid;
         };
         // wrapper for "add" operation; add value at ptr
         const auto operation_add = [&result](json_pointer & ptr, basic_json val)
         {
             // adding to the root of the target document means replacing it
             if (ptr.is_root())
             {
                 result = val;
             }
             else
             {
                 // make sure the top element of the pointer exists
                 json_pointer top_pointer = ptr.top();
                 if (top_pointer != ptr)
                 {
                     result.at(top_pointer);
                 }
                 // get reference to parent of JSON pointer ptr
                 const auto last_path = ptr.pop_back();
                 basic_json& parent = result[ptr];
                 switch (parent.m_type)
                 {
                     case value_t::null:
                     case value_t::object:
                     {
                         // use operator[] to add value
                         parent[last_path] = val;
                         break;
                     }
                     case value_t::array:
                     {
                         if (last_path == "-")
{
                             // special case: append to back
                             parent.push_back(val);
                         }
                         else
{
                             const auto idx = std::stoi(last_path);
                             if (static_cast<size_type>(idx) > parent.size())
{
                                 // avoid undefined behavior
                                 JSON_THROW(std::out_of_range("array index " + std::to_string(idx) + " is out of range"));
                             }
                             else
{
                                 // default case: insert add offset
                                 parent.insert(parent.begin() + static_cast<difference_type>(idx), val);
                             }
                         }
                         break;
                     }
                     default:
                     {
                         // if there exists a parent it cannot be primitive
                         assert(false);  // LCOV_EXCL_LINE
                     }
                 }
             }
         };
         // wrapper for "remove" operation; remove value at ptr
         const auto operation_remove = [&result](json_pointer & ptr)
         {
             // get reference to parent of JSON pointer ptr
             const auto last_path = ptr.pop_back();
             basic_json& parent = result.at(ptr);
             // remove child
             if (parent.is_object())
             {
                 // perform range check
                 auto it = parent.find(last_path);
                 if (it != parent.end())
                 {
                     parent.erase(it);
                 }
                 else
                 {
                     JSON_THROW(std::out_of_range("key '" + last_path + "' not found"));
                 }
             }
             else if (parent.is_array())
             {
                 // note erase performs range check
                 parent.erase(static_cast<size_type>(std::stoi(last_path)));
             }
         };
         // type check
         if (not json_patch.is_array())
         {
             // a JSON patch must be an array of objects
             JSON_THROW(std::invalid_argument("JSON patch must be an array of objects"));
         }
         // iterate and apply the operations
         for (const auto& val : json_patch)
         {
             // wrapper to get a value for an operation
             const auto get_value = [&val](const std::string & op,
                                           const std::string & member,
                                           bool string_type) -> basic_json&
             {
                 // find value
                 auto it = val.m_value.object->find(member);
                 // context-sensitive error message
                 const auto error_msg = (op == "op") ? "operation" : "operation '" + op + "'";
                 // check if desired value is present
                 if (it == val.m_value.object->end())
                 {
                     JSON_THROW(std::invalid_argument(error_msg + " must have member '" + member + "'"));
                 }
                 // check if result is of type string
                 if (string_type and not it->second.is_string())
                 {
                     JSON_THROW(std::invalid_argument(error_msg + " must have string member '" + member + "'"));
                 }
                 // no error: return value
                 return it->second;
             };
             // type check
             if (not val.is_object())
             {
                 JSON_THROW(std::invalid_argument("JSON patch must be an array of objects"));
             }
             // collect mandatory members
             const std::string op = get_value("op", "op", true);
             const std::string path = get_value(op, "path", true);
             json_pointer ptr(path);
             switch (get_op(op))
             {
                 case patch_operations::add:
                 {
                     operation_add(ptr, get_value("add", "value", false));
                     break;
                 }
                 case patch_operations::remove:
                 {
                     operation_remove(ptr);
                     break;
                 }
                 case patch_operations::replace:
                 {
                     // the "path" location must exist - use at()
                     result.at(ptr) = get_value("replace", "value", false);
                     break;
                 }
                 case patch_operations::move:
                 {
                     const std::string from_path = get_value("move", "from", true);
                     json_pointer from_ptr(from_path);
                     // the "from" location must exist - use at()
                     basic_json v = result.at(from_ptr);
                     // The move operation is functionally identical to a
                     // "remove" operation on the "from" location, followed
                     // immediately by an "add" operation at the target
                     // location with the value that was just removed.
                     operation_remove(from_ptr);
                     operation_add(ptr, v);
                     break;
                 }
                 case patch_operations::copy:
                 {
                     const std::string from_path = get_value("copy", "from", true);;
                     const json_pointer from_ptr(from_path);
                     // the "from" location must exist - use at()
                     result[ptr] = result.at(from_ptr);
                     break;
                 }
                 case patch_operations::test:
                 {
                     bool success = false;
                     JSON_TRY
                     {
                         // check if "value" matches the one at "path"
                         // the "path" location must exist - use at()
                         success = (result.at(ptr) == get_value("test", "value", false));
                     }
                     JSON_CATCH (std::out_of_range&)
                     {
                         // ignore out of range errors: success remains false
                     }
                     // throw an exception if test fails
                     if (not success)
                     {
                         JSON_THROW(std::domain_error("unsuccessful: " + val.dump()));
                     }
                     break;
                 }
                 case patch_operations::invalid:
                 {
                     // op must be "add", "remove", "replace", "move", "copy", or
                     // "test"
                     JSON_THROW(std::invalid_argument("operation value '" + op + "' is invalid"));
                 }
             }
         }
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back (basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > && val) inline
add an object to an array
Appends the given element val to the end of the JSON value. If the function is called on a JSON null value, an empty array is created before appending val.
Parameters
[in] val the value to add to the JSON array
Exceptions
std::domain_error when called on a type other than JSON array or null; example: "cannot use push_back() with number"
Amortized constant.
{The example shows how push_back() and += can be used to add elements to a JSON array. Note how the null value was silently converted to a JSON array.,push_back}
Since
version 1.0.0
Definition at line 5265 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::null.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_cbor_internal(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::from_msgpack_internal(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         // push_back only works for null objects or arrays
         if (not(is_null() or is_array()))
         {
             JSON_THROW(std::domain_error("cannot use push_back() with " + type_name()));
         }
         // transform null object into an array
         if (is_null())
         {
             m_type = value_t::array;
             m_value = value_t::array;
             assert_invariant();
         }
         // add element to array (move semantics)
         m_value.array->push_back(std::move(val));
         // invalidate object
         val.m_type = value_t::null;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & val) inline
add an object to an array
add an object to an array Appends the given element val to the end of the JSON value. If the function is called on a JSON null value, an empty array is created before appending val.
Parameters
[in] val the value to add to the JSON array
Exceptions
std::domain_error when called on a type other than JSON array or null; example: "cannot use push_back() with number"
Amortized constant.
{The example shows how push_back() and += can be used to add elements to a JSON array. Note how the null value was silently converted to a JSON array.,push_back}
Since
version 1.0.0
Definition at line 5301 of file json.hpp.
References nlohmann::detail::array, and JSON_THROW.
     {
         // push_back only works for null objects or arrays
         if (not(is_null() or is_array()))
         {
             JSON_THROW(std::domain_error("cannot use push_back() with " + type_name()));
         }
         // transform null object into an array
         if (is_null())
         {
             m_type = value_t::array;
             m_value = value_t::array;
             assert_invariant();
         }
         // add element to array
         m_value.array->push_back(val);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back (const typename object_t::value_type & val) inline
add an object to an object
Inserts the given element val to the JSON object. If the function is called on a JSON null value, an empty object is created before inserting val.
Parameters
[in] val the value to add to the JSON object
Exceptions
std::domain_error when called on a type other than JSON object or null; example: "cannot use push_back() with number"
Logarithmic in the size of the container, O(log(size())).
{The example shows how push_back() and += can be used to add elements to a JSON object. Note how the null value was silently converted to a JSON object.,push_back__object_t__value}
Since
version 1.0.0
Definition at line 5351 of file json.hpp.
References JSON_THROW, and nlohmann::detail::object.
     {
         // push_back only works for null objects or objects
         if (not(is_null() or is_object()))
         {
             JSON_THROW(std::domain_error("cannot use push_back() with " + type_name()));
         }
         // transform null object into an object
         if (is_null())
         {
             m_type = value_t::object;
             m_value = value_t::object;
             assert_invariant();
         }
         // add element to array
         m_value.object->insert(val);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::push_back (std::initializer_list< basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > > init) inline
add an object to an object
This function allows to use push_back with an initializer list. In case
the current value is an object,
the initializer list init contains only two elements, and
the first element of init is a string,
init is converted into an object element and added using push_back(const typename object_t::value_type&). Otherwise, init is converted to a JSON value and added using push_back(basic_json&&).
Parameters
init an initializer list
Linear in the size of the initializer list init.
Note
This function is required to resolve an ambiguous overload error, because pairs like {"key", "value"} can be both interpreted as object_t::value_type or std::initializer_list<basic_json>, see https://github.com/nlohmann/json/issues/235 for more information.
{The example shows how initializer lists are treated as objects when possible.,push_back__initializer_list}
Definition at line 5406 of file json.hpp.
     {
         if (is_object() and init.size() == 2 and init.begin()->is_string())
         {
             const string_t key = *init.begin();
             push_back(typename object_t::value_type(key, *(init.begin() + 1)));
         }
         else
         {
             push_back(basic_json(init));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::rbegin () inline noexcept
returns an iterator to the reverse-beginning
Returns an iterator to the reverse-beginning; that is, the last element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of reverse_iterator(end()).
{The following code shows an example for rbegin().,rbegin}
See also
crbegin() – returns a const reverse iterator to the beginning
rend() – returns a reverse iterator to the end
crend() – returns a const reverse iterator to the end
Since
version 1.0.0
Definition at line 4818 of file json.hpp.
     {
         return reverse_iterator(end());
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::rbegin () const inline noexcept
returns a const reverse iterator to the last element
Returns a const iterator to the reverse-beginning; that is, the last element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).rbegin().
{The following code shows an example for crbegin().,crbegin}
See also
rbegin() – returns a reverse iterator to the beginning
rend() – returns a reverse iterator to the end
crend() – returns a const reverse iterator to the end
Since
version 1.0.0
Definition at line 4826 of file json.hpp.
     {
         return crbegin();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::rend () inline noexcept
returns an iterator to the reverse-end
Returns an iterator to the reverse-end; that is, one before the first element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of reverse_iterator(begin()).
{The following code shows an example for rend().,rend}
See also
crend() – returns a const reverse iterator to the end
rbegin() – returns a reverse iterator to the beginning
crbegin() – returns a const reverse iterator to the beginning
Since
version 1.0.0
Definition at line 4855 of file json.hpp.
     {
         return reverse_iterator(begin());
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reverse_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::rend () const inline noexcept
returns a const reverse iterator to one before the first
Returns a const reverse iterator to the reverse-end; that is, one before the first element.
Illustration from cppreference.com
Constant.
This function helps basic_json satisfying the ReversibleContainer requirements:
The complexity is constant.
Has the semantics of const_cast<const basic_json&>(*this).rend().
{The following code shows an example for crend().,crend}
See also
rend() – returns a reverse iterator to the end
rbegin() – returns a reverse iterator to the beginning
crbegin() – returns a const reverse iterator to the beginning
Since
version 1.0.0
Definition at line 4863 of file json.hpp.
     {
         return crend();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> size_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::size () const inline noexcept
returns the number of elements
Returns the number of elements in a JSON value.
Returns
The return value depends on the different types and is defined as follows:
Value type return value
null 0
boolean 1
string 1
number 1
object result of function object_t::size()
array result of function array_t::size()
Note
This function does not return the length of a string stored as JSON value - it returns the number of elements in the JSON value which is 1 in the case of a string.
Constant, as long as array_t and object_t satisfy the Container concept; that is, their size() functions have constant complexity.
This function helps basic_json satisfying the Container requirements:
The complexity is constant.
Has the semantics of std::distance(begin(), end()).
{The following code calls size() on the different value types.,size}
See also
empty() – checks whether the container is empty
max_size() – returns the maximal number of elements
Since
version 1.0.0
Definition at line 5070 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::null, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
     {
         switch (m_type)
         {
             case value_t::null:
             {
                 // null values are empty
                 return 0;
             }
             case value_t::array:
             {
                 // delegate call to array_t::size()
                 return m_value.array->size();
             }
             case value_t::object:
             {
                 // delegate call to object_t::size()
                 return m_value.object->size();
             }
             default:
             {
                 // all other types have size 1
                 return 1;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::swap (reference other) inline noexcept
exchanges the values
Exchanges the contents of the JSON value with those of other. Does not invoke any move, copy, or swap operations on individual elements. All iterators and references remain valid. The past-the-end iterator is invalidated.
Parameters
[in,out] other JSON value to exchange the contents with
Constant.
{The example below shows how JSON values can be swapped with swap().,swap__reference}
Since
version 1.0.0
Definition at line 5745 of file json.hpp.
     {
         std::swap(m_type, other.m_type);
         std::swap(m_value, other.m_value);
         assert_invariant();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::swap (array_t & other) inline
exchanges the values
Exchanges the contents of a JSON array with those of other. Does not invoke any move, copy, or swap operations on individual elements. All iterators and references remain valid. The past-the-end iterator is invalidated.
Parameters
[in,out] other array to exchange the contents with
Exceptions
std::domain_error when JSON value is not an array; example: "cannot use swap() with string"
Constant.
{The example below shows how arrays can be swapped with swap().,swap__array_t}
Since
version 1.0.0
Definition at line 5777 of file json.hpp.
References JSON_THROW.
     {
         // swap only works for arrays
         if (is_array())
         {
             std::swap(*(m_value.array), other);
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use swap() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::swap (object_t & other) inline
exchanges the values
Exchanges the contents of a JSON object with those of other. Does not invoke any move, copy, or swap operations on individual elements. All iterators and references remain valid. The past-the-end iterator is invalidated.
Parameters
[in,out] other object to exchange the contents with
Exceptions
std::domain_error when JSON value is not an object; example: "cannot use swap() with string"
Constant.
{The example below shows how objects can be swapped with swap().,swap__object_t}
Since
version 1.0.0
Definition at line 5810 of file json.hpp.
References JSON_THROW.
     {
         // swap only works for objects
         if (is_object())
         {
             std::swap(*(m_value.object), other);
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use swap() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::swap (string_t & other) inline
exchanges the values
Exchanges the contents of a JSON string with those of other. Does not invoke any move, copy, or swap operations on individual elements. All iterators and references remain valid. The past-the-end iterator is invalidated.
Parameters
[in,out] other string to exchange the contents with
Exceptions
std::domain_error when JSON value is not a string; example: "cannot use swap() with boolean"
Constant.
{The example below shows how strings can be swapped with swap().,swap__string_t}
Since
version 1.0.0
Definition at line 5843 of file json.hpp.
References JSON_THROW.
     {
         // swap only works for strings
         if (is_string())
         {
             std::swap(*(m_value.string), other);
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use swap() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static std::vector<uint8_t> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j) inline static
create a MessagePack serialization of a given JSON value
Serializes a given JSON value j to a byte vector using the CBOR (Concise Binary Object Representation) serialization format. CBOR is a binary serialization format which aims to be more compact than JSON itself, yet more efficient to parse.
Parameters
[in] j JSON value to serialize
Returns
MessagePack serialization as byte vector
Linear in the size of the JSON value j.
{The example shows the serialization of a JSON value to a byte vector in CBOR format.,to_cbor}
See also
http://cbor.io
from_cbor(const std::vector<uint8_t>&) for the analogous deserialization
to_msgpack(const basic_json& for the related MessagePack format
Definition at line 8025 of file json.hpp.
     {
         std::vector<uint8_t> result;
         to_cbor_internal(j, result);
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor_internal (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j, std::vector< uint8_t > & v) inline static private
create a CBOR serialization of a given JSON value
This is a straightforward implementation of the CBOR specification.
Parameters
[in] j JSON value to serialize
[in,out] v byte vector to write the serialization to
See also
https://tools.ietf.org/html/rfc7049
Definition at line 6930 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::array, nlohmann::detail::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_float, nlohmann::detail::number_integer, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_integer, nlohmann::detail::number_unsigned, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_unsigned, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object, nlohmann::detail::string, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::string, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::type().
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 v.push_back(0xf6);
                 break;
             }
             case value_t::boolean:
             {
                 v.push_back(j.m_value.boolean ? 0xf5 : 0xf4);
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // CBOR does not differentiate between positive signed
                     // integers and unsigned integers. Therefore, we used the
                     // code from the value_t::number_unsigned case here.
                     if (j.m_value.number_integer <= 0x17)
                     {
                         add_to_vector(v, 1, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer <= UINT8_MAX)
                     {
                         v.push_back(0x18);
                         // one-byte uint8_t
                         add_to_vector(v, 1, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer <= UINT16_MAX)
                     {
                         v.push_back(0x19);
                         // two-byte uint16_t
                         add_to_vector(v, 2, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer <= UINT32_MAX)
                     {
                         v.push_back(0x1a);
                         // four-byte uint32_t
                         add_to_vector(v, 4, j.m_value.number_integer);
                     }
                     else
                     {
                         v.push_back(0x1b);
                         // eight-byte uint64_t
                         add_to_vector(v, 8, j.m_value.number_integer);
                     }
                 }
                 else
                 {
                     // The conversions below encode the sign in the first
                     // byte, and the value is converted to a positive number.
                     const auto positive_number = -1 - j.m_value.number_integer;
                     if (j.m_value.number_integer >= -24)
                     {
                         v.push_back(static_cast<uint8_t>(0x20 + positive_number));
                     }
                     else if (positive_number <= UINT8_MAX)
                     {
                         // int 8
                         v.push_back(0x38);
                         add_to_vector(v, 1, positive_number);
                     }
                     else if (positive_number <= UINT16_MAX)
                     {
                         // int 16
                         v.push_back(0x39);
                         add_to_vector(v, 2, positive_number);
                     }
                     else if (positive_number <= UINT32_MAX)
                     {
                         // int 32
                         v.push_back(0x3a);
                         add_to_vector(v, 4, positive_number);
                     }
                     else
                     {
                         // int 64
                         v.push_back(0x3b);
                         add_to_vector(v, 8, positive_number);
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned <= 0x17)
                 {
                     v.push_back(static_cast<uint8_t>(j.m_value.number_unsigned));
                 }
                 else if (j.m_value.number_unsigned <= 0xff)
                 {
                     v.push_back(0x18);
                     // one-byte uint8_t
                     add_to_vector(v, 1, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= 0xffff)
                 {
                     v.push_back(0x19);
                     // two-byte uint16_t
                     add_to_vector(v, 2, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= 0xffffffff)
                 {
                     v.push_back(0x1a);
                     // four-byte uint32_t
                     add_to_vector(v, 4, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= 0xffffffffffffffff)
                 {
                     v.push_back(0x1b);
                     // eight-byte uint64_t
                     add_to_vector(v, 8, j.m_value.number_unsigned);
                 }
                 break;
             }
             case value_t::number_float:
             {
                 // Double-Precision Float
                 v.push_back(0xfb);
                 const auto* helper = reinterpret_cast<const uint8_t*>(&(j.m_value.number_float));
                 for (size_t i = 0; i < 8; ++i)
                 {
                     v.push_back(helper[7 - i]);
                 }
                 break;
             }
             case value_t::string:
             {
                 const auto N = j.m_value.string->size();
                 if (N <= 0x17)
                 {
                     v.push_back(0x60 + N);  // 1 byte for string + size
                 }
                 else if (N <= 0xff)
                 {
                     v.push_back(0x78);  // one-byte uint8_t for N
                     add_to_vector(v, 1, N);
                 }
                 else if (N <= 0xffff)
                 {
                     v.push_back(0x79);  // two-byte uint16_t for N
                     add_to_vector(v, 2, N);
                 }
                 else if (N <= 0xffffffff)
                 {
                     v.push_back(0x7a); // four-byte uint32_t for N
                     add_to_vector(v, 4, N);
                 }
                 // LCOV_EXCL_START
                 else if (N <= 0xffffffffffffffff)
                 {
                     v.push_back(0x7b);  // eight-byte uint64_t for N
                     add_to_vector(v, 8, N);
                 }
                 // LCOV_EXCL_STOP
                 // append string
                 std::copy(j.m_value.string->begin(), j.m_value.string->end(),
                           std::back_inserter(v));
                 break;
             }
             case value_t::array:
             {
                 const auto N = j.m_value.array->size();
                 if (N <= 0x17)
                 {
                     v.push_back(0x80 + N);  // 1 byte for array + size
                 }
                 else if (N <= 0xff)
                 {
                     v.push_back(0x98);  // one-byte uint8_t for N
                     add_to_vector(v, 1, N);
                 }
                 else if (N <= 0xffff)
                 {
                     v.push_back(0x99);  // two-byte uint16_t for N
                     add_to_vector(v, 2, N);
                 }
                 else if (N <= 0xffffffff)
                 {
                     v.push_back(0x9a);  // four-byte uint32_t for N
                     add_to_vector(v, 4, N);
                 }
                 // LCOV_EXCL_START
                 else if (N <= 0xffffffffffffffff)
                 {
                     v.push_back(0x9b);  // eight-byte uint64_t for N
                     add_to_vector(v, 8, N);
                 }
                 // LCOV_EXCL_STOP
                 // append each element
                 for (const auto& el : *j.m_value.array)
                 {
                     to_cbor_internal(el, v);
                 }
                 break;
             }
             case value_t::object:
             {
                 const auto N = j.m_value.object->size();
                 if (N <= 0x17)
                 {
                     v.push_back(0xa0 + N);  // 1 byte for object + size
                 }
                 else if (N <= 0xff)
                 {
                     v.push_back(0xb8);
                     add_to_vector(v, 1, N);  // one-byte uint8_t for N
                 }
                 else if (N <= 0xffff)
                 {
                     v.push_back(0xb9);
                     add_to_vector(v, 2, N);  // two-byte uint16_t for N
                 }
                 else if (N <= 0xffffffff)
                 {
                     v.push_back(0xba);
                     add_to_vector(v, 4, N);  // four-byte uint32_t for N
                 }
                 // LCOV_EXCL_START
                 else if (N <= 0xffffffffffffffff)
                 {
                     v.push_back(0xbb);
                     add_to_vector(v, 8, N);  // eight-byte uint64_t for N
                 }
                 // LCOV_EXCL_STOP
                 // append each element
                 for (const auto& el : *j.m_value.object)
                 {
                     to_cbor_internal(el.first, v);
                     to_cbor_internal(el.second, v);
                 }
                 break;
             }
             default:
             {
                 break;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static std::vector<uint8_t> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j) inline static
create a MessagePack serialization of a given JSON value
Serializes a given JSON value j to a byte vector using the MessagePack serialization format. MessagePack is a binary serialization format which aims to be more compact than JSON itself, yet more efficient to parse.
Parameters
[in] j JSON value to serialize
Returns
MessagePack serialization as byte vector
Linear in the size of the JSON value j.
{The example shows the serialization of a JSON value to a byte vector in MessagePack format.,to_msgpack}
See also
http://msgpack.org
from_msgpack(const std::vector<uint8_t>&) for the analogous deserialization
to_cbor(const basic_json& for the related CBOR format
Definition at line 7969 of file json.hpp.
     {
         std::vector<uint8_t> result;
         to_msgpack_internal(j, result);
         return result;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack_internal (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j, std::vector< uint8_t > & v) inline static private
create a MessagePack serialization of a given JSON value
This is a straightforward implementation of the MessagePack specification.
Parameters
[in] j JSON value to serialize
[in,out] v byte vector to write the serialization to
See also
https://github.com/msgpack/msgpack/blob/master/spec.md
Definition at line 6684 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::array, nlohmann::detail::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::boolean, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_float, nlohmann::detail::number_integer, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_integer, nlohmann::detail::number_unsigned, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::number_unsigned, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object, nlohmann::detail::string, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::string, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::type().
     {
         switch (j.type())
         {
             case value_t::null:
             {
                 // nil
                 v.push_back(0xc0);
                 break;
             }
             case value_t::boolean:
             {
                 // true and false
                 v.push_back(j.m_value.boolean ? 0xc3 : 0xc2);
                 break;
             }
             case value_t::number_integer:
             {
                 if (j.m_value.number_integer >= 0)
                 {
                     // MessagePack does not differentiate between positive
                     // signed integers and unsigned integers. Therefore, we
                     // used the code from the value_t::number_unsigned case
                     // here.
                     if (j.m_value.number_unsigned < 128)
                     {
                         // positive fixnum
                         add_to_vector(v, 1, j.m_value.number_unsigned);
                     }
                     else if (j.m_value.number_unsigned <= UINT8_MAX)
                     {
                         // uint 8
                         v.push_back(0xcc);
                         add_to_vector(v, 1, j.m_value.number_unsigned);
                     }
                     else if (j.m_value.number_unsigned <= UINT16_MAX)
                     {
                         // uint 16
                         v.push_back(0xcd);
                         add_to_vector(v, 2, j.m_value.number_unsigned);
                     }
                     else if (j.m_value.number_unsigned <= UINT32_MAX)
                     {
                         // uint 32
                         v.push_back(0xce);
                         add_to_vector(v, 4, j.m_value.number_unsigned);
                     }
                     else if (j.m_value.number_unsigned <= UINT64_MAX)
                     {
                         // uint 64
                         v.push_back(0xcf);
                         add_to_vector(v, 8, j.m_value.number_unsigned);
                     }
                 }
                 else
                 {
                     if (j.m_value.number_integer >= -32)
                     {
                         // negative fixnum
                         add_to_vector(v, 1, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer >= INT8_MIN and j.m_value.number_integer <= INT8_MAX)
                     {
                         // int 8
                         v.push_back(0xd0);
                         add_to_vector(v, 1, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer >= INT16_MIN and j.m_value.number_integer <= INT16_MAX)
                     {
                         // int 16
                         v.push_back(0xd1);
                         add_to_vector(v, 2, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer >= INT32_MIN and j.m_value.number_integer <= INT32_MAX)
                     {
                         // int 32
                         v.push_back(0xd2);
                         add_to_vector(v, 4, j.m_value.number_integer);
                     }
                     else if (j.m_value.number_integer >= INT64_MIN and j.m_value.number_integer <= INT64_MAX)
                     {
                         // int 64
                         v.push_back(0xd3);
                         add_to_vector(v, 8, j.m_value.number_integer);
                     }
                 }
                 break;
             }
             case value_t::number_unsigned:
             {
                 if (j.m_value.number_unsigned < 128)
                 {
                     // positive fixnum
                     add_to_vector(v, 1, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= UINT8_MAX)
                 {
                     // uint 8
                     v.push_back(0xcc);
                     add_to_vector(v, 1, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= UINT16_MAX)
                 {
                     // uint 16
                     v.push_back(0xcd);
                     add_to_vector(v, 2, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= UINT32_MAX)
                 {
                     // uint 32
                     v.push_back(0xce);
                     add_to_vector(v, 4, j.m_value.number_unsigned);
                 }
                 else if (j.m_value.number_unsigned <= UINT64_MAX)
                 {
                     // uint 64
                     v.push_back(0xcf);
                     add_to_vector(v, 8, j.m_value.number_unsigned);
                 }
                 break;
             }
             case value_t::number_float:
             {
                 // float 64
                 v.push_back(0xcb);
                 const auto* helper = reinterpret_cast<const uint8_t*>(&(j.m_value.number_float));
                 for (size_t i = 0; i < 8; ++i)
                 {
                     v.push_back(helper[7 - i]);
                 }
                 break;
             }
             case value_t::string:
             {
                 const auto N = j.m_value.string->size();
                 if (N <= 31)
                 {
                     // fixstr
                     v.push_back(static_cast<uint8_t>(0xa0 | N));
                 }
                 else if (N <= 255)
                 {
                     // str 8
                     v.push_back(0xd9);
                     add_to_vector(v, 1, N);
                 }
                 else if (N <= 65535)
                 {
                     // str 16
                     v.push_back(0xda);
                     add_to_vector(v, 2, N);
                 }
                 else if (N <= 4294967295)
                 {
                     // str 32
                     v.push_back(0xdb);
                     add_to_vector(v, 4, N);
                 }
                 // append string
                 std::copy(j.m_value.string->begin(), j.m_value.string->end(),
                           std::back_inserter(v));
                 break;
             }
             case value_t::array:
             {
                 const auto N = j.m_value.array->size();
                 if (N <= 15)
                 {
                     // fixarray
                     v.push_back(static_cast<uint8_t>(0x90 | N));
                 }
                 else if (N <= 0xffff)
                 {
                     // array 16
                     v.push_back(0xdc);
                     add_to_vector(v, 2, N);
                 }
                 else if (N <= 0xffffffff)
                 {
                     // array 32
                     v.push_back(0xdd);
                     add_to_vector(v, 4, N);
                 }
                 // append each element
                 for (const auto& el : *j.m_value.array)
                 {
                     to_msgpack_internal(el, v);
                 }
                 break;
             }
             case value_t::object:
             {
                 const auto N = j.m_value.object->size();
                 if (N <= 15)
                 {
                     // fixmap
                     v.push_back(static_cast<uint8_t>(0x80 | (N & 0xf)));
                 }
                 else if (N <= 65535)
                 {
                     // map 16
                     v.push_back(0xde);
                     add_to_vector(v, 2, N);
                 }
                 else if (N <= 4294967295)
                 {
                     // map 32
                     v.push_back(0xdf);
                     add_to_vector(v, 4, N);
                 }
                 // append each element
                 for (const auto& el : *j.m_value.object)
                 {
                     to_msgpack_internal(el.first, v);
                     to_msgpack_internal(el.second, v);
                 }
                 break;
             }
             default:
             {
                 break;
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> constexpr value_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::type () const inline noexcept
return the type of the JSON value (explicit)
Return the type of the JSON value as a value from the value_t enumeration.
Returns
the type of the JSON value
Constant.
No-throw guarantee: this member function never throws exceptions.
{The following code exemplifies type() for all JSON types.,type}
Since
version 1.0.0
Definition at line 2688 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor_internal(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack_internal().
     {
         return m_type;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::string nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::type_name () const inline
return the type as string
Returns the type name as string to be used in error messages - usually to indicate that a function was called on a wrong JSON type.
Returns
basically a string representation of a the m_type member
Constant.
{The following code exemplifies type_name() for all JSON types.,type_name}
Since
version 1.0.0, public since 2.1.0
Definition at line 8082 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::object, and nlohmann::detail::string.
     {
         {
             switch (m_type)
             {
                 case value_t::null:
                     return "null";
                 case value_t::object:
                     return "object";
                 case value_t::array:
                     return "array";
                 case value_t::string:
                     return "string";
                 case value_t::boolean:
                     return "boolean";
                 case value_t::discarded:
                     return "discarded";
                 default:
                     return "number";
             }
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::unflatten () const inline
unflatten a previously flattened JSON value
The function restores the arbitrary nesting of a JSON value that has been flattened before using the flatten() function. The JSON value must meet certain constraints:
The value must be an object.
The keys must be JSON pointers (see RFC 6901)
The mapped values must be primitive JSON types.
Returns
the original JSON from a flattened version
Note
Empty objects and arrays are flattened by flatten() to null values and can not unflattened to their original type. Apart from this example, for a JSON value j, the following is always true: j == j.flatten().unflatten().
Linear in the size the JSON value.
{The following code shows how a flattened JSON object is unflattened into the original nested JSON object.,unflatten}
See also
flatten() for the reverse function
Since
version 2.0.0
Definition at line 12116 of file json.hpp.
     {
         return json_pointer::unflatten(*this);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class ValueType , typename std::enable_if< std::is_convertible< basic_json_t, ValueType >::value, int >::type = 0> ValueType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value (const typename object_t::key_type & key, ValueType default_value) const inline
access specified object element with default value
Returns either a copy of an object's element at the specified key key or a given default value if no element with key key exists.
The function is basically equivalent to executing
try {
    return at(key);
} catch(std::out_of_range) {
    return default_value;
}
Note
Unlike at(const typename object_t::key_type&), this function does not throw if the given key key was not found.
Unlike operator[](const typename object_t::key_type& key), this function does not implicitly add an element to the position defined by key. This function is furthermore also applicable to const objects.
Parameters
[in] key key of the element to access
[in] default_value the value to return if key is not found
Template Parameters
ValueType type compatible to JSON values, for instance int for JSON integer numbers, bool for JSON booleans, or std::vector types for JSON arrays. Note the type of the expected value at key and the default value default_value must be compatible.
Returns
copy of the element at key key or default_value if key is not found
Exceptions
std::domain_error if JSON is not an object; example: "cannot use value() with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be queried with a default value.,basic_json__value}
See also
at(const typename object_t::key_type&) for access by reference with range checking
operator[](const typename object_t::key_type&) for unchecked access by reference
Since
version 1.0.0
Definition at line 4074 of file json.hpp.
References JSON_THROW.
     {
         // at only works for objects
         if (is_object())
         {
             // if key is found, return value and given default value otherwise
             const auto it = find(key);
             if (it != end())
             {
                 return *it;
             }
             return default_value;
         }
         else
         {
             JSON_THROW(std::domain_error("cannot use value() with " + type_name()));
         }
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> string_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value (const typename object_t::key_type & key, const char * default_value) const inline
overload for a default value of type const char*
access specified object element with default value Returns either a copy of an object's element at the specified key key or a given default value if no element with key key exists.
The function is basically equivalent to executing
try {
    return at(key);
} catch(std::out_of_range) {
    return default_value;
}
Note
Unlike at(const typename object_t::key_type&), this function does not throw if the given key key was not found.
Unlike operator[](const typename object_t::key_type& key), this function does not implicitly add an element to the position defined by key. This function is furthermore also applicable to const objects.
Parameters
[in] key key of the element to access
[in] default_value the value to return if key is not found
Template Parameters
ValueType type compatible to JSON values, for instance int for JSON integer numbers, bool for JSON booleans, or std::vector types for JSON arrays. Note the type of the expected value at key and the default value default_value must be compatible.
Returns
copy of the element at key key or default_value if key is not found
Exceptions
std::domain_error if JSON is not an object; example: "cannot use value() with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be queried with a default value.,basic_json__value}
See also
at(const typename object_t::key_type&) for access by reference with range checking
operator[](const typename object_t::key_type&) for unchecked access by reference
Since
version 1.0.0
Definition at line 4098 of file json.hpp.
     {
         return value(key, string_t(default_value));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class ValueType , typename std::enable_if< std::is_convertible< basic_json_t, ValueType >::value, int >::type = 0> ValueType nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value (const json_pointer & ptr, ValueType default_value) const inline
access specified object element via JSON Pointer with default value
Returns either a copy of an object's element at the specified key key or a given default value if no element with key key exists.
The function is basically equivalent to executing
try {
    return at(ptr);
} catch(std::out_of_range) {
    return default_value;
}
Note
Unlike at(const json_pointer&), this function does not throw if the given key key was not found.
Parameters
[in] ptr a JSON pointer to the element to access
[in] default_value the value to return if ptr found no value
Template Parameters
ValueType type compatible to JSON values, for instance int for JSON integer numbers, bool for JSON booleans, or std::vector types for JSON arrays. Note the type of the expected value at key and the default value default_value must be compatible.
Returns
copy of the element at key key or default_value if key is not found
Exceptions
std::domain_error if JSON is not an object; example: "cannot use value() with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be queried with a default value.,basic_json__value_ptr}
See also
operator[](const json_pointer&) for unchecked access by reference
Since
version 2.0.2
Definition at line 4146 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_checked(), JSON_CATCH, JSON_THROW, and JSON_TRY.
     {
         // at only works for objects
         if (is_object())
         {
             // if pointer resolves a value, return it or use default value
             JSON_TRY
             {
                 return ptr.get_checked(this);
             }
             JSON_CATCH (std::out_of_range&)
             {
                 return default_value;
             }
         }
         JSON_THROW(std::domain_error("cannot use value() with " + type_name()));
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> string_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value (const json_pointer & ptr, const char * default_value) const inline
overload for a default value of type const char*
access specified object element via JSON Pointer with default value Returns either a copy of an object's element at the specified key key or a given default value if no element with key key exists.
The function is basically equivalent to executing
try {
    return at(ptr);
} catch(std::out_of_range) {
    return default_value;
}
Note
Unlike at(const json_pointer&), this function does not throw if the given key key was not found.
Parameters
[in] ptr a JSON pointer to the element to access
[in] default_value the value to return if ptr found no value
Template Parameters
ValueType type compatible to JSON values, for instance int for JSON integer numbers, bool for JSON booleans, or std::vector types for JSON arrays. Note the type of the expected value at key and the default value default_value must be compatible.
Returns
copy of the element at key key or default_value if key is not found
Exceptions
std::domain_error if JSON is not an object; example: "cannot use value() with null"
Logarithmic in the size of the container.
{The example below shows how object elements can be queried with a default value.,basic_json__value_ptr}
See also
operator[](const json_pointer&) for unchecked access by reference
Since
version 2.0.2
Definition at line 4169 of file json.hpp.
     {
         return value(ptr, string_t(default_value));
     }
Friends And Related Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<detail::value_t > friend struct detail::external_constructor friend
Definition at line 1041 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator!= (const_reference lhs, const_reference rhs) friend
comparison: not equal
Compares two JSON values for inequality by calculating not (lhs == rhs).
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether the values lhs and rhs are not equal
Linear.
{The example demonstrates comparing several JSON types.,operator__notequal}
Since
version 1.0.0
Definition at line 6012 of file json.hpp.
     {
         return not (lhs == rhs);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator!= (const_reference v, std::nullptr_t) friend
comparison: not equal
The functions compares the given JSON value against a null pointer. As the null pointer can be used to initialize a JSON value to null, a comparison of JSON value v with a null pointer should be equivalent to call not v.is_null().
Parameters
[in] v JSON value to consider
Returns
whether v is not null
Constant.
{The example compares several JSON types to the null pointer. ,operator__notequal__nullptr_t}
Since
version 1.0.0
Definition at line 6035 of file json.hpp.
     {
         return not v.is_null();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator!= (std::nullptr_t , const_reference v) friend
comparison: not equal
comparison: not equal The functions compares the given JSON value against a null pointer. As the null pointer can be used to initialize a JSON value to null, a comparison of JSON value v with a null pointer should be equivalent to call not v.is_null().
Parameters
[in] v JSON value to consider
Returns
whether v is not null
Constant.
{The example compares several JSON types to the null pointer. ,operator__notequal__nullptr_t}
Since
version 1.0.0
Definition at line 6044 of file json.hpp.
     {
         return not v.is_null();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator< (const_reference lhs, const_reference rhs) friend
comparison: less than
Compares whether one JSON value lhs is less than another JSON value rhs according to the following rules:
If lhs and rhs have the same type, the values are compared using the default < operator.
Integer and floating-point numbers are automatically converted before comparison
In case lhs and rhs have different types, the values are ignored and the order of the types is considered, see operator<(const value_t, const value_t).
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether lhs is less than rhs
Linear.
{The example demonstrates comparing several JSON types.,operator__less}
Since
version 1.0.0
Definition at line 6073 of file json.hpp.
     {
         const auto lhs_type = lhs.type();
         const auto rhs_type = rhs.type();
         if (lhs_type == rhs_type)
         {
             switch (lhs_type)
             {
                 case value_t::array:
                 {
                     return *lhs.m_value.array < *rhs.m_value.array;
                 }
                 case value_t::object:
                 {
                     return *lhs.m_value.object < *rhs.m_value.object;
                 }
                 case value_t::null:
                 {
                     return false;
                 }
                 case value_t::string:
                 {
                     return *lhs.m_value.string < *rhs.m_value.string;
                 }
                 case value_t::boolean:
                 {
                     return lhs.m_value.boolean < rhs.m_value.boolean;
                 }
                 case value_t::number_integer:
                 {
                     return lhs.m_value.number_integer < rhs.m_value.number_integer;
                 }
                 case value_t::number_unsigned:
                 {
                     return lhs.m_value.number_unsigned < rhs.m_value.number_unsigned;
                 }
                 case value_t::number_float:
                 {
                     return lhs.m_value.number_float < rhs.m_value.number_float;
                 }
                 default:
                 {
                     return false;
                 }
             }
         }
         else if (lhs_type == value_t::number_integer and rhs_type == value_t::number_float)
         {
             return static_cast<number_float_t>(lhs.m_value.number_integer) < rhs.m_value.number_float;
         }
         else if (lhs_type == value_t::number_float and rhs_type == value_t::number_integer)
         {
             return lhs.m_value.number_float < static_cast<number_float_t>(rhs.m_value.number_integer);
         }
         else if (lhs_type == value_t::number_unsigned and rhs_type == value_t::number_float)
         {
             return static_cast<number_float_t>(lhs.m_value.number_unsigned) < rhs.m_value.number_float;
         }
         else if (lhs_type == value_t::number_float and rhs_type == value_t::number_unsigned)
         {
             return lhs.m_value.number_float < static_cast<number_float_t>(rhs.m_value.number_unsigned);
         }
         else if (lhs_type == value_t::number_integer and rhs_type == value_t::number_unsigned)
         {
             return lhs.m_value.number_integer < static_cast<number_integer_t>(rhs.m_value.number_unsigned);
         }
         else if (lhs_type == value_t::number_unsigned and rhs_type == value_t::number_integer)
         {
             return static_cast<number_integer_t>(lhs.m_value.number_unsigned) < rhs.m_value.number_integer;
         }
         // We only reach this line if we cannot compare values. In that case,
         // we compare types. Note we have to call the operator explicitly,
         // because MSVC has problems otherwise.
         return operator<(lhs_type, rhs_type);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::ostream& operator<< (std::ostream & o, const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j) friend
serialize to stream
Serialize the given JSON value j to the output stream o. The JSON value will be serialized using the dump member function. The indentation of the output can be controlled with the member variable width of the output stream o. For instance, using the manipulator std::setw(4) on o sets the indentation level to 4 and the serialization result is the same as calling dump(4).
Note
During serialization, the locale and the precision of the output stream o are changed. The original values are restored when the function returns.
Parameters
[in,out] o stream to serialize to
[in] j JSON value to serialize
Returns
the stream o
Linear.
{The example below shows the serialization with different parameters to width to adjust the indentation level.,operator_serialize}
Since
version 1.0.0
Definition at line 6253 of file json.hpp.
     {
         // read width member and use it as indentation parameter if nonzero
         const bool pretty_print = (o.width() > 0);
         const auto indentation = (pretty_print ? o.width() : 0);
         // reset width to 0 for subsequent calls to this stream
         o.width(0);
         // fix locale problems
         const auto old_locale = o.imbue(std::locale::classic());
         // set precision
         // 6, 15 or 16 digits of precision allows round-trip IEEE 754
         // string->float->string, string->double->string or string->long
         // double->string; to be safe, we read this value from
         // std::numeric_limits<number_float_t>::digits10
         const auto old_precision = o.precision(std::numeric_limits<double>::digits10);
         // do the actual serialization
         j.dump(o, pretty_print, static_cast<unsigned int>(indentation));
         // reset locale and precision
         o.imbue(old_locale);
         o.precision(old_precision);
         return o;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::istream& operator<< (basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j, std::istream & i) friend
deserialize from stream
Deserializes an input stream to a JSON value.
Parameters
[in,out] i input stream to read a serialized JSON value from
[in,out] j JSON value to write the deserialized input to
Exceptions
std::invalid_argument in case of parse errors
Linear in the length of the input. The parser is a predictive LL(1) parser.
Note
A UTF-8 byte order mark is silently ignored.
{The example below shows how a JSON value is constructed by reading a serialization from a stream.,operator_deserialize}
See also
parse(std::istream&, const parser_callback_t) for a variant with a parser callback function to filter values while parsing
Since
version 1.0.0
Definition at line 6558 of file json.hpp.
     {
         j = parser(i).parse();
         return i;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator<= (const_reference lhs, const_reference rhs) friend
comparison: less than or equal
Compares whether one JSON value lhs is less than or equal to another JSON value by calculating not (rhs < lhs).
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether lhs is less than or equal to rhs
Linear.
{The example demonstrates comparing several JSON types.,operator__greater}
Since
version 1.0.0
Definition at line 6168 of file json.hpp.
     {
         return not (rhs < lhs);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator== (const_reference lhs, const_reference rhs) friend
comparison: equal
Compares two JSON values for equality according to the following rules:
Two JSON values are equal if (1) they are from the same type and (2) their stored values are the same.
Integer and floating-point numbers are automatically converted before comparison. Floating-point numbers are compared indirectly: two floating-point numbers f1 and f2 are considered equal if neither f1 > f2 nor f2 > f1 holds.
Two JSON null values are equal.
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether the values lhs and rhs are equal
Linear.
{The example demonstrates comparing several JSON types.,operator__equal}
Since
version 1.0.0
Definition at line 5889 of file json.hpp.
     {
         const auto lhs_type = lhs.type();
         const auto rhs_type = rhs.type();
         if (lhs_type == rhs_type)
         {
             switch (lhs_type)
             {
                 case value_t::array:
                 {
                     return *lhs.m_value.array == *rhs.m_value.array;
                 }
                 case value_t::object:
                 {
                     return *lhs.m_value.object == *rhs.m_value.object;
                 }
                 case value_t::null:
                 {
                     return true;
                 }
                 case value_t::string:
                 {
                     return *lhs.m_value.string == *rhs.m_value.string;
                 }
                 case value_t::boolean:
                 {
                     return lhs.m_value.boolean == rhs.m_value.boolean;
                 }
                 case value_t::number_integer:
                 {
                     return lhs.m_value.number_integer == rhs.m_value.number_integer;
                 }
                 case value_t::number_unsigned:
                 {
                     return lhs.m_value.number_unsigned == rhs.m_value.number_unsigned;
                 }
                 case value_t::number_float:
                 {
                     return lhs.m_value.number_float == rhs.m_value.number_float;
                 }
                 default:
                 {
                     return false;
                 }
             }
         }
         else if (lhs_type == value_t::number_integer and rhs_type == value_t::number_float)
         {
             return static_cast<number_float_t>(lhs.m_value.number_integer) == rhs.m_value.number_float;
         }
         else if (lhs_type == value_t::number_float and rhs_type == value_t::number_integer)
         {
             return lhs.m_value.number_float == static_cast<number_float_t>(rhs.m_value.number_integer);
         }
         else if (lhs_type == value_t::number_unsigned and rhs_type == value_t::number_float)
         {
             return static_cast<number_float_t>(lhs.m_value.number_unsigned) == rhs.m_value.number_float;
         }
         else if (lhs_type == value_t::number_float and rhs_type == value_t::number_unsigned)
         {
             return lhs.m_value.number_float == static_cast<number_float_t>(rhs.m_value.number_unsigned);
         }
         else if (lhs_type == value_t::number_unsigned and rhs_type == value_t::number_integer)
         {
             return static_cast<number_integer_t>(lhs.m_value.number_unsigned) == rhs.m_value.number_integer;
         }
         else if (lhs_type == value_t::number_integer and rhs_type == value_t::number_unsigned)
         {
             return lhs.m_value.number_integer == static_cast<number_integer_t>(rhs.m_value.number_unsigned);
         }
         return false;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator== (const_reference v, std::nullptr_t) friend
comparison: equal
The functions compares the given JSON value against a null pointer. As the null pointer can be used to initialize a JSON value to null, a comparison of JSON value v with a null pointer should be equivalent to call v.is_null().
Parameters
[in] v JSON value to consider
Returns
whether v is null
Constant.
{The example compares several JSON types to the null pointer. ,operator__equal__nullptr_t}
Since
version 1.0.0
Definition at line 5982 of file json.hpp.
     {
         return v.is_null();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator== (std::nullptr_t , const_reference v) friend
comparison: equal
comparison: equal The functions compares the given JSON value against a null pointer. As the null pointer can be used to initialize a JSON value to null, a comparison of JSON value v with a null pointer should be equivalent to call v.is_null().
Parameters
[in] v JSON value to consider
Returns
whether v is null
Constant.
{The example compares several JSON types to the null pointer. ,operator__equal__nullptr_t}
Since
version 1.0.0
Definition at line 5991 of file json.hpp.
     {
         return v.is_null();
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator> (const_reference lhs, const_reference rhs) friend
comparison: greater than
Compares whether one JSON value lhs is greater than another JSON value by calculating not (lhs <= rhs).
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether lhs is greater than to rhs
Linear.
{The example demonstrates comparing several JSON types.,operator__lessequal}
Since
version 1.0.0
Definition at line 6190 of file json.hpp.
     {
         return not (lhs <= rhs);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator>= (const_reference lhs, const_reference rhs) friend
comparison: greater than or equal
Compares whether one JSON value lhs is greater than or equal to another JSON value by calculating not (lhs < rhs).
Parameters
[in] lhs first JSON value to consider
[in] rhs second JSON value to consider
Returns
whether lhs is greater than or equal to rhs
Linear.
{The example demonstrates comparing several JSON types.,operator__greaterequal}
Since
version 1.0.0
Definition at line 6212 of file json.hpp.
     {
         return not (lhs < rhs);
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::ostream& operator>> (const basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j, std::ostream & o) friend
serialize to stream
serialize to stream Serialize the given JSON value j to the output stream o. The JSON value will be serialized using the dump member function. The indentation of the output can be controlled with the member variable width of the output stream o. For instance, using the manipulator std::setw(4) on o sets the indentation level to 4 and the serialization result is the same as calling dump(4).
Note
During serialization, the locale and the precision of the output stream o are changed. The original values are restored when the function returns.
Parameters
[in,out] o stream to serialize to
[in] j JSON value to serialize
Returns
the stream o
Linear.
{The example below shows the serialization with different parameters to width to adjust the indentation level.,operator_serialize}
Since
version 1.0.0
Definition at line 6285 of file json.hpp.
     {
         return o << j;
     }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::istream& operator>> (std::istream & i, basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer > & j) friend
deserialize from stream
deserialize from stream Deserializes an input stream to a JSON value.
Parameters
[in,out] i input stream to read a serialized JSON value from
[in,out] j JSON value to write the deserialized input to
Exceptions
std::invalid_argument in case of parse errors
Linear in the length of the input. The parser is a predictive LL(1) parser.
Note
A UTF-8 byte order mark is silently ignored.
{The example below shows how a JSON value is constructed by reading a serialization from a stream.,operator_deserialize}
See also
parse(std::istream&, const parser_callback_t) for a variant with a parser callback function to filter values while parsing
Since
version 1.0.0
Definition at line 6568 of file json.hpp.
     {
         j = parser(i).parse();
         return i;
     }
Field Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> value_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_type = value_t::null private
the type of the current element
Definition at line 8430 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::flatten(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::lexer::get_number(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> json_value nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value = {} private
the value of the current element
Definition at line 8433 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::flatten(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::lexer::get_number(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_cbor_internal(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::to_msgpack_internal(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::unflatten().
The documentation for this class was generated from the following file:
src/json.hpp