Virtual Zoo: nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer Class Reference
nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer Class Reference
JSON Pointer.
#include <json.hpp>
Public Member Functions
json_pointer (const std::string &s="")
create JSON pointer
std::string to_string () const noexcept
return a string representation of the JSON pointer
operator std::string () const
return a string representation of the JSON pointer
Private Member Functions
std::string pop_back ()
remove and return last reference pointer
bool is_root () const
return whether pointer points to the root document
json_pointer top () const
reference get_and_create (reference j) const
create and return a reference to the pointed to value
reference get_unchecked (pointer ptr) const
return a reference to the pointed to value
reference get_checked (pointer ptr) const
const_reference get_unchecked (const_pointer ptr) const
return a const reference to the pointed to value
const_reference get_checked (const_pointer ptr) const
Static Private Member Functions
static std::vector< std::string > split (const std::string &reference_string)
split the string input to reference tokens
static void replace_substring (std::string &s, const std::string &f, const std::string &t)
replace all occurrences of a substring by another string
static std::string escape (std::string s)
escape tilde and slash
static void unescape (std::string &s)
unescape tilde and slash
static void flatten (const std::string &reference_string, const basic_json &value, basic_json &result)
static basic_json unflatten (const basic_json &value)
Private Attributes
std::vector< std::string > reference_tokens {}
the reference tokens
Friends
class basic_json
allow basic_json to access private members
bool operator== (json_pointer const &lhs, json_pointer const &rhs) noexcept
bool operator!= (json_pointer const &lhs, json_pointer const &rhs) noexcept
Detailed Description
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer>
class nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer
JSON Pointer.
A JSON pointer defines a string syntax for identifying a specific value within a JSON document. It can be used with functions at and operator[]. Furthermore, JSON pointers are the base for JSON patches.
See also
RFC 6901
Since
version 2.0.0
Definition at line 11340 of file json.hpp.
Constructor & Destructor Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::json_pointer (const std::string & s = "") inline explicit
create JSON pointer
Create a JSON pointer according to the syntax described in Section 3 of RFC6901.
Parameters
[in] s string representing the JSON pointer; if omitted, the empty string is assumed which references the whole JSON value
Exceptions
std::domain_error if reference token is nonempty and does not begin with a slash (/); example: "JSON pointer must be empty or begin with /"
std::domain_error if a tilde (~) is not followed by 0 (representing ~) or 1 (representing /); example: "escape error: ~ must be followed with 0 or 1"
{The example shows the construction several valid JSON pointers as well as the exceptional behavior.,json_pointer}
Since
version 2.0.0
Definition at line 11368 of file json.hpp.
             : reference_tokens(split(s))
         {}
Member Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static std::string nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::escape (std::string s) inline static private
escape tilde and slash
Definition at line 11811 of file json.hpp.
         {
             // escape "~"" to "~0" and "/" to "~1"
             replace_substring(s, "~", "~0");
             replace_substring(s, "/", "~1");
             return s;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::flatten (const std::string & reference_string, const basic_json & value, basic_json & result) inline static private
Parameters
[in] reference_string the reference string to the current value
[in] value the value to consider
[in,out] result the result object to insert values to
Note
Empty objects or arrays are flattened to null.
Definition at line 11835 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_type, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, nlohmann::detail::object, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object.
         {
             switch (value.m_type)
             {
                 case value_t::array:
                 {
                     if (value.m_value.array->empty())
                     {
                         // flatten empty array as null
                         result[reference_string] = nullptr;
                     }
                     else
                     {
                         // iterate array and use index as reference string
                         for (size_t i = 0; i < value.m_value.array->size(); ++i)
{
                             flatten(reference_string + "/" + std::to_string(i),
                                     value.m_value.array->operator[](i), result);
                         }
                     }
                     break;
                 }
                 case value_t::object:
                 {
                     if (value.m_value.object->empty())
                     {
                         // flatten empty object as null
                         result[reference_string] = nullptr;
                     }
                     else
                     {
                         // iterate object and use keys as reference string
                         for (const auto& element : *value.m_value.object)
{
                             flatten(reference_string + "/" + escape(element.first),
                                     element.second, result);
                         }
                     }
                     break;
                 }
                 default:
                 {
                     // add primitive value with its reference string
                     result[reference_string] = value;
                     break;
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_and_create (reference j) const inline private
create and return a reference to the pointed to value
Linear in the number of reference tokens.
Definition at line 11440 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, nlohmann::detail::null, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::unflatten().
         {
             pointer result = &j;
             // in case no reference tokens exist, return a reference to the
             // JSON value j which will be overwritten by a primitive value
             for (const auto& reference_token : reference_tokens)
             {
                 switch (result->m_type)
                 {
                     case value_t::null:
                     {
                         if (reference_token == "0")
{
                             // start a new array if reference token is 0
                             result = &result->operator[](0);
                         }
                         else
{
                             // start a new object otherwise
                             result = &result->operator[](reference_token);
                         }
                         break;
                     }
                     case value_t::object:
                     {
                         // create an entry in the object
                         result = &result->operator[](reference_token);
                         break;
                     }
                     case value_t::array:
                     {
                         // create an entry in the array
                         result = &result->operator[](static_cast<size_type>(std::stoi(reference_token)));
                         break;
                     }
                     /*
                     The following code is only reached if there exists a
                     reference token _and_ the current value is primitive. In
                     this case, we have an error situation, because primitive
                     values may only occur as single value; that is, with an
                     empty list of reference tokens.
                     */
                     default:
                     {
                         JSON_THROW(std::domain_error("invalid value to unflatten"));
                     }
                 }
             }
             return *result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_checked (pointer ptr) const inline private
Definition at line 11582 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::at(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value().
         {
             for (const auto& reference_token : reference_tokens)
             {
                 switch (ptr->m_type)
                 {
                     case value_t::object:
                     {
                         // note: at performs range check
                         ptr = &ptr->at(reference_token);
                         break;
                     }
                     case value_t::array:
                     {
                         if (reference_token == "-")
{
                             // "-" always fails the range check
                             throw std::out_of_range("array index '-' (" +
                                                     std::to_string(ptr->m_value.array->size()) +
                                                     ") is out of range");
                         }
                         // error condition (cf. RFC 6901, Sect. 4)
                         if (reference_token.size() > 1 and reference_token[0] == '0')
{
                             JSON_THROW(std::domain_error("array index must not begin with '0'"));
                         }
                         // note: at performs range check
                         ptr = &ptr->at(static_cast<size_type>(std::stoi(reference_token)));
                         break;
                     }
                     default:
                     {
                         JSON_THROW(std::out_of_range("unresolved reference token '" + reference_token + "'"));
                     }
                 }
             }
             return *ptr;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_checked (const_pointer ptr) const inline private
Definition at line 11678 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             for (const auto& reference_token : reference_tokens)
             {
                 switch (ptr->m_type)
                 {
                     case value_t::object:
                     {
                         // note: at performs range check
                         ptr = &ptr->at(reference_token);
                         break;
                     }
                     case value_t::array:
                     {
                         if (reference_token == "-")
{
                             // "-" always fails the range check
                             throw std::out_of_range("array index '-' (" +
                                                     std::to_string(ptr->m_value.array->size()) +
                                                     ") is out of range");
                         }
                         // error condition (cf. RFC 6901, Sect. 4)
                         if (reference_token.size() > 1 and reference_token[0] == '0')
{
                             JSON_THROW(std::domain_error("array index must not begin with '0'"));
                         }
                         // note: at performs range check
                         ptr = &ptr->at(static_cast<size_type>(std::stoi(reference_token)));
                         break;
                     }
                     default:
                     {
                         JSON_THROW(std::out_of_range("unresolved reference token '" + reference_token + "'"));
                     }
                 }
             }
             return *ptr;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_unchecked (pointer ptr) const inline private
return a reference to the pointed to value
Note
This version does not throw if a value is not present, but tries to create nested values instead. For instance, calling this function with pointer "/this/that" on a null value is equivalent to calling operator[]("this").operator[]("that") on that value, effectively changing the null value to an object.
Parameters
[in] ptr a JSON value
Returns
reference to the JSON value pointed to by the JSON pointer
Linear in the length of the JSON pointer.
Exceptions
std::out_of_range if the JSON pointer can not be resolved
std::domain_error if an array index begins with '0'
std::invalid_argument if an array index was not a number
Definition at line 11515 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, nlohmann::detail::null, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::operator[]().
         {
             for (const auto& reference_token : reference_tokens)
             {
                 // convert null values to arrays or objects before continuing
                 if (ptr->m_type == value_t::null)
                 {
                     // check if reference token is a number
                     const bool nums = std::all_of(reference_token.begin(),
                                                   reference_token.end(),
                                                   [](const char x)
                     {
                         return std::isdigit(x);
                     });
                     // change value to array for numbers or "-" or to object
                     // otherwise
                     if (nums or reference_token == "-")
                     {
                         *ptr = value_t::array;
                     }
                     else
                     {
                         *ptr = value_t::object;
                     }
                 }
                 switch (ptr->m_type)
                 {
                     case value_t::object:
                     {
                         // use unchecked object access
                         ptr = &ptr->operator[](reference_token);
                         break;
                     }
                     case value_t::array:
                     {
                         // error condition (cf. RFC 6901, Sect. 4)
                         if (reference_token.size() > 1 and reference_token[0] == '0')
{
                             JSON_THROW(std::domain_error("array index must not begin with '0'"));
                         }
                         if (reference_token == "-")
{
                             // explicitly treat "-" as index beyond the end
                             ptr = &ptr->operator[](ptr->m_value.array->size());
                         }
                         else
{
                             // convert array index to number; unchecked access
                             ptr = &ptr->operator[](static_cast<size_type>(std::stoi(reference_token)));
                         }
                         break;
                     }
                     default:
                     {
                         JSON_THROW(std::out_of_range("unresolved reference token '" + reference_token + "'"));
                     }
                 }
             }
             return *ptr;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const_reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_unchecked (const_pointer ptr) const inline private
return a const reference to the pointed to value
Parameters
[in] ptr a JSON value
Returns
const reference to the JSON value pointed to by the JSON pointer
Definition at line 11634 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             for (const auto& reference_token : reference_tokens)
             {
                 switch (ptr->m_type)
                 {
                     case value_t::object:
                     {
                         // use unchecked object access
                         ptr = &ptr->operator[](reference_token);
                         break;
                     }
                     case value_t::array:
                     {
                         if (reference_token == "-")
{
                             // "-" cannot be used for const access
                             throw std::out_of_range("array index '-' (" +
                                                     std::to_string(ptr->m_value.array->size()) +
                                                     ") is out of range");
                         }
                         // error condition (cf. RFC 6901, Sect. 4)
                         if (reference_token.size() > 1 and reference_token[0] == '0')
{
                             JSON_THROW(std::domain_error("array index must not begin with '0'"));
                         }
                         // use unchecked array access
                         ptr = &ptr->operator[](static_cast<size_type>(std::stoi(reference_token)));
                         break;
                     }
                     default:
                     {
                         JSON_THROW(std::out_of_range("unresolved reference token '" + reference_token + "'"));
                     }
                 }
             }
             return *ptr;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::is_root () const inline private
return whether pointer points to the root document
Definition at line 11418 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
         {
             return reference_tokens.empty();
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::operator std::string () const inline
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
{The example shows the result of to_string., json_pointer__to_string}
Since
version 2.0.0
Definition at line 11398 of file json.hpp.
         {
             return to_string();
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::string nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::pop_back () inline private
remove and return last reference pointer
Definition at line 11405 of file json.hpp.
References JSON_THROW.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
         {
             if (is_root())
             {
                 JSON_THROW(std::domain_error("JSON pointer has no parent"));
             }
             auto last = reference_tokens.back();
             reference_tokens.pop_back();
             return last;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::replace_substring (std::string & s, const std::string & f, const std::string & t) inline static private
replace all occurrences of a substring by another string
Parameters
[in,out] s the string to manipulate; changed so that all occurrences of f are replaced with t
[in] f the substring to replace with t
[in] t the string to replace f
Precondition
The search string f must not be empty.
Since
version 2.0.0
Definition at line 11796 of file json.hpp.
         {
             assert(not f.empty());
             for (
                 size_t pos = s.find(f);         // find first occurrence of f
                 pos != std::string::npos;       // make sure f was found
                 s.replace(pos, f.size(), t),    // replace with t
                 pos = s.find(f, pos + t.size()) // find next occurrence of f
             );
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static std::vector<std::string> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::split (const std::string & reference_string) inline static private
split the string input to reference tokens
Definition at line 11723 of file json.hpp.
References JSON_THROW.
         {
             std::vector<std::string> result;
             // special case: empty reference string -> no reference tokens
             if (reference_string.empty())
             {
                 return result;
             }
             // check if nonempty reference string begins with slash
             if (reference_string[0] != '/')
             {
                 JSON_THROW(std::domain_error("JSON pointer must be empty or begin with '/'"));
             }
             // extract the reference tokens:
             // - slash: position of the last read slash (or end of string)
             // - start: position after the previous slash
             for (
                 // search for the first slash after the first character
                 size_t slash = reference_string.find_first_of('/', 1),
                 // set the beginning of the first reference token
                 start = 1;
                 // we can stop if start == string::npos+1 = 0
                 start != 0;
                 // set the beginning of the next reference token
                 // (will eventually be 0 if slash == std::string::npos)
                 start = slash + 1,
                 // find next slash
                 slash = reference_string.find_first_of('/', start))
             {
                 // use the text between the beginning of the reference token
                 // (start) and the last slash (slash).
                 auto reference_token = reference_string.substr(start, slash - start);
                 // check reference tokens are properly escaped
                 for (size_t pos = reference_token.find_first_of('~');
                         pos != std::string::npos;
                         pos = reference_token.find_first_of('~', pos + 1))
                 {
                     assert(reference_token[pos] == '~');
                     // ~ must be followed by 0 or 1
                     if (pos == reference_token.size() - 1 or
                             (reference_token[pos + 1] != '0' and
                              reference_token[pos + 1] != '1'))
                     {
                         JSON_THROW(std::domain_error("escape error: '~' must be followed with '0' or '1'"));
                     }
                 }
                 // finally, store the reference token
                 unescape(reference_token);
                 result.push_back(reference_token);
             }
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::string nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::to_string () const inline noexcept
return a string representation of the JSON pointer
Invariant
For each JSON pointer ptr, it holds:
ptr == json_pointer(ptr.to_string());
Returns
a string representation of the JSON pointer
{The example shows the result of to_string., json_pointer__to_string}
Since
version 2.0.0
Definition at line 11387 of file json.hpp.
References nlohmann::detail::string.
         {
             return std::accumulate(reference_tokens.begin(),
                                    reference_tokens.end(), std::string{},
                                    [](const std::string & a, const std::string & b)
             {
                 return a + "/" + escape(b);
             });
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> json_pointer nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::top () const inline private
Definition at line 11423 of file json.hpp.
References JSON_THROW, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::reference_tokens.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::patch().
         {
             if (is_root())
             {
                 JSON_THROW(std::domain_error("JSON pointer has no parent"));
             }
             json_pointer result = *this;
             result.reference_tokens = {reference_tokens[0]};
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::unescape (std::string & s) inline static private
unescape tilde and slash
Definition at line 11820 of file json.hpp.
         {
             // first transform any occurrence of the sequence '~1' to '/'
             replace_substring(s, "~1", "/");
             // then transform any occurrence of the sequence '~0' to '~'
             replace_substring(s, "~0", "~");
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> static basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::unflatten (const basic_json & value) inline static private
Parameters
[in] value flattened JSON
Returns
unflattened JSON
Definition at line 11893 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::get_and_create(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_object(), JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::m_value, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_value::object.
         {
             if (not value.is_object())
             {
                 JSON_THROW(std::domain_error("only objects can be unflattened"));
             }
             basic_json result;
             // iterate the JSON object values
             for (const auto& element : *value.m_value.object)
             {
                 if (not element.second.is_primitive())
                 {
                     JSON_THROW(std::domain_error("values in object must be primitive"));
                 }
                 // assign value to reference pointed to by JSON pointer; Note
                 // that if the JSON pointer is "" (i.e., points to the whole
                 // value), function get_and_create returns a reference to
                 // result itself. An assignment will then create a primitive
                 // value.
                 json_pointer(element.first).get_and_create(result) = element.second;
             }
             return result;
         }
Friends And Related Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> friend class basic_json friend
allow basic_json to access private members
Definition at line 11343 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator!= (json_pointer const & lhs, json_pointer const & rhs) friend
Definition at line 11928 of file json.hpp.
         {
             return !(lhs == rhs);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> bool operator== (json_pointer const & lhs, json_pointer const & rhs) friend
Definition at line 11922 of file json.hpp.
         {
             return lhs.reference_tokens == rhs.reference_tokens;
         }
Field Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> std::vector<std::string> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::reference_tokens {} private
the reference tokens
Definition at line 11935 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::json_pointer::top().
The documentation for this class was generated from the following file:
src/json.hpp