Virtual Zoo: MantaRay Class Reference
MantaRay Class Reference
#include <manta_ray.h>
Public Member Functions
MantaRay (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan MantaRay dengan inisial 'Q' dan ID i.
void Interact ()
Menampilkan aksi binatang ke layar.
int GetJmlMakanan ()
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Karnivora.
Public Member Functions inherited from Rajiformes
Rajiformes (char c, int i)
Constructor. Menciptakan Rajiformes dengan memanggil constructor WaterAnimal berinisial c dan ID i.
Public Member Functions inherited from WaterAnimal
WaterAnimal (char c, int i)
Constructor. Menciptakan WaterAnimal dengan cara memanggil constructor Animal berinisial c dan ID i.
Public Member Functions inherited from Animal
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
Public Member Functions inherited from Karnivora
void SetAmount (int n)
Setter daging.
int GetAmount ()
Getter daging.
Private Attributes
string aksi
const int rasio =400
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Protected Attributes inherited from Karnivora
int daging
Detailed Description
Kelas MantaRay turunan dari Rajiformes dan Karnivora
Definition at line 8 of file manta_ray.h.
Constructor & Destructor Documentation
MantaRay::MantaRay (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan MantaRay dengan inisial 'Q' dan ID i.
Parameters
i Nilai Id Animal yang diciptakan
x Posisi x Animal yang diciptakan
y Posisi y Animal yang diciptakan
massa berat Animal yang diciptakan
jinak nilai jinak Animal yang diciptakan
Definition at line 4 of file manta_ray.cpp.
References aksi, rasio, Karnivora::SetAmount(), Animal::SetJinak(), Animal::SetMassa(), Animal::SetX(), and Animal::SetY().
                                                             :
   Rajiformes('Q',i) {
   aksi = "swim! jump!";
   SetAmount(massa/rasio);
   SetMassa(massa);
   SetJinak(jinak);
   SetX(x);
   SetY(y);
 }
Member Function Documentation
int MantaRay::GetJmlMakanan () virtual
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Karnivora.
Returns
Jumlah makanan dari binatang.
Implements Animal.
Definition at line 16 of file manta_ray.cpp.
References Karnivora::GetAmount().
Referenced by TEST().
{
   Karnivora::GetAmount();
 }
void MantaRay::Interact () virtual
Menampilkan aksi binatang ke layar.
Implements Animal.
Definition at line 13 of file manta_ray.cpp.
References aksi.
Referenced by TEST().
{
   cout << "MantaRay: (" << aksi<< ")" << endl;
 }
Field Documentation
string MantaRay::aksi private
Definition at line 29 of file manta_ray.h.
Referenced by Interact(), and MantaRay().
const int MantaRay::rasio =400 private
Definition at line 30 of file manta_ray.h.
Referenced by MantaRay().
The documentation for this class was generated from the following files:
src/manta_ray.h
src/manta_ray.cpp