Virtual Zoo: Cell Class Reference
Cell Class Reference
#include <cell.h>
Public Member Functions
Cell (char c, int x, int y)
Constructor. Menciptakan Cell kosong dengan type c, posisi <x,y>.
virtual void Render ()
Menampilkan type cell Menuliskan type dari cell ke layar.
char GetType ()
Getter type.
Cage * GetCage ()
Getter cage.
void SetCage (Cage *c)
Setter cage. Merubah nilai cage dari cell.
Animal * GetAnimal ()
Getter Animal.
void SetAnimal (Animal *a)
Setter animal. Merubah nilai animal dari cell.
int GetAbsis ()
Getter absis.
int GetOrdinat ()
Getter absis.
Protected Attributes
Cage * cage
Animal * animal
const char type
const int absis
const int ordinat
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Detailed Description
Kelas Cell menyimpan informasi cage dan animal inherit kelas Renderable
Definition at line 14 of file cell.h.
Constructor & Destructor Documentation
Cell::Cell (char c, int x, int y)
Constructor. Menciptakan Cell kosong dengan type c, posisi <x,y>.
Parameters
c Nilai type Cell yang ingin dibuat
x Nilai absis Cell yang ingin dibuat
y Nilai ordinat Cell yang ingin dibuat
Definition at line 5 of file cell.cpp.
References animal, and cage.
                               : type(c), absis(x), ordinat(y) {
   cage=NULL;
   animal=NULL;
 }
Member Function Documentation
int Cell::GetAbsis ()
Getter absis.
Returns
absis
Definition at line 55 of file cell.cpp.
References absis.
Referenced by Driver::InitPosition(), TEST(), and Driver::TourVirtualZoo().
                    {
   return absis;
 }
Animal * Cell::GetAnimal ()
Getter Animal.
Returns
animal
Definition at line 26 of file cell.cpp.
References animal.
Referenced by Driver::MoveAnimal(), SetAnimal(), TEST(), and Driver::TourVirtualZoo().
{
   return animal;
 }
Cage * Cell::GetCage ()
Getter cage.
Returns
cage
Definition at line 18 of file cell.cpp.
References cage.
Referenced by Driver::InitAnimal(), Driver::MoveAnimal(), and TEST().
                     {
   return cage;
 }
int Cell::GetOrdinat ()
Getter absis.
Returns
absis
Definition at line 59 of file cell.cpp.
References ordinat.
Referenced by Driver::InitPosition(), TEST(), and Driver::TourVirtualZoo().
                      {
   return ordinat;
 }
char Cell::GetType ()
Getter type.
Returns
type
Definition at line 10 of file cell.cpp.
References type.
Referenced by Driver::InitZoo(), TEST(), and Driver::TourVirtualZoo().
                    {
   return type;
 }
void Cell::Render () virtual
Menampilkan type cell Menuliskan type dari cell ke layar.
Implements Renderable.
Reimplemented in Road, Habitat, Park, and Restaurant.
Definition at line 14 of file cell.cpp.
Referenced by Driver::DisplayVirtualZoo().
                   {
   cout<<type<<endl;
 }
void Cell::SetAnimal (Animal * a)
Setter animal. Merubah nilai animal dari cell.
Parameters
a Nilai animal yang ingin dimasukkan kedalam cell
Definition at line 30 of file cell.cpp.
References animal, GetAnimal(), Animal::GetHabitat(), and type.
Referenced by Driver::InitAnimal(), Driver::MoveAnimal(), and TEST().
{
   if(a==NULL) {
     animal = NULL;
   } else {
       bool found  = false;
       int i = 0;
       while (i < a->GetHabitat().size() && !found) {
         if (a->GetHabitat()[i] == this->type) {
           found = true;
         }
         i++;
       }
       if (found) {
         if(this->GetAnimal()==NULL) {
           animal = a;
         } else {
             throw ZooExp(7);
         }
       } else {
          throw ZooExp(1);
       }
   }
 }
void Cell::SetCage (Cage * c)
Setter cage. Merubah nilai cage dari cell.
Parameters
c Nilai cage yang ingin dimasukkan kedalam cell
Definition at line 22 of file cell.cpp.
References cage.
Referenced by TEST().
{
   cage=c;
 }
Field Documentation
const int Cell::absis protected
Definition at line 60 of file cell.h.
Referenced by GetAbsis().
Animal* Cell::animal protected
Definition at line 58 of file cell.h.
Referenced by Cell(), GetAnimal(), Habitat::Render(), and SetAnimal().
Cage* Cell::cage protected
Definition at line 57 of file cell.h.
Referenced by Cell(), GetCage(), Habitat::Render(), and SetCage().
const int Cell::ordinat protected
Definition at line 61 of file cell.h.
Referenced by GetOrdinat().
const char Cell::type protected
Definition at line 59 of file cell.h.
Referenced by GetType(), and SetAnimal().
The documentation for this class was generated from the following files:
src/cell.h
src/cell.cpp