Virtual Zoo: Buaya Class Reference
Buaya Class Reference
#include <buaya.h>
Public Member Functions
Buaya (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Buaya dengan inisial 'D' dan ID i.
void Interact ()
Menampilkan aksi binatang ke layar.
int GetJmlMakanan ()
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Karnivora.
Public Member Functions inherited from Crocodillia
Crocodillia (char c, int i)
Constructor. Menciptakan Crocodilla dengan memanggil constructor Land_WaterAnimal berinisial c dan ID i.
Public Member Functions inherited from Land_WaterAnimal
Land_WaterAnimal (char c, int i)
Constructor. Menciptakan Lan_WaterdAnimal dengan cara memanggil constructor Animal berinisial c dan ID i.
Public Member Functions inherited from Animal
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
Public Member Functions inherited from Karnivora
void SetAmount (int n)
Setter daging.
int GetAmount ()
Getter daging.
Private Attributes
string aksi
const int rasio =200
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Protected Attributes inherited from Karnivora
int daging
Detailed Description
Kelas Buaya turunan dari Crocodillia dan Karnivora
Definition at line 8 of file buaya.h.
Constructor & Destructor Documentation
Buaya::Buaya (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Buaya dengan inisial 'D' dan ID i.
Parameters
i Nilai Id Animal yang diciptakan
x Posisi x Animal yang diciptakan
y Posisi y Animal yang diciptakan
massa berat Animal yang diciptakan
jinak nilai jinak Animal yang diciptakan
Definition at line 4 of file buaya.cpp.
References aksi, rasio, Karnivora::SetAmount(), Animal::SetJinak(), Animal::SetMassa(), Animal::SetX(), and Animal::SetY().
                                                       : Crocodillia('D',i) {
   aksi = "open mouth";
   SetAmount(massa/rasio);
   SetMassa(massa);
   SetJinak(jinak);
   SetX(x);
   SetY(y);
 }
Member Function Documentation
int Buaya::GetJmlMakanan () virtual
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Karnivora.
Returns
Jumlah makanan dari binatang.
Implements Animal.
Definition at line 15 of file buaya.cpp.
References Karnivora::GetAmount().
Referenced by TEST().
{
   Karnivora::GetAmount();
 }
void Buaya::Interact () virtual
Menampilkan aksi binatang ke layar.
Implements Animal.
Definition at line 12 of file buaya.cpp.
References aksi.
Referenced by TEST().
                       {
   cout <<"Buaya: ("<< aksi << ")" << endl;
 }
Field Documentation
string Buaya::aksi private
Definition at line 29 of file buaya.h.
Referenced by Buaya(), and Interact().
const int Buaya::rasio =200 private
Definition at line 30 of file buaya.h.
Referenced by Buaya().
The documentation for this class was generated from the following files:
src/buaya.h
src/buaya.cpp