Virtual Zoo: AnimalHandler Class Reference
AnimalHandler Class Reference
#include <animal_handler.h>
Public Member Functions
AnimalHandler ()
Constructor. inisiasi n dengan 0.
~AnimalHandler ()
Destructor.
Animal * GetAnimal (int id)
Getter elemen animal.
int NbAnimal ()
Mengetahui jumlah animal.
void AddAnimal (Animal *a)
Menambahkan animal kedalam list_animal.
int JumlahMakanan ()
Mengembalikan jumlah makanan dari seluruh animal Mengiterasi list_animal dan menjumlahkan makanan dari tiap animal.
Private Attributes
vector< Animal * > list_animal
int n
Detailed Description
Kelas AnimalHandler terdiri atas list animal yang pernah diciptakan
Definition at line 10 of file animal_handler.h.
Constructor & Destructor Documentation
AnimalHandler::AnimalHandler ()
Constructor. inisiasi n dengan 0.
Definition at line 4 of file animal_handler.cpp.
{
   n=0;
 }
AnimalHandler::~AnimalHandler ()
Destructor.
Definition at line 16 of file animal_handler.cpp.
{
   for(int i=0; i<n; i++){
     delete list_animal[i];
   }
 }
Member Function Documentation
void AnimalHandler::AddAnimal (Animal * a)
Menambahkan animal kedalam list_animal.
Parameters
a Animal yang ingin ditambahkan ke list_animal
Definition at line 22 of file animal_handler.cpp.
Referenced by Driver::InitAnimal(), and TEST().
{
   list_animal.push_back(a);
   n++;
 }
Animal * AnimalHandler::GetAnimal (int id)
Getter elemen animal.
Parameters
id nilai id animal yang ingin diketahui
Returns
list_animal[id]
Definition at line 8 of file animal_handler.cpp.
Referenced by Driver::MoveAnimal(), and TEST().
{
   return list_animal[id];
 }
int AnimalHandler::JumlahMakanan ()
Mengembalikan jumlah makanan dari seluruh animal Mengiterasi list_animal dan menjumlahkan makanan dari tiap animal.
Returns
jumlah makanan dari seluruh animal
Definition at line 27 of file animal_handler.cpp.
Referenced by main(), and TEST().
{
   int sum = 0;
   for(int i=0; i<list_animal.size(); i++) {
     sum+=list_animal[i]->GetJmlMakanan();
   }
   return sum;
 }
int AnimalHandler::NbAnimal ()
Mengetahui jumlah animal.
Returns
n
Definition at line 12 of file animal_handler.cpp.
Referenced by Driver::MoveAnimal(), and TEST().
{
   return n;
 }
Field Documentation
vector<Animal*> AnimalHandler::list_animal private
Definition at line 39 of file animal_handler.h.
int AnimalHandler::n private
Definition at line 40 of file animal_handler.h.
The documentation for this class was generated from the following files:
src/animal_handler.h
src/animal_handler.cpp