Virtual Zoo: CageHandler Class Reference
CageHandler Class Reference
#include <cage_handler.h>
Public Member Functions
CageHandler ()
Constructor Menciptakan CageHandler dengan n=0.
~CageHandler ()
Destructor.
Cage * GetCage (int id)
Getter elemen list_cage.
int NbCage ()
Mengetahui banyak cage yang diciptakan.
void AddCage (Cage *c)
Menambahkan cage kedalam list_cage.
Private Attributes
vector< Cage * > list_cage
int n
Detailed Description
Kelas CageHandler terdiri dari semua cage yang pernah diciptakan
Definition at line 10 of file cage_handler.h.
Constructor & Destructor Documentation
CageHandler::CageHandler ()
Constructor Menciptakan CageHandler dengan n=0.
Definition at line 3 of file cage_handler.cpp.
References n.
{
   n=0;
 }
CageHandler::~CageHandler ()
Destructor.
Definition at line 27 of file cage_handler.cpp.
References list_cage, and n.
{
   for(int i = 0; i < n; i++) {
     delete list_cage[i];
   }
 }
Member Function Documentation
void CageHandler::AddCage (Cage * c)
Menambahkan cage kedalam list_cage.
Parameters
c elemen yang ingin ditambahkan ke list_cage
Definition at line 33 of file cage_handler.cpp.
References list_cage, and n.
Referenced by Driver::InitCage(), and TEST().
{
   list_cage.push_back(c);
   n++;
 }
Cage * CageHandler::GetCage (int id)
Getter elemen list_cage.
Parameters
id Nilai posisi elemen yang ingin didapatkan
Returns
list_cage[id]
Definition at line 7 of file cage_handler.cpp.
References list_cage, and n.
Referenced by Driver::InitZoo(), and TEST().
{
   bool found = false;
   int i = 0;
   while((!found) && (i<n)) {
     if(list_cage[i]->GetId()==id)
       found = true;
     else
       i++;
   }
   if(found)
     return list_cage[i];
   else
     return NULL;
 }
int CageHandler::NbCage ()
Mengetahui banyak cage yang diciptakan.
Returns
n
Definition at line 23 of file cage_handler.cpp.
References n.
Referenced by TEST().
{
   return n;
 }
Field Documentation
vector<Cage*> CageHandler::list_cage private
Definition at line 34 of file cage_handler.h.
Referenced by AddCage(), GetCage(), and ~CageHandler().
int CageHandler::n private
Definition at line 35 of file cage_handler.h.
Referenced by AddCage(), CageHandler(), GetCage(), NbCage(), and ~CageHandler().
The documentation for this class was generated from the following files:
src/cage_handler.h
src/cage_handler.cpp