Virtual Zoo: Karnivora Class Reference
Karnivora Class Reference
#include <karnivora.h>
Public Member Functions
void SetAmount (int n)
Setter daging.
int GetAmount ()
Getter daging.
Protected Attributes
int daging
Detailed Description
Kelas Karnivora menyimpan informasi makanan berupa daging
Definition at line 9 of file karnivora.h.
Member Function Documentation
int Karnivora::GetAmount () virtual
Getter daging.
Returns
daging
Implements Pemakan.
Definition at line 6 of file karnivora.cpp.
References daging.
Referenced by Aligator::GetJmlMakanan(), Buaya::GetJmlMakanan(), StingRay::GetJmlMakanan(), MantaRay::GetJmlMakanan(), Macan::GetJmlMakanan(), Garuda::GetJmlMakanan(), HiuMartil::GetJmlMakanan(), HiuKarpet::GetJmlMakanan(), HarimauSumatra::GetJmlMakanan(), Komodo::GetJmlMakanan(), Elang::GetJmlMakanan(), and TEST().
{
   return daging;
 }
void Karnivora::SetAmount (int n)
Setter daging.
Parameters
n Jumlah daging yang diinginkan
Definition at line 3 of file karnivora.cpp.
References daging.
Referenced by Aligator::Aligator(), Buaya::Buaya(), Elang::Elang(), Garuda::Garuda(), HarimauSumatra::HarimauSumatra(), HiuKarpet::HiuKarpet(), HiuMartil::HiuMartil(), Komodo::Komodo(), Macan::Macan(), MantaRay::MantaRay(), StingRay::StingRay(), and TEST().
{
   daging = n;
 }
Field Documentation
int Karnivora::daging protected
Definition at line 21 of file karnivora.h.
Referenced by GetAmount(), and SetAmount().
The documentation for this class was generated from the following files:
src/karnivora.h
src/karnivora.cpp