Virtual Zoo: OrangUtan Class Reference
OrangUtan Class Reference
#include <orang_utan.h>
Public Member Functions
OrangUtan (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan OrangUtan dengan inisial 'U' dan ID i.
void Interact ()
Menampilkan suara binatang ke layar.
int GetJmlMakanan ()
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Omnivora.
Public Member Functions inherited from Primate
Primate (char c, int i)
Constructor. Menciptakan Primate dengan memanggil constructor LandAnimal berinisial c dan ID i.
Public Member Functions inherited from LandAnimal
LandAnimal (char c, int i)
Constructor. Menciptakan LandAnimal menciptakan Animal berinisial c dan ID i.
Public Member Functions inherited from Animal
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
Public Member Functions inherited from Omnivora
void SetAmount (int n)
Setter daging_tumbuhan.
int GetAmount ()
Getter daging_tumbuhan.
Private Attributes
string suara
const int rasio =15
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Protected Attributes inherited from Omnivora
int daging_tumbuhan
Detailed Description
Kelas OrangUtan turunan dari kelas Primate dan Omnivora
Definition at line 11 of file orang_utan.h.
Constructor & Destructor Documentation
OrangUtan::OrangUtan (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan OrangUtan dengan inisial 'U' dan ID i.
Parameters
i Nilai Id Animal yang diciptakan
x Posisi x Animal yang diciptakan
y Posisi y Animal yang diciptakan
massa berat Animal yang diciptakan
jinak nilai jinak Animal yang diciptakan
Definition at line 4 of file orang_utan.cpp.
References rasio, Omnivora::SetAmount(), Animal::SetJinak(), Animal::SetMassa(), Animal::SetX(), Animal::SetY(), and suara.
                                                               :
   Primate('U',i) {
   suara = "Auooo";
   SetAmount(massa/rasio);
   SetMassa(massa);
   SetJinak(jinak);
   SetX(x);
   SetY(y);
 }
Member Function Documentation
int OrangUtan::GetJmlMakanan () virtual
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Omnivora.
Returns
Jumlah makanan dari binatang.
Implements Animal.
Definition at line 16 of file orang_utan.cpp.
References Omnivora::GetAmount().
Referenced by TEST().
{
   Omnivora::GetAmount();
 }
void OrangUtan::Interact () virtual
Menampilkan suara binatang ke layar.
Implements Animal.
Definition at line 13 of file orang_utan.cpp.
References suara.
Referenced by TEST().
{
   cout << "Orang Utan: \""<< suara <<"\""<< endl;
 }
Field Documentation
const int OrangUtan::rasio =15 private
Definition at line 33 of file orang_utan.h.
Referenced by OrangUtan().
string OrangUtan::suara private
Definition at line 32 of file orang_utan.h.
Referenced by Interact(), and OrangUtan().
The documentation for this class was generated from the following files:
src/orang_utan.h
src/orang_utan.cpp