Virtual Zoo: nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U > Class Template Reference
nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U > Class Template Reference
a template for a random access iterator for the basic_json class
#include <json.hpp>
Public Types
using value_type = typename basic_json::value_type
the type of the values when the iterator is dereferenced
using difference_type = typename basic_json::difference_type
a type to represent differences between iterators
using pointer = typename std::conditional< std::is_const< U >::value, typename basic_json::const_pointer, typename basic_json::pointer >::type
defines a pointer to the type iterated over (value_type)
using reference = typename std::conditional< std::is_const< U >::value, typename basic_json::const_reference, typename basic_json::reference >::type
defines a reference to the type iterated over (value_type)
using iterator_category = std::bidirectional_iterator_tag
the category of the iterator
Public Member Functions
iter_impl ()=default
default constructor
iter_impl (pointer object) noexcept
constructor for a given JSON instance
operator const_iterator () const
iter_impl (const iter_impl &other) noexcept
copy constructor
iter_impl & operator= (iter_impl other) noexcept(std::is_nothrow_move_constructible< pointer >::value andstd::is_nothrow_move_assignable< pointer >::value andstd::is_nothrow_move_constructible< internal_iterator >::value andstd::is_nothrow_move_assignable< internal_iterator >::value)
copy assignment
reference operator* () const
return a reference to the value pointed to by the iterator
pointer operator-> () const
dereference the iterator
iter_impl operator++ (int)
post-increment (it++)
iter_impl & operator++ ()
pre-increment (++it)
iter_impl operator-- (int)
post-decrement (it–)
iter_impl & operator-- ()
pre-decrement (–it)
bool operator== (const iter_impl &other) const
comparison: equal
bool operator!= (const iter_impl &other) const
comparison: not equal
bool operator< (const iter_impl &other) const
comparison: smaller
bool operator<= (const iter_impl &other) const
comparison: less than or equal
bool operator> (const iter_impl &other) const
comparison: greater than
bool operator>= (const iter_impl &other) const
comparison: greater than or equal
iter_impl & operator+= (difference_type i)
add to iterator
iter_impl & operator-= (difference_type i)
subtract from iterator
iter_impl operator+ (difference_type i)
add to iterator
iter_impl operator- (difference_type i)
subtract from iterator
difference_type operator- (const iter_impl &other) const
return difference
reference operator[] (difference_type n) const
access to successor
object_t::key_type key () const
return the key of an object iterator
reference value () const
return the value of an iterator
Private Member Functions
void set_begin () noexcept
set the iterator to the first value
void set_end () noexcept
set the iterator past the last value
Private Attributes
pointer m_object = nullptr
associated JSON instance
internal_iterator m_it = internal_iterator()
the actual iterator of the associated instance
Friends
class basic_json
allow basic_json to access private members
Detailed Description
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer>
template<typename U>
class nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >
a template for a random access iterator for the basic_json class
This class implements a both iterators (iterator and const_iterator) for the basic_json class.
Note
An iterator is called initialized when a pointer to a JSON value has been set (e.g., by a constructor or a copy assignment). If the iterator is default-constructed, it is uninitialized and most methods are undefined. The library uses assertions to detect calls on uninitialized iterators.
The class satisfies the following concept requirements:
RandomAccessIterator: The iterator that can be moved to point (forward and backward) to any element in constant time.
Since
version 1.0.0, simplified in version 2.0.9
Definition at line 1050 of file json.hpp.
Member Typedef Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::difference_type = typename basic_json::difference_type
a type to represent differences between iterators
Definition at line 8728 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::iterator_category = std::bidirectional_iterator_tag
the category of the iterator
Definition at line 8738 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::pointer = typename std::conditional<std::is_const<U>::value, typename basic_json::const_pointer, typename basic_json::pointer>::type
defines a pointer to the type iterated over (value_type)
Definition at line 8732 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::reference = typename std::conditional<std::is_const<U>::value, typename basic_json::const_reference, typename basic_json::reference>::type
defines a reference to the type iterated over (value_type)
Definition at line 8736 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > using nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::value_type = typename basic_json::value_type
the type of the values when the iterator is dereferenced
Definition at line 8726 of file json.hpp.
Constructor & Destructor Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::iter_impl () default
default constructor
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::iter_impl (pointer object) inline explicit noexcept
constructor for a given JSON instance
Parameters
[in] object pointer to a JSON object for this iterator
Precondition
object != nullptr
Postcondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8749 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
             : m_object(object)
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     m_it.object_iterator = typename object_t::iterator();
                     break;
                 }
                 case basic_json::value_t::array:
                 {
                     m_it.array_iterator = typename array_t::iterator();
                     break;
                 }
                 default:
                 {
                     m_it.primitive_iterator = primitive_iterator_t();
                     break;
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::iter_impl (const iter_impl< U > & other) inline noexcept
copy constructor
Parameters
[in] other iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 8802 of file json.hpp.
             : m_object(other.m_object), m_it(other.m_it)
         {}
Member Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > object_t::key_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::key () const inline
return the key of an object iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9283 of file json.hpp.
References JSON_THROW.
         {
             assert(m_object != nullptr);
             if (m_object->is_object())
             {
                 return m_it.object_iterator->first;
             }
             JSON_THROW(std::domain_error("cannot use key() for non-object iterators"));
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator const_iterator () const inline
Definition at line 8784 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object.
         {
             const_iterator ret;
             if (m_object)
             {
                 ret.m_object = m_object;
                 ret.m_it = m_it;
             }
             return ret;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator!= (const iter_impl< U > & other) const inline
comparison: not equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9088 of file json.hpp.
         {
             return not operator==(other);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator* () const inline
return a reference to the value pointed to by the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8896 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     assert(m_it.object_iterator != m_object->m_value.object->end());
                     return m_it.object_iterator->second;
                 }
                 case basic_json::value_t::array:
                 {
                     assert(m_it.array_iterator != m_object->m_value.array->end());
                     return *m_it.array_iterator;
                 }
                 case basic_json::value_t::null:
                 {
                     JSON_THROW(std::out_of_range("cannot get value"));
                 }
                 default:
                 {
                     if (m_it.primitive_iterator.is_begin())
                     {
                         return *m_object;
                     }
                     JSON_THROW(std::out_of_range("cannot get value"));
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator+ (difference_type i) inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9197 of file json.hpp.
         {
             auto result = *this;
             result += i;
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator++ (int) inline
post-increment (it++)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8969 of file json.hpp.
         {
             auto result = *this;
             ++(*this);
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator++ () inline
pre-increment (++it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8980 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     std::advance(m_it.object_iterator, 1);
                     break;
                 }
                 case basic_json::value_t::array:
                 {
                     std::advance(m_it.array_iterator, 1);
                     break;
                 }
                 default:
                 {
                     ++m_it.primitive_iterator;
                     break;
                 }
             }
             return *this;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator+= (difference_type i) inline
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9157 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     JSON_THROW(std::domain_error("cannot use offsets with object iterators"));
                 }
                 case basic_json::value_t::array:
                 {
                     std::advance(m_it.array_iterator, i);
                     break;
                 }
                 default:
                 {
                     m_it.primitive_iterator += i;
                     break;
                 }
             }
             return *this;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator- (difference_type i) inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9208 of file json.hpp.
         {
             auto result = *this;
             result -= i;
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > difference_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator- (const iter_impl< U > & other) const inline
return difference
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9219 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, nlohmann::detail::object, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::primitive_iterator.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     JSON_THROW(std::domain_error("cannot use offsets with object iterators"));
                 }
                 case basic_json::value_t::array:
                 {
                     return m_it.array_iterator - other.m_it.array_iterator;
                 }
                 default:
                 {
                     return m_it.primitive_iterator - other.m_it.primitive_iterator;
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator-- (int) inline
post-decrement (it–)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9012 of file json.hpp.
         {
             auto result = *this;
             --(*this);
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator-- () inline
pre-decrement (–it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9023 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     std::advance(m_it.object_iterator, -1);
                     break;
                 }
                 case basic_json::value_t::array:
                 {
                     std::advance(m_it.array_iterator, -1);
                     break;
                 }
                 default:
                 {
                     --m_it.primitive_iterator;
                     break;
                 }
             }
             return *this;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator-= (difference_type i) inline
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9188 of file json.hpp.
         {
             return operator+=(-i);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > pointer nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator-> () const inline
dereference the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8935 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     assert(m_it.object_iterator != m_object->m_value.object->end());
                     return &(m_it.object_iterator->second);
                 }
                 case basic_json::value_t::array:
                 {
                     assert(m_it.array_iterator != m_object->m_value.array->end());
                     return &*m_it.array_iterator;
                 }
                 default:
                 {
                     if (m_it.primitive_iterator.is_begin())
                     {
                         return m_object;
                     }
                     JSON_THROW(std::out_of_range("cannot get value"));
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator< (const iter_impl< U > & other) const inline
comparison: smaller
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9097 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object, nlohmann::detail::object, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::primitive_iterator.
         {
             // if objects are not the same, the comparison is undefined
             if (m_object != other.m_object)
             {
                 JSON_THROW(std::domain_error("cannot compare iterators of different containers"));
             }
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     JSON_THROW(std::domain_error("cannot compare order of object iterators"));
                 }
                 case basic_json::value_t::array:
                 {
                     return (m_it.array_iterator < other.m_it.array_iterator);
                 }
                 default:
                 {
                     return (m_it.primitive_iterator < other.m_it.primitive_iterator);
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator<= (const iter_impl< U > & other) const inline
comparison: less than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9130 of file json.hpp.
         {
             return not other.operator < (*this);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > iter_impl& nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator= (iter_impl< U > other) inline noexcept
copy assignment
Parameters
[in,out] other iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 8811 of file json.hpp.
         {
             std::swap(m_object, other.m_object);
             std::swap(m_it, other.m_it);
             return *this;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator== (const iter_impl< U > & other) const inline
comparison: equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9055 of file json.hpp.
References nlohmann::detail::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::array_iterator, JSON_THROW, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object, nlohmann::detail::object, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::object_iterator, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::internal_iterator::primitive_iterator.
         {
             // if objects are not the same, the comparison is undefined
             if (m_object != other.m_object)
             {
                 JSON_THROW(std::domain_error("cannot compare iterators of different containers"));
             }
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     return (m_it.object_iterator == other.m_it.object_iterator);
                 }
                 case basic_json::value_t::array:
                 {
                     return (m_it.array_iterator == other.m_it.array_iterator);
                 }
                 default:
                 {
                     return (m_it.primitive_iterator == other.m_it.primitive_iterator);
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator> (const iter_impl< U > & other) const inline
comparison: greater than
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9139 of file json.hpp.
         {
             return not operator<=(other);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > bool nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator>= (const iter_impl< U > & other) const inline
comparison: greater than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9148 of file json.hpp.
References nlohmann::detail::operator<().
         {
             return not operator<(other);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator[] (difference_type n) const inline
access to successor
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9246 of file json.hpp.
References nlohmann::detail::array, JSON_THROW, and nlohmann::detail::object.
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     JSON_THROW(std::domain_error("cannot use operator[] for object iterators"));
                 }
                 case basic_json::value_t::array:
                 {
                     return *std::next(m_it.array_iterator, n);
                 }
                 case basic_json::value_t::null:
                 {
                     JSON_THROW(std::out_of_range("cannot get value"));
                 }
                 default:
                 {
                     if (m_it.primitive_iterator.get_value() == -n)
                     {
                         return *m_object;
                     }
                     JSON_THROW(std::out_of_range("cannot get value"));
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_begin () inline private noexcept
set the iterator to the first value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8828 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::begin(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cbegin().
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     m_it.object_iterator = m_object->m_value.object->begin();
                     break;
                 }
                 case basic_json::value_t::array:
                 {
                     m_it.array_iterator = m_object->m_value.array->begin();
                     break;
                 }
                 case basic_json::value_t::null:
                 {
                     // set to end so begin()==end() is true: null is empty
                     m_it.primitive_iterator.set_end();
                     break;
                 }
                 default:
                 {
                     m_it.primitive_iterator.set_begin();
                     break;
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::set_end () inline private noexcept
set the iterator past the last value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 8865 of file json.hpp.
References nlohmann::detail::array, and nlohmann::detail::object.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::cend(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end().
         {
             assert(m_object != nullptr);
             switch (m_object->m_type)
             {
                 case basic_json::value_t::object:
                 {
                     m_it.object_iterator = m_object->m_value.object->end();
                     break;
                 }
                 case basic_json::value_t::array:
                 {
                     m_it.array_iterator = m_object->m_value.array->end();
                     break;
                 }
                 default:
                 {
                     m_it.primitive_iterator.set_end();
                     break;
                 }
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > reference nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::value () const inline
return the value of an iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 9299 of file json.hpp.
         {
             return operator*();
         }
Friends And Related Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > friend class basic_json friend
allow basic_json to access private members
Definition at line 8717 of file json.hpp.
Field Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > internal_iterator nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_it = internal_iterator() private
the actual iterator of the associated instance
Definition at line 9308 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator const_iterator(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator-(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator<(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator==().
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<typename U > pointer nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::m_object = nullptr private
associated JSON instance
Definition at line 9306 of file json.hpp.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator const_iterator(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator<(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::iter_impl< U >::operator==().
The documentation for this class was generated from the following file:
src/json.hpp