Virtual Zoo: Banteng Class Reference
Banteng Class Reference
#include <banteng.h>
Public Member Functions
Banteng (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Banteng dengan inisial 'A' dan ID i.
void Interact ()
Menampilkan aksi binatang ke layar.
int GetJmlMakanan ()
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Herbivora.
Public Member Functions inherited from Artiodactyl
Artiodactyl (char c, int i)
Constructor. Menciptakan Artiodactyl dengan memanggil constructor LandAnimal berinisial c dan ID i.
Public Member Functions inherited from LandAnimal
LandAnimal (char c, int i)
Constructor. Menciptakan LandAnimal menciptakan Animal berinisial c dan ID i.
Public Member Functions inherited from Animal
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
Public Member Functions inherited from Herbivora
void SetAmount (int n)
Setter tumbuhan.
int GetAmount ()
Getter tumbuhan.
Private Attributes
string aksi
const int rasio =100
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Protected Attributes inherited from Herbivora
int tumbuhan
Detailed Description
Kelas Banteng turunan dari Artiodactyl dan Herbivora
Definition at line 10 of file banteng.h.
Constructor & Destructor Documentation
Banteng::Banteng (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Banteng dengan inisial 'A' dan ID i.
Parameters
i Nilai Id Animal yang diciptakan
x Posisi x Animal yang diciptakan
y Posisi y Animal yang diciptakan
massa berat Animal yang diciptakan
jinak nilai jinak Animal yang diciptakan
Definition at line 4 of file banteng.cpp.
References aksi, rasio, Herbivora::SetAmount(), Animal::SetJinak(), Animal::SetMassa(), Animal::SetX(), and Animal::SetY().
                                                           :
   Artiodactyl('A',i) {
   aksi = "snort";
   SetAmount(massa/rasio);
   SetMassa(massa);
   SetJinak(jinak);
   SetX(x);
   SetY(y);
 }
Member Function Documentation
int Banteng::GetJmlMakanan () virtual
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Herbivora.
Returns
Jumlah makanan dari binatang.
Implements Animal.
Definition at line 16 of file banteng.cpp.
References Herbivora::GetAmount().
Referenced by TEST().
{
   Herbivora::GetAmount();
 }
void Banteng::Interact () virtual
Menampilkan aksi binatang ke layar.
Implements Animal.
Definition at line 13 of file banteng.cpp.
References aksi.
Referenced by TEST().
{
   cout <<"Banteng: ("<< aksi << ")" << endl;
 }
Field Documentation
string Banteng::aksi private
Definition at line 31 of file banteng.h.
Referenced by Banteng(), and Interact().
const int Banteng::rasio =100 private
Definition at line 32 of file banteng.h.
Referenced by Banteng().
The documentation for this class was generated from the following files:
src/banteng.h
src/banteng.cpp