Virtual Zoo: Herbivora Class Reference
Herbivora Class Reference
#include <herbivora.h>
Public Member Functions
void SetAmount (int n)
Setter tumbuhan.
int GetAmount ()
Getter tumbuhan.
Protected Attributes
int tumbuhan
Detailed Description
Kelas Herbivora menyimpan informasi makanan berupa tumbuhan
Definition at line 8 of file herbivora.h.
Member Function Documentation
int Herbivora::GetAmount () virtual
Getter tumbuhan.
Returns
tumbuhan
Implements Pemakan.
Definition at line 6 of file herbivora.cpp.
References tumbuhan.
Referenced by BadakCulaSatu::GetJmlMakanan(), Kancil::GetJmlMakanan(), Rusa::GetJmlMakanan(), Zebra::GetJmlMakanan(), Parkit::GetJmlMakanan(), Nuri::GetJmlMakanan(), Kakatua::GetJmlMakanan(), Iguana::GetJmlMakanan(), Banteng::GetJmlMakanan(), and TEST().
{
   return tumbuhan;
 }
void Herbivora::SetAmount (int n)
Setter tumbuhan.
Parameters
n Jumlah tumbuhan yang diinginkan
Definition at line 3 of file herbivora.cpp.
References tumbuhan.
Referenced by BadakCulaSatu::BadakCulaSatu(), Banteng::Banteng(), Iguana::Iguana(), Kakatua::Kakatua(), Kancil::Kancil(), Nuri::Nuri(), Parkit::Parkit(), Rusa::Rusa(), TEST(), and Zebra::Zebra().
{
   tumbuhan = n;
 }
Field Documentation
int Herbivora::tumbuhan protected
Definition at line 20 of file herbivora.h.
Referenced by GetAmount(), and SetAmount().
The documentation for this class was generated from the following files:
src/herbivora.h
src/herbivora.cpp