Virtual Zoo: Parkit Class Reference
Parkit Class Reference
#include <parkit.h>
Public Member Functions
Parkit (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Parkit dengan inisial 'F' dan ID i.
void Interact ()
Menampilkan suara binatang ke layar.
int GetJmlMakanan ()
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Herbivora.
Public Member Functions inherited from Prittaciformes
Prittaciformes (char c, int i)
Constructor. Menciptakan Prittaciformes dengan memanggil constructor FlyingAnimal berinisial c dan ID i.
Public Member Functions inherited from FlyingAnimal
FlyingAnimal (char c, int i)
Constructor. Menciptakan FlyingAnimal dengan cara memanggil constructor Animal berinisial c dan ID i.
Public Member Functions inherited from Animal
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
Public Member Functions inherited from Herbivora
void SetAmount (int n)
Setter tumbuhan.
int GetAmount ()
Getter tumbuhan.
Private Attributes
string suara
const int rasio =5
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Protected Attributes inherited from Herbivora
int tumbuhan
Detailed Description
Kelas Parkit turunan dari Prittaciformes dan Herbivora
Definition at line 8 of file parkit.h.
Constructor & Destructor Documentation
Parkit::Parkit (int i, int x, int y, int massa, bool jinak)
Constructor. Menciptakan Parkit dengan inisial 'F' dan ID i.
Parameters
i Nilai Id Animal yang diciptakan
x Posisi x Animal yang diciptakan
y Posisi y Animal yang diciptakan
massa berat Animal yang diciptakan
jinak nilai jinak Animal yang diciptakan
Definition at line 4 of file parkit.cpp.
References rasio, Herbivora::SetAmount(), Animal::SetJinak(), Animal::SetMassa(), Animal::SetX(), Animal::SetY(), and suara.
                                                         :
   Prittaciformes('F',i) {
   suara = "cuit cuit";
   SetAmount(massa/rasio);
   SetMassa(massa);
   SetJinak(jinak);
   SetX(x);
   SetY(y);
 }
Member Function Documentation
int Parkit::GetJmlMakanan () virtual
Melihat jumlah makanan dari binatang. Memanggil fungsi GetAmount parent Herbivora.
Returns
Jumlah makanan dari binatang.
Implements Animal.
Definition at line 16 of file parkit.cpp.
References Herbivora::GetAmount().
Referenced by TEST().
{
   Herbivora::GetAmount();
 }
void Parkit::Interact () virtual
Menampilkan suara binatang ke layar.
Implements Animal.
Definition at line 13 of file parkit.cpp.
References suara.
Referenced by TEST().
                       {
   cout << "Parkit: \"" << suara << "\"" << endl;
 }
Field Documentation
const int Parkit::rasio =5 private
Definition at line 29 of file parkit.h.
Referenced by Parkit().
string Parkit::suara private
Definition at line 28 of file parkit.h.
Referenced by Interact(), and Parkit().
The documentation for this class was generated from the following files:
src/parkit.h
src/parkit.cpp