Virtual Zoo: Animal Class Reference
Animal Class Reference abstract
#include <animal.h>
Public Member Functions
Animal (char c, int i)
Constructor.
void SetJinak (bool _jinak)
Setter jinak.
bool IsJinak ()
Mengecek apakah animal jinak.
char GetInisial ()
Getter inisial.
int GetID ()
Getter ID.
int GetMassa ()
Getter massa.
int GetPosisiX ()
Getter posisi x.
int GetPosisiY ()
Getter posisi y.
void SetMassa (int kg)
Setter massa.
void SetX (int _x)
Setter x.
void SetY (int _y)
Setter y.
void Render ()
Menampilkan karakter inisial dari animal ke layar.
vector< char > & GetHabitat ()
Getter type.
void AddHabitat (char c)
Menambahkan c kedalam type.
virtual int GetJmlMakanan ()=0
Getter jumlah makanan animal.
virtual void Interact ()=0
Menampilkan interaksi dari animal Menampilkan interaksi animal ke layar.
Private Attributes
int x
int y
int massa
bool jinak
const int ID
const char inisial
vector< char > type
Additional Inherited Members
Static Public Member Functions inherited from Renderable
static void Banner ()
Menampilkan banner virtual zoo.
static void Legend ()
Menampilkan legend zoo.
Detailed Description
Kelas Animal representasi binatang dengan posisi, massa dan ketentuan jinak.
Definition at line 11 of file animal.h.
Constructor & Destructor Documentation
Animal::Animal (char c, int i)
Constructor.
Parameters
c Nilai inisial Animal yang ingin diciptakan
i Nilai ID Animal yang ingin diciptakan
Definition at line 5 of file animal.cpp.
                             : inisial(c) , ID(i) {
 }
Member Function Documentation
void Animal::AddHabitat (char c)
Menambahkan c kedalam type.
Parameters
c nilai habitat animal yang ingin ditambahkan ke type
Definition at line 45 of file animal.cpp.
Referenced by FlyingAnimal::FlyingAnimal(), Land_AirAnimal::Land_AirAnimal(), Land_WaterAnimal::Land_WaterAnimal(), LandAnimal::LandAnimal(), TEST(), Water_AirAnimal::Water_AirAnimal(), and WaterAnimal::WaterAnimal().
{
   type.push_back(c);
 }
vector< char > & Animal::GetHabitat ()
Getter type.
Returns
type
Definition at line 42 of file animal.cpp.
References type.
Referenced by Cage::AddAnimal(), Cell::SetAnimal(), and TEST().
{
   return type;
 }
int Animal::GetID ()
Getter ID.
Returns
ID
Definition at line 36 of file animal.cpp.
References ID.
Referenced by TEST().
                   {
   return ID;
 }
char Animal::GetInisial ()
Getter inisial.
Returns
inisial
Definition at line 32 of file animal.cpp.
References inisial.
Referenced by Cage::AddAnimal(), and TEST().
{
   return inisial;
 }
virtual int Animal::GetJmlMakanan () pure virtual
Getter jumlah makanan animal.
Returns
Nilai makanan yang diperlukan animal
Implemented in OrangUtan, Banteng, Iguana, Kakatua, Aligator, BadakCulaSatu, Bekantan, Buaya, Elang, Garuda, HarimauSumatra, HiuKarpet, HiuMartil, Kancil, Komodo, Macan, MantaRay, Nuri, Parkit, Rusa, Siamang, StingRay, and Zebra.
int Animal::GetMassa ()
Getter massa.
Returns
massa
Definition at line 13 of file animal.cpp.
References massa.
Referenced by TEST().
                      {
   return massa;
 }
int Animal::GetPosisiX ()
Getter posisi x.
Returns
x
Definition at line 16 of file animal.cpp.
References x.
Referenced by Driver::MoveAnimal(), and TEST().
{
   return x;
 }
int Animal::GetPosisiY ()
Getter posisi y.
Returns
y
Definition at line 19 of file animal.cpp.
References y.
Referenced by Driver::MoveAnimal(), and TEST().
{
   return y;
 }
virtual void Animal::Interact () pure virtual
Menampilkan interaksi dari animal Menampilkan interaksi animal ke layar.
Implemented in OrangUtan, Banteng, Iguana, Kakatua, Aligator, BadakCulaSatu, Bekantan, Buaya, Elang, Garuda, HarimauSumatra, HiuKarpet, HiuMartil, Kancil, Komodo, Macan, MantaRay, Nuri, Parkit, Rusa, Siamang, StingRay, and Zebra.
Referenced by Driver::TourVirtualZoo().
bool Animal::IsJinak ()
Mengecek apakah animal jinak.
Returns
jinak
Definition at line 10 of file animal.cpp.
References jinak.
Referenced by Cage::AddAnimal(), and TEST().
                      {
   return jinak;
 }
void Animal::Render () virtual
Menampilkan karakter inisial dari animal ke layar.
Implements Renderable.
Definition at line 39 of file animal.cpp.
References inisial.
Referenced by Habitat::Render().
                     {
   cout << "\033[1;31m"<<inisial<<' '<<"\033[0m";
 }
void Animal::SetJinak (bool _jinak)
Setter jinak.
Parameters
_jinak Nilai jinak Animal yang ingin dimasukkan
Definition at line 7 of file animal.cpp.
References jinak.
Referenced by Aligator::Aligator(), BadakCulaSatu::BadakCulaSatu(), Banteng::Banteng(), Bekantan::Bekantan(), Buaya::Buaya(), Elang::Elang(), Garuda::Garuda(), HarimauSumatra::HarimauSumatra(), HiuKarpet::HiuKarpet(), HiuMartil::HiuMartil(), Iguana::Iguana(), Kakatua::Kakatua(), Kancil::Kancil(), Komodo::Komodo(), Macan::Macan(), MantaRay::MantaRay(), Nuri::Nuri(), OrangUtan::OrangUtan(), Parkit::Parkit(), Rusa::Rusa(), Siamang::Siamang(), StingRay::StingRay(), and Zebra::Zebra().
{
   jinak = _jinak;
 }
void Animal::SetMassa (int kg)
Setter massa.
Parameters
kg Nilai massa animal yang ingin dimasukkan
Definition at line 22 of file animal.cpp.
References massa.
Referenced by Aligator::Aligator(), BadakCulaSatu::BadakCulaSatu(), Banteng::Banteng(), Bekantan::Bekantan(), Buaya::Buaya(), Elang::Elang(), Garuda::Garuda(), HarimauSumatra::HarimauSumatra(), HiuKarpet::HiuKarpet(), HiuMartil::HiuMartil(), Iguana::Iguana(), Kakatua::Kakatua(), Kancil::Kancil(), Komodo::Komodo(), Macan::Macan(), MantaRay::MantaRay(), Nuri::Nuri(), OrangUtan::OrangUtan(), Parkit::Parkit(), Rusa::Rusa(), Siamang::Siamang(), StingRay::StingRay(), TEST(), and Zebra::Zebra().
{
   massa = kg;
 }
void Animal::SetX (int _x)
Setter x.
Parameters
_x Nilai posisi x animal yang ingin dimasukkan
Definition at line 25 of file animal.cpp.
References x.
Referenced by Aligator::Aligator(), BadakCulaSatu::BadakCulaSatu(), Banteng::Banteng(), Bekantan::Bekantan(), Buaya::Buaya(), Elang::Elang(), Garuda::Garuda(), HarimauSumatra::HarimauSumatra(), HiuKarpet::HiuKarpet(), HiuMartil::HiuMartil(), Iguana::Iguana(), Kakatua::Kakatua(), Kancil::Kancil(), Komodo::Komodo(), Macan::Macan(), MantaRay::MantaRay(), Driver::MoveAnimal(), Nuri::Nuri(), OrangUtan::OrangUtan(), Parkit::Parkit(), Rusa::Rusa(), Siamang::Siamang(), StingRay::StingRay(), TEST(), and Zebra::Zebra().
{
   x = _x;
 }
void Animal::SetY (int _y)
Setter y.
Parameters
_y Nilai posisi y animal yang ingin dimasukkan
Definition at line 28 of file animal.cpp.
References y.
Referenced by Aligator::Aligator(), BadakCulaSatu::BadakCulaSatu(), Banteng::Banteng(), Bekantan::Bekantan(), Buaya::Buaya(), Elang::Elang(), Garuda::Garuda(), HarimauSumatra::HarimauSumatra(), HiuKarpet::HiuKarpet(), HiuMartil::HiuMartil(), Iguana::Iguana(), Kakatua::Kakatua(), Kancil::Kancil(), Komodo::Komodo(), Macan::Macan(), MantaRay::MantaRay(), Driver::MoveAnimal(), Nuri::Nuri(), OrangUtan::OrangUtan(), Parkit::Parkit(), Rusa::Rusa(), Siamang::Siamang(), StingRay::StingRay(), TEST(), and Zebra::Zebra().
{
   y = _y;
 }
Field Documentation
const int Animal::ID private
Definition at line 84 of file animal.h.
Referenced by GetID().
const char Animal::inisial private
Definition at line 85 of file animal.h.
Referenced by GetInisial(), and Render().
bool Animal::jinak private
Definition at line 83 of file animal.h.
Referenced by IsJinak(), and SetJinak().
int Animal::massa private
Definition at line 82 of file animal.h.
Referenced by GetMassa(), and SetMassa().
vector<char> Animal::type private
Definition at line 86 of file animal.h.
Referenced by GetHabitat().
int Animal::x private
Definition at line 80 of file animal.h.
Referenced by GetPosisiX(), and SetX().
int Animal::y private
Definition at line 81 of file animal.h.
Referenced by GetPosisiY(), and SetY().
The documentation for this class was generated from the following files:
src/animal.h
src/animal.cpp