Virtual Zoo: Zoo Class Reference
Zoo Class Reference
#include <zoo.h>
Public Member Functions
Zoo (int x, int y)
Constructor. Menciptakan Zoo kosong dengan lebar x dan panjang y.
Zoo (const Zoo &z)
Copy Constructor. Prekondisi z memiliki width dan length yang sama Mengantisipasi agar tidak bit wise copy.
Zoo & operator= (const Zoo &z)
Operator Assignment Mengoverloading operator samadengan agar Zoo tidak bit wise copy.
~Zoo ()
Destructor.
void SetCell (int x, int y, Cell *cell)
Setter c.
Cell * GetCell (int x, int y)
Getter c.
int GetWidth ()
Getter width.
int GetLength ()
Getter length.
void AddEntrance (Cell *c)
Menambahkan entrance.
void AddExit (Cell *)
Menambahkan exit.
Cell * GetEntrance (int i)
Getter entrance.
Cell * GetExit (int i)
Getter exit.
int NbEntrance ()
Mengembalikan jumlah elemen entrance.
int NbExit ()
Mengembalikan jumlah elemen exit.
Private Attributes
Cell *** c
const int width
const int length
vector< Cell * > entrance
vector< Cell * > exit
Detailed Description
Kelas Zoo terdiri dari matriks cell dan pintu masuk serta keluar
Definition at line 12 of file zoo.h.
Constructor & Destructor Documentation
Zoo::Zoo (int x, int y)
Constructor. Menciptakan Zoo kosong dengan lebar x dan panjang y.
Parameters
x Nilai width Zoo yang ingin diciptakan
y Nilai length Zoo yang ingin diciptakan
Definition at line 6 of file zoo.cpp.
References c, length, and width.
                     : width(x), length(y) {
   c = new Cell**[length];
   for(int i = 0; i < length; i++) {
     c[i] = new Cell*[width];
   }
 }
Zoo::Zoo (const Zoo & z)
Copy Constructor. Prekondisi z memiliki width dan length yang sama Mengantisipasi agar tidak bit wise copy.
Parameters
z Zoo yang ingin dicopy
Definition at line 13 of file zoo.cpp.
References c, length, and width.
                      : length(z.length) , width(z.width) {
   c = new Cell**[length];
   for (int i = 0; i < length; i++) {
     c[i] = new Cell*[width];
   }
   for (int i = 0; i < length; i++) {
     for (int j = 0; j < width; j++) {
       c[i] = z.c[i];
     }
   }
 }
Zoo::~Zoo ()
Destructor.
Definition at line 55 of file zoo.cpp.
References c, and length.
           {
   for(int i = 0; i<length;i++) {
     delete [] c[i];
   }
   delete [] c;
 }
Member Function Documentation
void Zoo::AddEntrance (Cell * c)
Menambahkan entrance.
Parameters
c Cell yang merupakan Entrance
Definition at line 70 of file zoo.cpp.
References entrance.
Referenced by TEST().
{
   entrance.push_back(c);
 }
void Zoo::AddExit (Cell * c)
Menambahkan exit.
Parameters
c Cell yang merupakan Exit
Definition at line 74 of file zoo.cpp.
References exit.
Referenced by TEST().
{
   exit.push_back(c);
 }
Cell * Zoo::GetCell (int x, int y)
Getter c.
Parameters
x Nilai kolom c yang ingin didapatkan.
y Nilai baris c yang ingin didapatkan.
Returns
c.
Definition at line 51 of file zoo.cpp.
References c.
Referenced by Driver::DisplayVirtualZoo(), Driver::InitAnimal(), Driver::MoveAnimal(), TEST(), and Driver::TourVirtualZoo().
{
   return c[y][x];
 }
Cell * Zoo::GetEntrance (int i)
Getter entrance.
Parameters
i Nilai indeks elemen entrance ingin yang didapatkan
Returns
entrance[i]
Definition at line 78 of file zoo.cpp.
References entrance.
Referenced by Driver::InitPosition(), and TEST().
{
   if(i<entrance.size())
     return entrance[i];
   else
     return NULL;
 }
Cell * Zoo::GetExit (int i)
Getter exit.
Parameters
i Nilai indeks elemen exit yang ingin didapatkan
Returns
exit[i]
Definition at line 85 of file zoo.cpp.
References exit.
Referenced by TEST(), and Driver::TourVirtualZoo().
{
   if(i<exit.size())
     return exit[i];
   else
     return NULL;
 }
int Zoo::GetLength ()
Getter length.
Returns
length
Definition at line 66 of file zoo.cpp.
References length.
Referenced by Driver::DisplayVirtualZoo(), Driver::InitAnimal(), Driver::InitPosition(), Driver::MoveAnimal(), TEST(), and Driver::TourVirtualZoo().
                    {
   return length;
 }
int Zoo::GetWidth ()
Getter width.
Returns
width
Definition at line 62 of file zoo.cpp.
References width.
Referenced by Driver::DisplayVirtualZoo(), Driver::InitAnimal(), Driver::InitPosition(), Driver::MoveAnimal(), TEST(), and Driver::TourVirtualZoo().
                   {
   return width;
 }
int Zoo::NbEntrance ()
Mengembalikan jumlah elemen entrance.
Returns
Banyaknya elemen entrance
Definition at line 92 of file zoo.cpp.
References entrance.
Referenced by Driver::InitPosition(), and TEST().
                     {
   return entrance.size();
 }
int Zoo::NbExit ()
Mengembalikan jumlah elemen exit.
Returns
Banyaknya elemen exit
Definition at line 96 of file zoo.cpp.
References exit.
Referenced by TEST(), and Driver::TourVirtualZoo().
                 {
   return exit.size();
 }
Zoo & Zoo::operator= (const Zoo & z)
Operator Assignment Mengoverloading operator samadengan agar Zoo tidak bit wise copy.
Parameters
z Nilai zoo yang ingin di masukkan
Returns
this zoo yang sudah sama dengan z
Definition at line 26 of file zoo.cpp.
References c, length, and width.
{
   if (this != &z) {
     for(int i = 0; i<length;i++) {
       delete [] c[i];
     }
     delete [] c;
     c = new Cell**[length];
     for (int i = 0; i < length; i++) {
       c[i] = new Cell*[width];
     }
     for (int i = 0; i < length; i++) {
       for (int j = 0; j < width; j++) {
         c[i] = z.c[i];
       }
     }
   }
   return *this;
 }
void Zoo::SetCell (int x, int y, Cell * cell)
Setter c.
Parameters
x Nilai kolom c yang akan di set.
y Nilai baris c yang akan di set.
cell Nilai c yang akan dimasukkan.
Definition at line 47 of file zoo.cpp.
References c.
Referenced by TEST().
{
   c[y][x]=cell;
 }
Field Documentation
Cell*** Zoo::c private
Definition at line 83 of file zoo.h.
Referenced by GetCell(), operator=(), SetCell(), Zoo(), and ~Zoo().
vector<Cell*> Zoo::entrance private
Definition at line 86 of file zoo.h.
Referenced by AddEntrance(), GetEntrance(), and NbEntrance().
vector<Cell*> Zoo::exit private
Definition at line 87 of file zoo.h.
Referenced by AddExit(), GetExit(), and NbExit().
const int Zoo::length private
Definition at line 85 of file zoo.h.
Referenced by GetLength(), operator=(), Zoo(), and ~Zoo().
const int Zoo::width private
Definition at line 84 of file zoo.h.
Referenced by GetWidth(), operator=(), and Zoo().
The documentation for this class was generated from the following files:
src/zoo.h
src/zoo.cpp