Virtual Zoo: nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser Class Reference
nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser Class Reference
syntax analysis
Public Member Functions
parser (const char *buff, const parser_callback_t cb=nullptr)
a parser reading from a string literal
parser (std::istream &is, const parser_callback_t cb=nullptr)
a parser reading from an input stream
template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type = 0>
parser (IteratorType first, IteratorType last, const parser_callback_t cb=nullptr)
a parser reading from an iterator range with contiguous storage
basic_json parse ()
public parser interface
Private Member Functions
basic_json parse_internal (bool keep)
the actual parser
lexer::token_type get_token ()
get next token from lexer
void expect (typename lexer::token_type t) const
void unexpect (typename lexer::token_type t) const
Private Attributes
int depth = 0
current level of recursion
const parser_callback_t callback = nullptr
callback function
lexer::token_type last_token = lexer::token_type::uninitialized
the type of the last read token
lexer m_lexer
the lexer
Detailed Description
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer>
class nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser
syntax analysis
This class implements a recursive decent parser.
Definition at line 11049 of file json.hpp.
Constructor & Destructor Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parser (const char * buff, const parser_callback_t cb = nullptr) inline
a parser reading from a string literal
Definition at line 11053 of file json.hpp.
             : callback(cb),
               m_lexer(reinterpret_cast<const typename lexer::lexer_char_t*>(buff), std::strlen(buff))
         {}
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parser (std::istream & is, const parser_callback_t cb = nullptr) inline
a parser reading from an input stream
Definition at line 11059 of file json.hpp.
             : callback(cb), m_lexer(is)
         {}
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> template<class IteratorType , typename std::enable_if< std::is_same< typename std::iterator_traits< IteratorType >::iterator_category, std::random_access_iterator_tag >::value, int >::type = 0> nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parser (IteratorType first, IteratorType last, const parser_callback_t cb = nullptr) inline
a parser reading from an iterator range with contiguous storage
Definition at line 11068 of file json.hpp.
             : callback(cb),
               m_lexer(reinterpret_cast<const typename lexer::lexer_char_t*>(&(*first)),
                       static_cast<size_t>(std::distance(first, last)))
         {}
Member Function Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::expect (typename lexer::token_type t) const inline private
Definition at line 11292 of file json.hpp.
References JSON_THROW, and nlohmann::detail::string.
         {
             if (t != last_token)
             {
                 std::string error_msg = "parse error - unexpected ";
                 error_msg += (last_token == lexer::token_type::parse_error ? ("'" +  m_lexer.get_token_string() +
                               "'") :
                               lexer::token_type_name(last_token));
                 error_msg += "; expected " + lexer::token_type_name(t);
                 JSON_THROW(std::invalid_argument(error_msg));
             }
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> lexer::token_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::get_token () inline private
get next token from lexer
Definition at line 11286 of file json.hpp.
         {
             last_token = m_lexer.scan();
             return last_token;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse () inline
public parser interface
Definition at line 11075 of file json.hpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::assert_invariant(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::is_discarded().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::basic_json(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parse().
         {
             // read first token
             get_token();
             basic_json result = parse_internal(true);
             result.assert_invariant();
             expect(lexer::token_type::end_of_input);
             // return parser result and replace it with null in case the
             // top-level value was discarded by the callback function
             return result.is_discarded() ? basic_json() : std::move(result);
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> basic_json nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::parse_internal (bool keep) inline private
the actual parser
Definition at line 11092 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, and nlohmann::detail::object.
         {
             auto result = basic_json(value_t::discarded);
             switch (last_token)
             {
                 case lexer::token_type::begin_object:
                 {
                     if (keep and (not callback
                                   or ((keep = callback(depth++, parse_event_t::object_start, result)) != 0)))
                     {
                         // explicitly set result to object to cope with {}
                         result.m_type = value_t::object;
                         result.m_value = value_t::object;
                     }
                     // read next token
                     get_token();
                     // closing } -> we are done
                     if (last_token == lexer::token_type::end_object)
                     {
                         get_token();
                         if (keep and callback and not callback(--depth, parse_event_t::object_end, result))
{
                             result = basic_json(value_t::discarded);
                         }
                         return result;
                     }
                     // no comma is expected here
                     unexpect(lexer::token_type::value_separator);
                     // otherwise: parse key-value pairs
                     do
                     {
                         // ugly, but could be fixed with loop reorganization
                         if (last_token == lexer::token_type::value_separator)
{
                             get_token();
                         }
                         // store key
                         expect(lexer::token_type::value_string);
                         const auto key = m_lexer.get_string();
                         bool keep_tag = false;
                         if (keep)
{
                             if (callback)
{
                                 basic_json k(key);
                                 keep_tag = callback(depth, parse_event_t::key, k);
                             }
                             else
{
                                 keep_tag = true;
                             }
                         }
                         // parse separator (:)
                         get_token();
                         expect(lexer::token_type::name_separator);
                         // parse and add value
                         get_token();
                         auto value = parse_internal(keep);
                         if (keep and keep_tag and not value.is_discarded())
{
                             result[key] = std::move(value);
                         }
                     }
                     while (last_token == lexer::token_type::value_separator);
                     // closing }
                     expect(lexer::token_type::end_object);
                     get_token();
                     if (keep and callback and not callback(--depth, parse_event_t::object_end, result))
                     {
                         result = basic_json(value_t::discarded);
                     }
                     return result;
                 }
                 case lexer::token_type::begin_array:
                 {
                     if (keep and (not callback
                                   or ((keep = callback(depth++, parse_event_t::array_start, result)) != 0)))
                     {
                         // explicitly set result to object to cope with []
                         result.m_type = value_t::array;
                         result.m_value = value_t::array;
                     }
                     // read next token
                     get_token();
                     // closing ] -> we are done
                     if (last_token == lexer::token_type::end_array)
                     {
                         get_token();
                         if (callback and not callback(--depth, parse_event_t::array_end, result))
{
                             result = basic_json(value_t::discarded);
                         }
                         return result;
                     }
                     // no comma is expected here
                     unexpect(lexer::token_type::value_separator);
                     // otherwise: parse values
                     do
                     {
                         // ugly, but could be fixed with loop reorganization
                         if (last_token == lexer::token_type::value_separator)
{
                             get_token();
                         }
                         // parse value
                         auto value = parse_internal(keep);
                         if (keep and not value.is_discarded())
{
                             result.push_back(std::move(value));
                         }
                     }
                     while (last_token == lexer::token_type::value_separator);
                     // closing ]
                     expect(lexer::token_type::end_array);
                     get_token();
                     if (keep and callback and not callback(--depth, parse_event_t::array_end, result))
                     {
                         result = basic_json(value_t::discarded);
                     }
                     return result;
                 }
                 case lexer::token_type::literal_null:
                 {
                     get_token();
                     result.m_type = value_t::null;
                     break;
                 }
                 case lexer::token_type::value_string:
                 {
                     const auto s = m_lexer.get_string();
                     get_token();
                     result = basic_json(s);
                     break;
                 }
                 case lexer::token_type::literal_true:
                 {
                     get_token();
                     result.m_type = value_t::boolean;
                     result.m_value = true;
                     break;
                 }
                 case lexer::token_type::literal_false:
                 {
                     get_token();
                     result.m_type = value_t::boolean;
                     result.m_value = false;
                     break;
                 }
                 case lexer::token_type::value_number:
                 {
                     m_lexer.get_number(result);
                     get_token();
                     break;
                 }
                 default:
                 {
                     // the last token was unexpected
                     unexpect(last_token);
                 }
             }
             if (keep and callback and not callback(depth, parse_event_t::value, result))
             {
                 result = basic_json(value_t::discarded);
             }
             return result;
         }
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> void nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::unexpect (typename lexer::token_type t) const inline private
Definition at line 11305 of file json.hpp.
References JSON_THROW, and nlohmann::detail::string.
         {
             if (t == last_token)
             {
                 std::string error_msg = "parse error - unexpected ";
                 error_msg += (last_token == lexer::token_type::parse_error ? ("'" +  m_lexer.get_token_string() +
                               "'") :
                               lexer::token_type_name(last_token));
                 JSON_THROW(std::invalid_argument(error_msg));
             }
         }
Field Documentation
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> const parser_callback_t nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::callback = nullptr private
callback function
Definition at line 11321 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> int nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::depth = 0 private
current level of recursion
Definition at line 11319 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> lexer::token_type nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::last_token = lexer::token_type::uninitialized private
the type of the last read token
Definition at line 11323 of file json.hpp.
template<template< typename U, typename V, typename...Args > class ObjectType = std::map, template< typename U, typename...Args > class ArrayType = std::vector, class StringType = std::string, class BooleanType = bool, class NumberIntegerType = std::int64_t, class NumberUnsignedType = std::uint64_t, class NumberFloatType = double, template< typename U > class AllocatorType = std::allocator, template< typename T, typename SFINAE=void > class JSONSerializer = adl_serializer> lexer nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::parser::m_lexer private
the lexer
Definition at line 11325 of file json.hpp.
The documentation for this class was generated from the following file:
src/json.hpp