Virtual Zoo: Omnivora Class Reference
Omnivora Class Reference
#include <omnivora.h>
Public Member Functions
void SetAmount (int n)
Setter daging_tumbuhan.
int GetAmount ()
Getter daging_tumbuhan.
Protected Attributes
int daging_tumbuhan
Detailed Description
Kelas Omnivora menyimpan informasi makanan perpaduan daging dan tumbuhan
Definition at line 10 of file omnivora.h.
Member Function Documentation
int Omnivora::GetAmount () virtual
Getter daging_tumbuhan.
Returns
daging_tumbuhan
Implements Pemakan.
Definition at line 6 of file omnivora.cpp.
References daging_tumbuhan.
Referenced by Bekantan::GetJmlMakanan(), Siamang::GetJmlMakanan(), OrangUtan::GetJmlMakanan(), and TEST().
{
   return daging_tumbuhan;
 }
void Omnivora::SetAmount (int n)
Setter daging_tumbuhan.
Parameters
n Jumlah daging_tumbuhan yang diinginkan
Definition at line 3 of file omnivora.cpp.
References daging_tumbuhan.
Referenced by Bekantan::Bekantan(), OrangUtan::OrangUtan(), Siamang::Siamang(), and TEST().
{
   daging_tumbuhan = n;
 }
Field Documentation
int Omnivora::daging_tumbuhan protected
Definition at line 22 of file omnivora.h.
Referenced by GetAmount(), and SetAmount().
The documentation for this class was generated from the following files:
src/omnivora.h
src/omnivora.cpp