Virtual Zoo: Cage Class Reference
Cage Class Reference
#include <cage.h>
Public Member Functions
Cage (int _id, char hab)
Constructor. Menciptakan Cage dengan id _id dan habitat hab.
void AddAnimal (Animal *a)
Menambahkan elemen ke animal.
void AddCell (char c)
Menambahkan cell Penambahan cell akan menambah luas dari cage.
int GetId ()
Getter id.
int GetLuas ()
Getter luas.
int GetNbAnimal ()
Mengembalikan banyaknya elemen animal.
char GetHabitat ()
Getter habitat.
bool IsAvailable ()
Mengetahui apakah cage available Mengecek apakah cage dapat ditambahkan elemen animal.
bool IsIsiJinak ()
Mengetahui apakah elemen animal jinak.
Private Attributes
int luas
const int id
const char habitat
vector< Animal * > animal
Detailed Description
Kelas Cage terdiri dari animal dengan luas, id, dan habitat tertentu Representasi kumpulan cage dengan habitat sejenis
Definition at line 13 of file cage.h.
Constructor & Destructor Documentation
Cage::Cage (int _id, char hab)
Constructor. Menciptakan Cage dengan id _id dan habitat hab.
Parameters
_id Nilai id Cage yang ingin diciptakan
hab Nilai habitat Cage yang ingin diciptakan
Definition at line 5 of file cage.cpp.
References luas.
                            : id(_id), habitat(hab) {
   luas = 0;
 }
Member Function Documentation
void Cage::AddAnimal (Animal * a)
Menambahkan elemen ke animal.
Parameters
a elemen yang ingin ditambahkan ke animal
Definition at line 9 of file cage.cpp.
References animal, GetHabitat(), Animal::GetHabitat(), Animal::GetInisial(), IsAvailable(), IsIsiJinak(), and Animal::IsJinak().
Referenced by Driver::InitAnimal(), and TEST().
{
   bool feasible = false;
   int i = 0;
   while((!feasible)&& i<(a->GetHabitat()).size()) {
     if((a->GetHabitat())[i]==this->GetHabitat())
       feasible=true;
     else
       i++;
   }
   if(feasible) {
     if(animal.size()==0) {
       animal.push_back(a);
     } else {
         if(a->IsJinak()) {
           if(this->IsIsiJinak()) {
             if(this->IsAvailable())
               animal.push_back(a);
             else
               throw ZooExp(0);
           } else
               throw ZooExp(3);
       } else {
           if(animal[0]->GetInisial()==a->GetInisial()) {
             if(this->IsAvailable())
               animal.push_back(a);
             else
               throw ZooExp(0);
           } else
               throw ZooExp(3);
       }
     }
   } else
       throw ZooExp(1);
 }
void Cage::AddCell (char c)
Menambahkan cell Penambahan cell akan menambah luas dari cage.
Parameters
c Habitat
Definition at line 46 of file cage.cpp.
References GetHabitat(), and luas.
Referenced by Driver::InitZoo(), and TEST().
{
   if(c==this->GetHabitat())
     luas++;
   else
     throw ZooExp(2);
 }
char Cage::GetHabitat ()
Getter habitat.
Returns
habitat
Definition at line 65 of file cage.cpp.
References habitat.
Referenced by AddAnimal(), AddCell(), and TEST().
                       {
   return habitat;
 }
int Cage::GetId ()
Getter id.
Returns
id
Definition at line 53 of file cage.cpp.
References id.
Referenced by Driver::MoveAnimal(), and TEST().
                 {
   return id;
 }
int Cage::GetLuas ()
Getter luas.
Returns
luas
Definition at line 57 of file cage.cpp.
References luas.
Referenced by TEST().
                   {
   return luas;
 }
int Cage::GetNbAnimal ()
Mengembalikan banyaknya elemen animal.
Returns
size dari animal
Definition at line 61 of file cage.cpp.
References animal.
Referenced by IsAvailable(), and TEST().
                       {
   return animal.size();
 }
bool Cage::IsAvailable ()
Mengetahui apakah cage available Mengecek apakah cage dapat ditambahkan elemen animal.
Returns
Apakah cage availabe
Definition at line 69 of file cage.cpp.
References GetNbAnimal(), and luas.
Referenced by AddAnimal().
{
   return(this->GetNbAnimal()<((3*luas)/10));
 }
bool Cage::IsIsiJinak ()
Mengetahui apakah elemen animal jinak.
Returns
Apakah semua elemen animal jinak
Definition at line 73 of file cage.cpp.
References animal.
Referenced by AddAnimal(), and TEST().
                       {
   bool found=false;
   int i=0;
   while((!found) && i<animal.size()) {
     if(!(animal[i]->IsJinak()))
       found=true;
     else
       i++;
   }
   return !found;
 }
Field Documentation
vector<Animal*> Cage::animal private
Definition at line 60 of file cage.h.
Referenced by AddAnimal(), GetNbAnimal(), and IsIsiJinak().
const char Cage::habitat private
Definition at line 59 of file cage.h.
Referenced by GetHabitat().
const int Cage::id private
Definition at line 58 of file cage.h.
Referenced by GetId().
int Cage::luas private
Definition at line 57 of file cage.h.
Referenced by AddCell(), Cage(), GetLuas(), and IsAvailable().
The documentation for this class was generated from the following files:
src/cage.h
src/cage.cpp