Virtual Zoo: test/orang_utan_test.cpp File Reference
orang_utan_test.cpp File Reference
#include "../src/include.h"
#include <gtest/gtest.h>
Data Structures
class OrangUtanTest
Functions
TEST (OrangUtanTest, OrangUtanConstructor)
TEST (OrangUtanTest, OrangUtanInteract)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 32 of file orang_utan_test.cpp.
{
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
TEST (OrangUtanTest , OrangUtanConstructor)
Definition at line 10 of file orang_utan_test.cpp.
References Animal::GetID(), OrangUtan::GetJmlMakanan(), Animal::GetPosisiX(), Animal::GetPosisiY(), and Animal::IsJinak().
{
   OrangUtan o(1, 10, 1, 100, true);
   EXPECT_EQ(6, o.GetJmlMakanan());
   EXPECT_EQ(1, o.GetID());
   EXPECT_EQ(true, o.IsJinak());
   EXPECT_EQ(10, o.GetPosisiX());
   EXPECT_EQ(1, o.GetPosisiY());
 }
TEST (OrangUtanTest , OrangUtanInteract)
Definition at line 20 of file orang_utan_test.cpp.
References OrangUtan::Interact().
{
   OrangUtan o(1, 10, 1, 100, true);
   std::stringstream buffer;
   std::streambuf * old = std::cout.rdbuf(buffer.rdbuf());
   o.Interact();
   std::string text = buffer.str();
   std::cout.rdbuf( old );
   EXPECT_EQ("Orang Utan: \"Auooo\"\n", text);
 }