Virtual Zoo: test/perrisodactyl_test.cpp File Reference
perrisodactyl_test.cpp File Reference
#include "../src/include.h"
#include <gtest/gtest.h>
Data Structures
class PerrisodactylTest
Functions
TEST (PerrisodactylTest, PrittaciformesConstructor)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 20 of file perrisodactyl_test.cpp.
{
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
TEST (PerrisodactylTest , PrittaciformesConstructor)
Definition at line 9 of file perrisodactyl_test.cpp.
References Animal::GetID(), Animal::GetInisial(), Zebra::GetJmlMakanan(), Animal::GetPosisiX(), Animal::GetPosisiY(), and Animal::IsJinak().
{
   Zebra o(1, 10, 1, 3, true);
   EXPECT_EQ(1, o.GetJmlMakanan());
   EXPECT_EQ(1, o.GetID());
   EXPECT_EQ(true, o.IsJinak());
   EXPECT_EQ(10, o.GetPosisiX());
   EXPECT_EQ(1, o.GetPosisiY());
   EXPECT_EQ('Z', o.GetInisial());
 }