SRCS = include.h\
	animal.h \
	animal.cpp \
	land_animal.h \
	land_animal.cpp \
	water_animal.h \
	water_animal.cpp \
	flying_animal.h \
	flying_animal.cpp \
	land_water_animal.h \
	land_water_animal.cpp \
	land_air_animal.h \
	land_air_animal.cpp \
	water_air_animal.h \
	water_air_animal.cpp \
	squamata.h \
	squamata.cpp \
	primate.h \
	primate.cpp \
	carnivore.h \
	carnivore.cpp \
	artiodactyl.h \
	artiodactyl.cpp \
	perrisodactyl.h \
	perrisodactyl.cpp \
	crocodillia.h \
	crocodillia.cpp \
	carcharhiniformes.h \
	carcharhiniformes.cpp \
	rajiformes.h \
	rajiformes.cpp \
	falconiformes.h \
	falconiformes.cpp \
	prittaciformes.h \
	prittaciformes.cpp \
	animal_handler.h \
	animal_handler.cpp \
	banteng.h \
	banteng.cpp \
	bekantan.h \
	bekantan.cpp \
	badak_cula_satu.h \
	badak_cula_satu.cpp \
	buaya.h \
	buaya.cpp \
	rusa.h \
	rusa.cpp \
	parkit.h \
	parkit.cpp \
	garuda.h \
	garuda.cpp \
	harimau_sumatra.h \
	harimau_sumatra.cpp \
	iguana.h \
	iguana.cpp \
	komodo.h \
	komodo.cpp \
	kancil.h \
	kancil.cpp \
	aligator.h \
	aligator.cpp \
	macan.h \
	macan.cpp \
	nuri.h \
	nuri.cpp \
	kakatua.h \
	kakatua.cpp \
	manta_ray.h \
	manta_ray.cpp \
	siamang.h \
	siamang.cpp \
	hiu_martil.h \
	hiu_martil.cpp \
	hiu_karpet.h \
	hiu_karpet.cpp \
	sting_ray.h \
	sting_ray.cpp \
	zebra.h \
	zebra.cpp \
	elang.h \
	elang.cpp \
	cell.h \
	cell.cpp \
	habitat.h \
	habitat.cpp \
	facility.h \
	facility.cpp \
	land_habitat.h \
	land_habitat.cpp \
	water_habitat.h \
	water_habitat.cpp \
	air_habitat.h \
	air_habitat.cpp \
	restaurant.h \
	restaurant.cpp \
	road.h \
	road.cpp \
	entrance.h \
	entrance.cpp \
	exit.h \
	exit.cpp \
	park.h \
	park.cpp \
	zooexp.h \
	zooexp.cpp \
	cage.h \
	cage.cpp \
	cage_handler.h \
	cage_handler.cpp  \
	driver.h \
	driver.cpp \
	zoo.h \
	zoo.cpp \
	pemakan.h \
	karnivora.h \
	karnivora.cpp \
	herbivora.h \
	herbivora.cpp \
	omnivora.h \
	omnivora.cpp \
	renderable.h \
	renderable.cpp

OBJS = ../bin/animal.o \
	../bin/land_animal.o \
	../bin/water_animal.o \
	../bin/flying_animal.o \
	../bin/land_water_animal.o \
	../bin/land_air_animal.o \
	../bin/water_air_animal.o \
	../bin/squamata.o \
	../bin/primate.o \
	../bin/carnivore.o \
	../bin/artiodactyl.o \
	../bin/perrisodactyl.o \
	../bin/crocodillia.o \
	../bin/carcharhiniformes.o \
	../bin/rajiformes.o \
	../bin/falconiformes.o \
	../bin/prittaciformes.o \
	../bin/animal_handler.o \
	../bin/banteng.o \
	../bin/bekantan.o \
	../bin/badak_cula_satu.o \
	../bin/buaya.o \
	../bin/rusa.o \
	../bin/parkit.o \
	../bin/garuda.o \
	../bin/harimau_sumatra.o \
	../bin/iguana.o \
	../bin/komodo.o \
	../bin/kancil.o \
	../bin/aligator.o \
	../bin/macan.o \
	../bin/nuri.o \
	../bin/kakatua.o \
	../bin/manta_ray.o \
	../bin/siamang.o \
	../bin/hiu_martil.o \
	../bin/orang_utan.o \
	../bin/hiu_karpet.o \
	../bin/sting_ray.o \
	../bin/zebra.o \
	../bin/elang.o \
	../bin/cell.o \
	../bin/habitat.o \
	../bin/facility.o \
	../bin/land_habitat.o \
	../bin/water_habitat.o \
	../bin/air_habitat.o \
	../bin/restaurant.o \
	../bin/park.o \
	../bin/road.o \
	../bin/entrance.o \
	../bin/exit.o \
	../bin/zooexp.o \
	../bin/cage.o \
	../bin/cage_handler.o \
	../bin/driver.o \
	../bin/zoo.o \
	../bin/karnivora.o \
	../bin/herbivora.o \
	../bin/omnivora.o \
	../bin/renderable.o \
	main.cpp

all: buildobject buildall

buildobject: $(SRCS)
	g++ animal.cpp -c -o ../bin/animal.o -std=c++11
	g++ land_animal.cpp -c -o ../bin/land_animal.o -std=c++11
	g++ water_animal.cpp -c -o ../bin/water_animal.o -std=c++11
	g++ flying_animal.cpp -c -o ../bin/flying_animal.o -std=c++11
	g++ land_water_animal.cpp -c -o ../bin/land_water_animal.o -std=c++11
	g++ land_air_animal.cpp -c -o ../bin/land_air_animal.o -std=c++11
	g++ water_air_animal.cpp -c -o ../bin/water_air_animal.o -std=c++11
	g++ squamata.cpp -c -o ../bin/squamata.o -std=c++11
	g++ primate.cpp -c -o ../bin/primate.o -std=c++11
	g++ carnivore.cpp -c -o ../bin/carnivore.o -std=c++11
	g++ artiodactyl.cpp -c -o ../bin/artiodactyl.o -std=c++11
	g++ perrisodactyl.cpp -c -o ../bin/perrisodactyl.o -std=c++11
	g++ crocodillia.cpp -c -o ../bin/crocodillia.o -std=c++11
	g++ carcharhiniformes.cpp -c -o ../bin/carcharhiniformes.o -std=c++11
	g++ rajiformes.cpp -c -o ../bin/rajiformes.o -std=c++11
	g++ falconiformes.cpp -c -o ../bin/falconiformes.o -std=c++11
	g++ prittaciformes.cpp -c -o ../bin/prittaciformes.o -std=c++11
	g++ animal_handler.cpp -c -o ../bin/animal_handler.o -std=c++11
	g++ banteng.cpp -c -o ../bin/banteng.o -std=c++11
	g++ bekantan.cpp -c -o ../bin/bekantan.o -std=c++11
	g++ badak_cula_satu.cpp -c -o ../bin/badak_cula_satu.o -std=c++11
	g++ buaya.cpp -c -o ../bin/buaya.o -std=c++11
	g++ rusa.cpp -c -o ../bin/rusa.o -std=c++11
	g++ parkit.cpp -c -o ../bin/parkit.o -std=c++11
	g++ garuda.cpp -c -o ../bin/garuda.o -std=c++11
	g++ harimau_sumatra.cpp -c -o ../bin/harimau_sumatra.o -std=c++11
	g++ iguana.cpp -c -o ../bin/iguana.o -std=c++11
	g++ komodo.cpp -c -o ../bin/komodo.o -std=c++11
	g++ kancil.cpp -c -o ../bin/kancil.o -std=c++11
	g++ aligator.cpp -c -o ../bin/aligator.o -std=c++11
	g++ macan.cpp -c -o ../bin/macan.o -std=c++11
	g++ nuri.cpp -c -o ../bin/nuri.o -std=c++11
	g++ kakatua.cpp -c -o ../bin/kakatua.o -std=c++11
	g++ manta_ray.cpp -c -o ../bin/manta_ray.o -std=c++11
	g++ siamang.cpp -c -o ../bin/siamang.o -std=c++11
	g++ hiu_martil.cpp -c -o ../bin/hiu_martil.o -std=c++11
	g++ orang_utan.cpp -c -o ../bin/orang_utan.o -std=c++11
	g++ hiu_karpet.cpp -c -o ../bin/hiu_karpet.o -std=c++11
	g++ sting_ray.cpp -c -o ../bin/sting_ray.o -std=c++11
	g++ zebra.cpp -c -o ../bin/zebra.o -std=c++11
	g++ elang.cpp -c -o ../bin/elang.o -std=c++11
	g++ cell.cpp -c -o ../bin/cell.o -std=c++11
	g++ habitat.cpp -c -o ../bin/habitat.o -std=c++11
	g++ facility.cpp -c -o ../bin/facility.o -std=c++11
	g++ land_habitat.cpp -c -o ../bin/land_habitat.o -std=c++11
	g++ water_habitat.cpp -c -o ../bin/water_habitat.o -std=c++11
	g++ air_habitat.cpp -c -o ../bin/air_habitat.o -std=c++11
	g++ restaurant.cpp -c -o ../bin/restaurant.o -std=c++11
	g++ park.cpp -c -o ../bin/park.o -std=c++11
	g++ road.cpp -c -o ../bin/road.o -std=c++11
	g++ entrance.cpp -c -o ../bin/entrance.o -std=c++11
	g++ exit.cpp -c -o ../bin/exit.o -std=c++11
	g++ zooexp.cpp -c -o ../bin/zooexp.o -std=c++11
	g++ cage.cpp -c -o ../bin/cage.o -std=c++11
	g++ cage_handler.cpp -c -o ../bin/cage_handler.o -std=c++11
	g++ driver.cpp -c -o ../bin/driver.o -std=c++11
	g++ zoo.cpp -c -o ../bin/zoo.o -std=c++11
	g++ karnivora.cpp -c -o ../bin/karnivora.o -std=c++11
	g++ herbivora.cpp -c -o ../bin/herbivora.o -std=c++11
	g++ omnivora.cpp -c -o ../bin/omnivora.o -std=c++11
	g++ renderable.cpp -c -o ../bin/renderable.o -std=c++11

buildall: $(OBJS)
	g++ $(OBJS) -o main -std=c++11

map: map_generator.cpp
	g++ map_generator.cpp -o ../bin/map_generator -std=c++11
	./../bin/map_generator